spring:
  application:
    name: "aprimorar-api"
  profiles:
    active: "dev"
  mvc:
    problemdetails:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  override-with-generic-response: false
