sonar.projectKey=aprimorar-client
sonar.projectName=Aprimorar Client

sonar.sources=src
sonar.exclusions=src/kubb/**,src/gen/**,node_modules/**,dist/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

# TypeScript config
sonar.typescript.tsconfigPaths=tsconfig.json,tsconfig.app.json,tsconfig.node.json

# Memory for large TS projects
sonar.javascript.node.maxspace=4096
