/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ArchiveAlunoPathParams = {
  /**
   * @type string, uuid
   */
  alunoId: string;
};

/**
 * @description Aluno arquivado com sucesso.
 */
export type ArchiveAluno204 = any;

export type ArchiveAlunoMutationResponse = ArchiveAluno204;

export type ArchiveAlunoMutation = {
  Response: ArchiveAluno204;
  PathParams: ArchiveAlunoPathParams;
  Errors: any;
};
