/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type ArchiveAlunoPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno arquivado com sucesso.
 */
export type ArchiveAluno204 = any;

/**
 * @description Aluno não encontrado
 */
export type ArchiveAluno404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type ArchiveAluno409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type ArchiveAluno500 = ProblemResponseDTO;

export type ArchiveAlunoMutationResponse = ArchiveAluno204;

export type ArchiveAlunoMutation = {
  Response: ArchiveAluno204;
  PathParams: ArchiveAlunoPathParams;
  Errors: ArchiveAluno404 | ArchiveAluno409 | ArchiveAluno500;
};
