/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlunoResponseDTO } from "../AlunoResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type BuscarAlunoPorIdPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno retornado com sucesso.
 */
export type BuscarAlunoPorId200 = AlunoResponseDTO;

/**
 * @description Aluno não encontrado
 */
export type BuscarAlunoPorId404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type BuscarAlunoPorId500 = ProblemResponseDTO;

export type BuscarAlunoPorIdQueryResponse = BuscarAlunoPorId200;

export type BuscarAlunoPorIdQuery = {
  Response: BuscarAlunoPorId200;
  PathParams: BuscarAlunoPorIdPathParams;
  Errors: BuscarAlunoPorId404 | BuscarAlunoPorId500;
};
