/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type DesarquivarAlunoPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno desarquivado com sucesso.
 */
export type DesarquivarAluno204 = any;

/**
 * @description Aluno não encontrado
 */
export type DesarquivarAluno404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type DesarquivarAluno409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type DesarquivarAluno500 = ProblemResponseDTO;

export type DesarquivarAlunoMutationResponse = DesarquivarAluno204;

export type DesarquivarAlunoMutation = {
  Response: DesarquivarAluno204;
  PathParams: DesarquivarAlunoPathParams;
  Errors: DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500;
};
