/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AlunosKpisDTO } from "../AlunosKpisDTO.ts";

/**
 * @description KPIs de alunos retornados com sucesso.
*/
export type GetAlunosKpis200 = AlunosKpisDTO;

export type GetAlunosKpisQueryResponse = GetAlunosKpis200;

export type GetAlunosKpisQuery = {
    Response: GetAlunosKpis200;
    Errors: any;
};