/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlunoResponseDTO } from "../AlunoResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetAlunoByIdPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno retornado com sucesso.
 */
export type GetAlunoById200 = AlunoResponseDTO;

/**
 * @description Aluno não encontrado
 */
export type GetAlunoById404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetAlunoById500 = ProblemResponseDTO;

export type GetAlunoByIdQueryResponse = GetAlunoById200;

export type GetAlunoByIdQuery = {
  Response: GetAlunoById200;
  PathParams: GetAlunoByIdPathParams;
  Errors: GetAlunoById404 | GetAlunoById500;
};
