/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlunosListDTO } from "../AlunosListDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

/**
 * @description Lista de opções de alunos retornada com sucesso.
 */
export type ListarOpcoesAlunos200 = AlunosListDTO[];

/**
 * @description Erro interno do sistema
 */
export type ListarOpcoesAlunos500 = ProblemResponseDTO;

export type ListarOpcoesAlunosQueryResponse = ListarOpcoesAlunos200;

export type ListarOpcoesAlunosQuery = {
  Response: ListarOpcoesAlunos200;
  Errors: ListarOpcoesAlunos500;
};
