/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlunosListDTO } from "../AlunosListDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

/**
 * @description Lista de opções de alunos retornada com sucesso.
 */
export type ListAlunos200 = AlunosListDTO[];

/**
 * @description Erro interno do sistema
 */
export type ListAlunos500 = ProblemResponseDTO;

export type ListAlunosQueryResponse = ListAlunos200;

export type ListAlunosQuery = {
  Response: ListAlunos200;
  Errors: ListAlunos500;
};
