/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UnarchiveAlunoPathParams = {
    /**
     * @type string, uuid
    */
    alunoId: string;
};

/**
 * @description Aluno desarquivado com sucesso.
*/
export type UnarchiveAluno204 = any;

export type UnarchiveAlunoMutationResponse = UnarchiveAluno204;

export type UnarchiveAlunoMutation = {
    Response: UnarchiveAluno204;
    PathParams: UnarchiveAlunoPathParams;
    Errors: any;
};