/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StudentCreateDTO } from "../StudentCreateDTO.ts";
import type { StudentResponseDTO } from "../StudentResponseDTO.ts";

/**
 * @description Aluno criado com sucesso.
 */
export type CreateStudent201 = StudentResponseDTO;

export type CreateStudentMutationRequest = StudentCreateDTO;

export type CreateStudentMutationResponse = CreateStudent201;

export type CreateStudentMutation = {
  Response: CreateStudent201;
  Request: CreateStudentMutationRequest;
  Errors: any;
};
