/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";
import type { StudentRequestDTO } from "../StudentRequestDTO.ts";
import type { StudentResponseDTO } from "../StudentResponseDTO.ts";

/**
 * @description Aluno criado com sucesso
 */
export type CreateStudent200 = StudentResponseDTO;

/**
 * @description Requisição inválida
 */
export type CreateStudent400 = ProblemDetailResponseDTO;

export type CreateStudentMutationRequest = StudentRequestDTO;

export type CreateStudentMutationResponse = CreateStudent200;

export type CreateStudentMutation = {
  Response: CreateStudent200;
  Request: CreateStudentMutationRequest;
  Errors: CreateStudent400;
};
