/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

export type DeleteStudentPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno deletado com sucesso
 */
export type DeleteStudent204 = any;

/**
 * @description Requisição inválida
 */
export type DeleteStudent400 = ProblemDetailResponseDTO;

export type DeleteStudentMutationResponse = DeleteStudent204;

export type DeleteStudentMutation = {
  Response: DeleteStudent204;
  PathParams: DeleteStudentPathParams;
  Errors: DeleteStudent400;
};
