/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PagedModelStudentResponseDTO } from "../PagedModelStudentResponseDTO.ts";
import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

export type GetStudentsQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @description Termo de busca
   * @type string | undefined
   */
  search?: string;
};

/**
 * @description Listagem dos alunos com paginação
 */
export type GetStudents200 = PagedModelStudentResponseDTO;

/**
 * @description Requisição inválida
 */
export type GetStudents400 = ProblemDetailResponseDTO;

export type GetStudentsQueryResponse = GetStudents200;

export type GetStudentsQuery = {
  Response: GetStudents200;
  QueryParams: GetStudentsQueryParams;
  Errors: GetStudents400;
};
