/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";
import type { StudentOptionDTO } from "../StudentOptionDTO.ts";

/**
 * @description Listagem dos alunos para opções e dropdown
 */
export type GetStudentOptions200 = StudentOptionDTO[];

/**
 * @description Requisição inválida
 */
export type GetStudentOptions400 = ProblemDetailResponseDTO;

export type GetStudentOptionsQueryResponse = GetStudentOptions200;

export type GetStudentOptionsQuery = {
  Response: GetStudentOptions200;
  Errors: GetStudentOptions400;
};
