/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

export type UnarchiveStudentPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno desarquivado com sucesso
 */
export type UnarchiveStudent204 = any;

/**
 * @description Requisição inválida
 */
export type UnarchiveStudent400 = ProblemDetailResponseDTO;

export type UnarchiveStudentMutationResponse = UnarchiveStudent204;

export type UnarchiveStudentMutation = {
  Response: UnarchiveStudent204;
  PathParams: UnarchiveStudentPathParams;
  Errors: UnarchiveStudent400;
};
