/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StudentResponseDTO } from "../StudentResponseDTO.ts";
import type { StudentUpdateDTO } from "../StudentUpdateDTO.ts";

export type UpdateStudentPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno atualizado com sucesso.
 */
export type UpdateStudent200 = StudentResponseDTO;

export type UpdateStudentMutationRequest = StudentUpdateDTO;

export type UpdateStudentMutationResponse = UpdateStudent200;

export type UpdateStudentMutation = {
  Response: UpdateStudent200;
  Request: UpdateStudentMutationRequest;
  PathParams: UpdateStudentPathParams;
  Errors: any;
};
