/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StudentRequestDTO } from "../StudentRequestDTO.ts";

export type UpdateStudentPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

/**
 * @description Aluno atualizado com sucesso.
 */
export type UpdateStudent204 = any;

export type UpdateStudentMutationRequest = StudentRequestDTO;

export type UpdateStudentMutationResponse = UpdateStudent204;

export type UpdateStudentMutation = {
  Response: UpdateStudent204;
  Request: UpdateStudentMutationRequest;
  PathParams: UpdateStudentPathParams;
  Errors: any;
};
