/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const archiveParentPathParamsSchema = z.object({
  parentId: z.uuid(),
});

/**
 * @description Responsável arquivado com sucesso
 */
export const archiveParent204Schema = z.any();

export const archiveParentMutationResponseSchema = z.lazy(
  () => archiveParent204Schema,
);
