/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { parentRequestDTOSchema } from "../parentRequestDTOSchema.ts";
import { parentResponseDTOSchema } from "../parentResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Responsável criado com sucesso
 */
export const createParent204Schema = z
  .lazy(() => parentResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

export const createParentMutationRequestSchema = z
  .lazy(() => parentRequestDTOSchema)
  .describe("Formato de payload para criar um novo responsável");

export const createParentMutationResponseSchema = z.lazy(
  () => createParent204Schema,
);
