/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const deleteParentPathParamsSchema = z.object({
  parentId: z.uuid(),
});

/**
 * @description Responsável deletado com sucesso
 */
export const deleteParent204Schema = z.any();

export const deleteParentMutationResponseSchema = z.lazy(
  () => deleteParent204Schema,
);
