/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { parentResponseDTOSchema } from "../parentResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getParentByIdPathParamsSchema = z.object({
  parentId: z.uuid(),
});

/**
 * @description Responsável retornado com sucesso
 */
export const getParentById200Schema = z
  .lazy(() => parentResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

export const getParentByIdQueryResponseSchema = z.lazy(
  () => getParentById200Schema,
);
