/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageDTOParentResponseDTOSchema } from "../pageDTOParentResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getParentsQueryParamsSchema = z.object({
  page: z.coerce
    .number()
    .int()
    .min(0)
    .default(0)
    .describe("Zero-based page index (0..N)"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(20)
    .describe("The size of the page to be returned"),
  sort: z.optional(
    z
      .array(z.string())
      .describe(
        "Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
      ),
  ),
  search: z.optional(z.string()),
  archived: z.optional(z.boolean()),
});

/**
 * @description Lista de responsáveis retornada com sucesso.
 */
export const getParents200Schema = z.lazy(() => pageDTOParentResponseDTOSchema);

export const getParentsQueryResponseSchema = z.lazy(() => getParents200Schema);
