/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { parentRequestDTOSchema } from "../parentRequestDTOSchema.ts";
import { parentResponseDTOSchema } from "../parentResponseDTOSchema.ts";
import { z } from "zod/v4";

export const updateParentPathParamsSchema = z.object({
  parentId: z.uuid(),
});

/**
 * @description Responsável atualizado com sucesso
 */
export const updateParent200Schema = z
  .lazy(() => parentResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

export const updateParentMutationRequestSchema = z
  .lazy(() => parentRequestDTOSchema)
  .describe("Formato de payload para criar um novo responsável");

export const updateParentMutationResponseSchema = z.lazy(
  () => updateParent200Schema,
);
