/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CreateDespesaMutationRequest,
  CreateDespesaMutationResponse,
  CreateDespesa400,
  CreateDespesa409,
  CreateDespesa500,
} from "../../types/financeiro/CreateDespesa.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createDespesaMutationKey = () =>
  [{ url: "/v1/despesas" }] as const;

export type CreateDespesaMutationKey = ReturnType<
  typeof createDespesaMutationKey
>;

/**
 * @summary Cria uma nova despesa geral
 * {@link /v1/despesas}
 */
export async function createDespesa(
  data: CreateDespesaMutationRequest,
  config: Partial<RequestConfig<CreateDespesaMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateDespesaMutationResponse,
    ResponseErrorConfig<CreateDespesa400 | CreateDespesa409 | CreateDespesa500>,
    CreateDespesaMutationRequest
  >({
    method: "POST",
    url: `/v1/despesas`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createDespesaMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateDespesaMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createDespesaMutationKey();
  return mutationOptions<
    CreateDespesaMutationResponse,
    ResponseErrorConfig<CreateDespesa400 | CreateDespesa409 | CreateDespesa500>,
    { data: CreateDespesaMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createDespesa(data, config);
    },
  });
}

/**
 * @summary Cria uma nova despesa geral
 * {@link /v1/despesas}
 */
export function useCreateDespesa<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateDespesaMutationResponse,
      ResponseErrorConfig<
        CreateDespesa400 | CreateDespesa409 | CreateDespesa500
      >,
      { data: CreateDespesaMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateDespesaMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createDespesaMutationKey();

  const baseOptions = createDespesaMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateDespesaMutationResponse,
    ResponseErrorConfig<CreateDespesa400 | CreateDespesa409 | CreateDespesa500>,
    { data: CreateDespesaMutationRequest },
    TContext
  >;

  return useMutation<
    CreateDespesaMutationResponse,
    ResponseErrorConfig<CreateDespesa400 | CreateDespesa409 | CreateDespesa500>,
    { data: CreateDespesaMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateDespesaMutationResponse,
    ResponseErrorConfig<CreateDespesa400 | CreateDespesa409 | CreateDespesa500>,
    { data: CreateDespesaMutationRequest },
    TContext
  >;
}
