/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetDespesaByIdQueryResponse,
  GetDespesaByIdPathParams,
  GetDespesaById404,
  GetDespesaById500,
} from "../../types/financeiro/GetDespesaById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDespesaByIdQueryKey = (
  id: GetDespesaByIdPathParams["id"] | undefined,
) => [{ url: "/v1/despesas/:id", params: { id: id } }] as const;

export type GetDespesaByIdQueryKey = ReturnType<typeof getDespesaByIdQueryKey>;

/**
 * @summary Busca uma despesa geral pelo ID
 * {@link /v1/despesas/:id}
 */
export async function getDespesaById(
  id: GetDespesaByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDespesaByIdQueryResponse,
    ResponseErrorConfig<GetDespesaById404 | GetDespesaById500>,
    unknown
  >({ method: "GET", url: `/v1/despesas/${id}`, ...requestConfig });
  return res.data;
}

export function getDespesaByIdQueryOptions(
  id: GetDespesaByIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDespesaByIdQueryKey(id);
  return queryOptions<
    GetDespesaByIdQueryResponse,
    ResponseErrorConfig<GetDespesaById404 | GetDespesaById500>,
    GetDespesaByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getDespesaById(id!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Busca uma despesa geral pelo ID
 * {@link /v1/despesas/:id}
 */
export function useGetDespesaById<
  TData = GetDespesaByIdQueryResponse,
  TQueryData = GetDespesaByIdQueryResponse,
  TQueryKey extends QueryKey = GetDespesaByIdQueryKey,
>(
  id: GetDespesaByIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDespesaByIdQueryResponse,
        ResponseErrorConfig<GetDespesaById404 | GetDespesaById500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getDespesaByIdQueryKey(id);

  const query = useQuery(
    {
      ...getDespesaByIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetDespesaById404 | GetDespesaById500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
