/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ToggleDespesaPaymentMutationResponse,
  ToggleDespesaPaymentPathParams,
  ToggleDespesaPayment404,
  ToggleDespesaPayment500,
} from "../../types/financeiro/ToggleDespesaPayment.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const toggleDespesaPaymentMutationKey = () =>
  [{ url: "/v1/despesas/:id/toggle-pagamento" }] as const;

export type ToggleDespesaPaymentMutationKey = ReturnType<
  typeof toggleDespesaPaymentMutationKey
>;

/**
 * @summary Alterna o pagamento de uma despesa geral
 * {@link /v1/despesas/:id/toggle-pagamento}
 */
export async function toggleDespesaPayment(
  id: ToggleDespesaPaymentPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ToggleDespesaPaymentMutationResponse,
    ResponseErrorConfig<ToggleDespesaPayment404 | ToggleDespesaPayment500>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/despesas/${id}/toggle-pagamento`,
    ...requestConfig,
  });
  return res.data;
}

export function toggleDespesaPaymentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = toggleDespesaPaymentMutationKey();
  return mutationOptions<
    ToggleDespesaPaymentMutationResponse,
    ResponseErrorConfig<ToggleDespesaPayment404 | ToggleDespesaPayment500>,
    { id: ToggleDespesaPaymentPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return toggleDespesaPayment(id, config);
    },
  });
}

/**
 * @summary Alterna o pagamento de uma despesa geral
 * {@link /v1/despesas/:id/toggle-pagamento}
 */
export function useToggleDespesaPayment<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ToggleDespesaPaymentMutationResponse,
      ResponseErrorConfig<ToggleDespesaPayment404 | ToggleDespesaPayment500>,
      { id: ToggleDespesaPaymentPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? toggleDespesaPaymentMutationKey();

  const baseOptions = toggleDespesaPaymentMutationOptions(
    config,
  ) as UseMutationOptions<
    ToggleDespesaPaymentMutationResponse,
    ResponseErrorConfig<ToggleDespesaPayment404 | ToggleDespesaPayment500>,
    { id: ToggleDespesaPaymentPathParams["id"] },
    TContext
  >;

  return useMutation<
    ToggleDespesaPaymentMutationResponse,
    ResponseErrorConfig<ToggleDespesaPayment404 | ToggleDespesaPayment500>,
    { id: ToggleDespesaPaymentPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ToggleDespesaPaymentMutationResponse,
    ResponseErrorConfig<ToggleDespesaPayment404 | ToggleDespesaPayment500>,
    { id: ToggleDespesaPaymentPathParams["id"] },
    TContext
  >;
}
