/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UpdateDespesaMutationRequest,
  UpdateDespesaMutationResponse,
  UpdateDespesaPathParams,
  UpdateDespesa400,
  UpdateDespesa404,
  UpdateDespesa409,
  UpdateDespesa500,
} from "../../types/financeiro/UpdateDespesa.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateDespesaMutationKey = () =>
  [{ url: "/v1/despesas/:id" }] as const;

export type UpdateDespesaMutationKey = ReturnType<
  typeof updateDespesaMutationKey
>;

/**
 * @summary Atualiza uma despesa geral
 * {@link /v1/despesas/:id}
 */
export async function updateDespesa(
  id: UpdateDespesaPathParams["id"],
  data: UpdateDespesaMutationRequest,
  config: Partial<RequestConfig<UpdateDespesaMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateDespesaMutationResponse,
    ResponseErrorConfig<
      UpdateDespesa400 | UpdateDespesa404 | UpdateDespesa409 | UpdateDespesa500
    >,
    UpdateDespesaMutationRequest
  >({
    method: "PUT",
    url: `/v1/despesas/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateDespesaMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateDespesaMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updateDespesaMutationKey();
  return mutationOptions<
    UpdateDespesaMutationResponse,
    ResponseErrorConfig<
      UpdateDespesa400 | UpdateDespesa404 | UpdateDespesa409 | UpdateDespesa500
    >,
    { id: UpdateDespesaPathParams["id"]; data: UpdateDespesaMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return updateDespesa(id, data, config);
    },
  });
}

/**
 * @summary Atualiza uma despesa geral
 * {@link /v1/despesas/:id}
 */
export function useUpdateDespesa<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateDespesaMutationResponse,
      ResponseErrorConfig<
        | UpdateDespesa400
        | UpdateDespesa404
        | UpdateDespesa409
        | UpdateDespesa500
      >,
      { id: UpdateDespesaPathParams["id"]; data: UpdateDespesaMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateDespesaMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateDespesaMutationKey();

  const baseOptions = updateDespesaMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateDespesaMutationResponse,
    ResponseErrorConfig<
      UpdateDespesa400 | UpdateDespesa404 | UpdateDespesa409 | UpdateDespesa500
    >,
    { id: UpdateDespesaPathParams["id"]; data: UpdateDespesaMutationRequest },
    TContext
  >;

  return useMutation<
    UpdateDespesaMutationResponse,
    ResponseErrorConfig<
      UpdateDespesa400 | UpdateDespesa404 | UpdateDespesa409 | UpdateDespesa500
    >,
    { id: UpdateDespesaPathParams["id"]; data: UpdateDespesaMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateDespesaMutationResponse,
    ResponseErrorConfig<
      UpdateDespesa400 | UpdateDespesa404 | UpdateDespesa409 | UpdateDespesa500
    >,
    { id: UpdateDespesaPathParams["id"]; data: UpdateDespesaMutationRequest },
    TContext
  >;
}
