/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StudentResponseDTO } from "../StudentResponseDTO.ts";

export type GetStudentsByParentPathParams = {
  /**
   * @type string, uuid
   */
  parentId: string;
};

/**
 * @description Lista de alunos retornada com sucesso.
 */
export type GetStudentsByParent200 = StudentResponseDTO[];

export type GetStudentsByParentQueryResponse = GetStudentsByParent200;

export type GetStudentsByParentQuery = {
  Response: GetStudentsByParent200;
  PathParams: GetStudentsByParentPathParams;
  Errors: any;
};
