/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StudentSummaryDTO } from "../StudentSummaryDTO.ts";

/**
 * @description Lista de opções de alunos retornada com sucesso.
 */
export type GetStudentSummary200 = StudentSummaryDTO[];

export type GetStudentSummaryQueryResponse = GetStudentSummary200;

export type GetStudentSummaryQuery = {
  Response: GetStudentSummary200;
  Errors: any;
};
