/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StudentSummaryDTO } from "../StudentSummaryDTO.ts";

/**
 * @description Lista de opções de alunos retornada com sucesso.
 */
export type GetStudentOptions200 = StudentSummaryDTO[];

export type GetStudentOptionsQueryResponse = GetStudentOptions200;

export type GetStudentOptionsQuery = {
  Response: GetStudentOptions200;
  Errors: any;
};
