/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ArquivarResponsavelMutationResponse,
  ArquivarResponsavelPathParams,
  ArquivarResponsavel404,
  ArquivarResponsavel409,
  ArquivarResponsavel500,
} from "../../types/responsavel/ArquivarResponsavel.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const arquivarResponsavelMutationKey = () =>
  [{ url: "/v1/responsaveis/:responsavelId/archive" }] as const;

export type ArquivarResponsavelMutationKey = ReturnType<
  typeof arquivarResponsavelMutationKey
>;

/**
 * @description Arquiva um responsável por ID
 * {@link /v1/responsaveis/:responsavelId/archive}
 */
export async function arquivarResponsavel(
  responsavelId: ArquivarResponsavelPathParams["responsavelId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ArquivarResponsavelMutationResponse,
    ResponseErrorConfig<
      ArquivarResponsavel404 | ArquivarResponsavel409 | ArquivarResponsavel500
    >,
    unknown
  >({
    method: "PATCH",
    url: `/v1/responsaveis/${responsavelId}/archive`,
    ...requestConfig,
  });
  return res.data;
}

export function arquivarResponsavelMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = arquivarResponsavelMutationKey();
  return mutationOptions<
    ArquivarResponsavelMutationResponse,
    ResponseErrorConfig<
      ArquivarResponsavel404 | ArquivarResponsavel409 | ArquivarResponsavel500
    >,
    { responsavelId: ArquivarResponsavelPathParams["responsavelId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ responsavelId }) => {
      return arquivarResponsavel(responsavelId, config);
    },
  });
}

/**
 * @description Arquiva um responsável por ID
 * {@link /v1/responsaveis/:responsavelId/archive}
 */
export function useArquivarResponsavel<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ArquivarResponsavelMutationResponse,
      ResponseErrorConfig<
        ArquivarResponsavel404 | ArquivarResponsavel409 | ArquivarResponsavel500
      >,
      { responsavelId: ArquivarResponsavelPathParams["responsavelId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? arquivarResponsavelMutationKey();

  const baseOptions = arquivarResponsavelMutationOptions(
    config,
  ) as UseMutationOptions<
    ArquivarResponsavelMutationResponse,
    ResponseErrorConfig<
      ArquivarResponsavel404 | ArquivarResponsavel409 | ArquivarResponsavel500
    >,
    { responsavelId: ArquivarResponsavelPathParams["responsavelId"] },
    TContext
  >;

  return useMutation<
    ArquivarResponsavelMutationResponse,
    ResponseErrorConfig<
      ArquivarResponsavel404 | ArquivarResponsavel409 | ArquivarResponsavel500
    >,
    { responsavelId: ArquivarResponsavelPathParams["responsavelId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ArquivarResponsavelMutationResponse,
    ResponseErrorConfig<
      ArquivarResponsavel404 | ArquivarResponsavel409 | ArquivarResponsavel500
    >,
    { responsavelId: ArquivarResponsavelPathParams["responsavelId"] },
    TContext
  >;
}
