/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type {
  CreateResponsavelMutationRequest,
  CreateResponsavelMutationResponse,
} from "../../types/CreateResponsavel.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createResponsavelMutationKey = () =>
  [{ url: "/v1/responsaveis" }] as const;

export type CreateResponsavelMutationKey = ReturnType<
  typeof createResponsavelMutationKey
>;

/**
 * @description Cria um novo responsável
 * {@link /v1/responsaveis}
 */
export async function createResponsavel(
  data: CreateResponsavelMutationRequest,
  config: Partial<RequestConfig<CreateResponsavelMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateResponsavelMutationResponse,
    ResponseErrorConfig<Error>,
    CreateResponsavelMutationRequest
  >({
    method: "POST",
    url: `/v1/responsaveis`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createResponsavelMutationOptions(
  config: Partial<RequestConfig<CreateResponsavelMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = createResponsavelMutationKey();
  return mutationOptions<
    CreateResponsavelMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateResponsavelMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createResponsavel(data, config);
    },
  });
}

/**
 * @description Cria um novo responsável
 * {@link /v1/responsaveis}
 */
export function useCreateResponsavel<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateResponsavelMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CreateResponsavelMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateResponsavelMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createResponsavelMutationKey();

  const baseOptions = createResponsavelMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateResponsavelMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateResponsavelMutationRequest },
    TContext
  >;

  return useMutation<
    CreateResponsavelMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateResponsavelMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateResponsavelMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateResponsavelMutationRequest },
    TContext
  >;
}
