/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeletarResponsavelMutationResponse,
  DeletarResponsavelPathParams,
  DeletarResponsavel404,
  DeletarResponsavel409,
  DeletarResponsavel500,
} from "../../types/responsavel/DeletarResponsavel.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deletarResponsavelMutationKey = () =>
  [{ url: "/v1/responsaveis/:responsavelId" }] as const;

export type DeletarResponsavelMutationKey = ReturnType<
  typeof deletarResponsavelMutationKey
>;

/**
 * @description Deleta um responsável por ID
 * {@link /v1/responsaveis/:responsavelId}
 */
export async function deletarResponsavel(
  responsavelId: DeletarResponsavelPathParams["responsavelId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeletarResponsavelMutationResponse,
    ResponseErrorConfig<
      DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/v1/responsaveis/${responsavelId}`,
    ...requestConfig,
  });
  return res.data;
}

export function deletarResponsavelMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deletarResponsavelMutationKey();
  return mutationOptions<
    DeletarResponsavelMutationResponse,
    ResponseErrorConfig<
      DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500
    >,
    { responsavelId: DeletarResponsavelPathParams["responsavelId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ responsavelId }) => {
      return deletarResponsavel(responsavelId, config);
    },
  });
}

/**
 * @description Deleta um responsável por ID
 * {@link /v1/responsaveis/:responsavelId}
 */
export function useDeletarResponsavel<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeletarResponsavelMutationResponse,
      ResponseErrorConfig<
        DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500
      >,
      { responsavelId: DeletarResponsavelPathParams["responsavelId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deletarResponsavelMutationKey();

  const baseOptions = deletarResponsavelMutationOptions(
    config,
  ) as UseMutationOptions<
    DeletarResponsavelMutationResponse,
    ResponseErrorConfig<
      DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500
    >,
    { responsavelId: DeletarResponsavelPathParams["responsavelId"] },
    TContext
  >;

  return useMutation<
    DeletarResponsavelMutationResponse,
    ResponseErrorConfig<
      DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500
    >,
    { responsavelId: DeletarResponsavelPathParams["responsavelId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeletarResponsavelMutationResponse,
    ResponseErrorConfig<
      DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500
    >,
    { responsavelId: DeletarResponsavelPathParams["responsavelId"] },
    TContext
  >;
}
