/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetResponsavelByIdQueryResponse,
  GetResponsavelByIdPathParams,
} from "../../types/responsavel/GetResponsavelById.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getResponsavelByIdQueryKey = (
  responsavelId: GetResponsavelByIdPathParams["responsavelId"],
) =>
  [
    {
      url: "/v1/responsaveis/:responsavelId",
      params: { responsavelId: responsavelId },
    },
  ] as const;

export type GetResponsavelByIdQueryKey = ReturnType<
  typeof getResponsavelByIdQueryKey
>;

/**
 * @description Retorna um responsável por ID
 * {@link /v1/responsaveis/:responsavelId}
 */
export async function getResponsavelById(
  responsavelId: GetResponsavelByIdPathParams["responsavelId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetResponsavelByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/responsaveis/${responsavelId}`,
    ...requestConfig,
  });
  return res.data;
}

export function getResponsavelByIdQueryOptions(
  responsavelId: GetResponsavelByIdPathParams["responsavelId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getResponsavelByIdQueryKey(responsavelId);
  return queryOptions<
    GetResponsavelByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetResponsavelByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!responsavelId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getResponsavelById(responsavelId, config);
    },
  });
}

/**
 * @description Retorna um responsável por ID
 * {@link /v1/responsaveis/:responsavelId}
 */
export function useGetResponsavelById<
  TData = GetResponsavelByIdQueryResponse,
  TQueryData = GetResponsavelByIdQueryResponse,
  TQueryKey extends QueryKey = GetResponsavelByIdQueryKey,
>(
  responsavelId: GetResponsavelByIdPathParams["responsavelId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetResponsavelByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getResponsavelByIdQueryKey(responsavelId);

  const query = useQuery(
    {
      ...getResponsavelByIdQueryOptions(responsavelId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
