/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetResponsaveisQueryResponse,
  GetResponsaveisQueryParams,
} from "../../types/responsavel/GetResponsaveis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getResponsaveisQueryKey = (params?: GetResponsaveisQueryParams) =>
  [{ url: "/v1/responsaveis" }, ...(params ? [params] : [])] as const;

export type GetResponsaveisQueryKey = ReturnType<
  typeof getResponsaveisQueryKey
>;

/**
 * @description Retorna uma lista de responsáveis paginada
 * {@link /v1/responsaveis}
 */
export async function getResponsaveis(
  params?: GetResponsaveisQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetResponsaveisQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/responsaveis`, params, ...requestConfig });
  return res.data;
}

export function getResponsaveisQueryOptions(
  params?: GetResponsaveisQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getResponsaveisQueryKey(params);
  return queryOptions<
    GetResponsaveisQueryResponse,
    ResponseErrorConfig<Error>,
    GetResponsaveisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getResponsaveis(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna uma lista de responsáveis paginada
 * {@link /v1/responsaveis}
 */
export function useGetResponsaveis<
  TData = GetResponsaveisQueryResponse,
  TQueryData = GetResponsaveisQueryResponse,
  TQueryKey extends QueryKey = GetResponsaveisQueryKey,
>(
  params?: GetResponsaveisQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetResponsaveisQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getResponsaveisQueryKey(params);

  const query = useQuery(
    {
      ...getResponsaveisQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
