/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ListResponsaveisQueryResponse,
  ListResponsaveis500,
} from "../../types/responsavel/ListResponsaveis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listResponsaveisQueryKey = () =>
  [{ url: "/v1/responsaveis/options" }] as const;

export type ListResponsaveisQueryKey = ReturnType<
  typeof listResponsaveisQueryKey
>;

/**
 * @description Retorna uma lista de responsáveis para dropdown
 * {@link /v1/responsaveis/options}
 */
export async function listResponsaveis(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListResponsaveisQueryResponse,
    ResponseErrorConfig<ListResponsaveis500>,
    unknown
  >({ method: "GET", url: `/v1/responsaveis/options`, ...requestConfig });
  return res.data;
}

export function listResponsaveisQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listResponsaveisQueryKey();
  return queryOptions<
    ListResponsaveisQueryResponse,
    ResponseErrorConfig<ListResponsaveis500>,
    ListResponsaveisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listResponsaveis({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Retorna uma lista de responsáveis para dropdown
 * {@link /v1/responsaveis/options}
 */
export function useListResponsaveis<
  TData = ListResponsaveisQueryResponse,
  TQueryData = ListResponsaveisQueryResponse,
  TQueryKey extends QueryKey = ListResponsaveisQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListResponsaveisQueryResponse,
        ResponseErrorConfig<ListResponsaveis500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? listResponsaveisQueryKey();

  const query = useQuery(
    {
      ...listResponsaveisQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<ListResponsaveis500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
