/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UpdateResponsavelMutationRequest,
  UpdateResponsavelMutationResponse,
  UpdateResponsavelPathParams,
  UpdateResponsavel400,
  UpdateResponsavel404,
  UpdateResponsavel409,
  UpdateResponsavel500,
} from "../../types/responsavel/UpdateResponsavel.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateResponsavelMutationKey = () =>
  [{ url: "/v1/responsaveis/:responsavelId" }] as const;

export type UpdateResponsavelMutationKey = ReturnType<
  typeof updateResponsavelMutationKey
>;

/**
 * @description Atualiza um responsável por ID
 * {@link /v1/responsaveis/:responsavelId}
 */
export async function updateResponsavel(
  responsavelId: UpdateResponsavelPathParams["responsavelId"],
  data: UpdateResponsavelMutationRequest,
  config: Partial<RequestConfig<UpdateResponsavelMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateResponsavelMutationResponse,
    ResponseErrorConfig<
      | UpdateResponsavel400
      | UpdateResponsavel404
      | UpdateResponsavel409
      | UpdateResponsavel500
    >,
    UpdateResponsavelMutationRequest
  >({
    method: "PATCH",
    url: `/v1/responsaveis/${responsavelId}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateResponsavelMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateResponsavelMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updateResponsavelMutationKey();
  return mutationOptions<
    UpdateResponsavelMutationResponse,
    ResponseErrorConfig<
      | UpdateResponsavel400
      | UpdateResponsavel404
      | UpdateResponsavel409
      | UpdateResponsavel500
    >,
    {
      responsavelId: UpdateResponsavelPathParams["responsavelId"];
      data: UpdateResponsavelMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ responsavelId, data }) => {
      return updateResponsavel(responsavelId, data, config);
    },
  });
}

/**
 * @description Atualiza um responsável por ID
 * {@link /v1/responsaveis/:responsavelId}
 */
export function useUpdateResponsavel<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateResponsavelMutationResponse,
      ResponseErrorConfig<
        | UpdateResponsavel400
        | UpdateResponsavel404
        | UpdateResponsavel409
        | UpdateResponsavel500
      >,
      {
        responsavelId: UpdateResponsavelPathParams["responsavelId"];
        data: UpdateResponsavelMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateResponsavelMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateResponsavelMutationKey();

  const baseOptions = updateResponsavelMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateResponsavelMutationResponse,
    ResponseErrorConfig<
      | UpdateResponsavel400
      | UpdateResponsavel404
      | UpdateResponsavel409
      | UpdateResponsavel500
    >,
    {
      responsavelId: UpdateResponsavelPathParams["responsavelId"];
      data: UpdateResponsavelMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdateResponsavelMutationResponse,
    ResponseErrorConfig<
      | UpdateResponsavel400
      | UpdateResponsavel404
      | UpdateResponsavel409
      | UpdateResponsavel500
    >,
    {
      responsavelId: UpdateResponsavelPathParams["responsavelId"];
      data: UpdateResponsavelMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateResponsavelMutationResponse,
    ResponseErrorConfig<
      | UpdateResponsavel400
      | UpdateResponsavel404
      | UpdateResponsavel409
      | UpdateResponsavel500
    >,
    {
      responsavelId: UpdateResponsavelPathParams["responsavelId"];
      data: UpdateResponsavelMutationRequest;
    },
    TContext
  >;
}
