/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EventResponseDTO } from "../EventResponseDTO.ts";

export type GetEventByIdPathParams = {
  /**
   * @type string, uuid
   */
  eventId: string;
};

/**
 * @description Evento retornado com sucessso.
 */
export type GetEventById200 = EventResponseDTO;

export type GetEventByIdQueryResponse = GetEventById200;

export type GetEventByIdQuery = {
  Response: GetEventById200;
  PathParams: GetEventByIdPathParams;
  Errors: any;
};
