/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageDTOEventResponseDTO } from "../PageDTOEventResponseDTO.ts";

export type GetEventsQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type string | undefined
   */
  search?: string;
  /**
   * @type boolean | undefined
   */
  archived?: boolean;
};

/**
 * @description Lista de eventos retornada com sucesso.
 */
export type GetEvents200 = PageDTOEventResponseDTO;

export type GetEventsQueryResponse = GetEvents200;

export type GetEventsQuery = {
  Response: GetEvents200;
  QueryParams: GetEventsQueryParams;
  Errors: any;
};
