/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageDTOEventResponseDTO } from "../PageDTOEventResponseDTO.ts";

export type GetEventsByStudentPathParams = {
  /**
   * @type string, uuid
   */
  studentId: string;
};

export type GetEventsByStudentQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
};

/**
 * @description Lista de eventos do aluno retornada com sucesso.
 */
export type GetEventsByStudent200 = PageDTOEventResponseDTO;

export type GetEventsByStudentQueryResponse = GetEventsByStudent200;

export type GetEventsByStudentQuery = {
  Response: GetEventsByStudent200;
  PathParams: GetEventsByStudentPathParams;
  QueryParams: GetEventsByStudentQueryParams;
  Errors: any;
};
