/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateColaboradorMutationRequest, CreateColaboradorMutationResponse } from "../../types/colaborador/CreateColaborador.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createColaboradorMutationKey = () => [{ url: '/v1/colaboradores' }] as const

export type CreateColaboradorMutationKey = ReturnType<typeof createColaboradorMutationKey>

/**
 * @description Cria um novo colaborador com os dados fornecidos.
 * {@link /v1/colaboradores}
 */
export async function createColaborador(data: CreateColaboradorMutationRequest, config: Partial<RequestConfig<CreateColaboradorMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateColaboradorMutationResponse, ResponseErrorConfig<Error>, CreateColaboradorMutationRequest>({ method : "POST", url : `/v1/colaboradores`, data : requestData, ... requestConfig })  
  return res.data
}

export function createColaboradorMutationOptions(config: Partial<RequestConfig<CreateColaboradorMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createColaboradorMutationKey()
  return mutationOptions<CreateColaboradorMutationResponse, ResponseErrorConfig<Error>, {data: CreateColaboradorMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createColaborador(data, config)
    },
  })
}

/**
 * @description Cria um novo colaborador com os dados fornecidos.
 * {@link /v1/colaboradores}
 */
export function useCreateColaborador<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateColaboradorMutationResponse, ResponseErrorConfig<Error>, {data: CreateColaboradorMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateColaboradorMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createColaboradorMutationKey()

  const baseOptions = createColaboradorMutationOptions(config) as UseMutationOptions<CreateColaboradorMutationResponse, ResponseErrorConfig<Error>, {data: CreateColaboradorMutationRequest}, TContext>

  return useMutation<CreateColaboradorMutationResponse, ResponseErrorConfig<Error>, {data: CreateColaboradorMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateColaboradorMutationResponse, ResponseErrorConfig<Error>, {data: CreateColaboradorMutationRequest}, TContext>
}