/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetColaboradoresKpisQueryResponse,
  GetColaboradoresKpis400,
  GetColaboradoresKpis500,
} from "../../types/colaborador/GetColaboradoresKpis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getColaboradoresKpisQueryKey = () =>
  [{ url: "/v1/colaboradores/kpis" }] as const;

export type GetColaboradoresKpisQueryKey = ReturnType<
  typeof getColaboradoresKpisQueryKey
>;

/**
 * @description Retorna os KPIs de colaboradores.
 * {@link /v1/colaboradores/kpis}
 */
export async function getColaboradoresKpis(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetColaboradoresKpisQueryResponse,
    ResponseErrorConfig<GetColaboradoresKpis400 | GetColaboradoresKpis500>,
    unknown
  >({ method: "GET", url: `/v1/colaboradores/kpis`, ...requestConfig });
  return res.data;
}

export function getColaboradoresKpisQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getColaboradoresKpisQueryKey();
  return queryOptions<
    GetColaboradoresKpisQueryResponse,
    ResponseErrorConfig<GetColaboradoresKpis400 | GetColaboradoresKpis500>,
    GetColaboradoresKpisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getColaboradoresKpis({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna os KPIs de colaboradores.
 * {@link /v1/colaboradores/kpis}
 */
export function useGetColaboradoresKpis<
  TData = GetColaboradoresKpisQueryResponse,
  TQueryData = GetColaboradoresKpisQueryResponse,
  TQueryKey extends QueryKey = GetColaboradoresKpisQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetColaboradoresKpisQueryResponse,
        ResponseErrorConfig<GetColaboradoresKpis400 | GetColaboradoresKpis500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getColaboradoresKpisQueryKey();

  const query = useQuery(
    {
      ...getColaboradoresKpisQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetColaboradoresKpis400 | GetColaboradoresKpis500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
