/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetColaboradoresListQueryResponse } from "../../types/colaborador/GetColaboradoresList.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getColaboradoresListQueryKey = () =>
  [{ url: "/v1/colaboradores/list" }] as const;

export type GetColaboradoresListQueryKey = ReturnType<
  typeof getColaboradoresListQueryKey
>;

/**
 * @description Retorna uma lista de opções de colaboradores para dropdown.
 * {@link /v1/colaboradores/list}
 */
export async function getColaboradoresList(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetColaboradoresListQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/colaboradores/list`, ...requestConfig });
  return res.data;
}

export function getColaboradoresListQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getColaboradoresListQueryKey();
  return queryOptions<
    GetColaboradoresListQueryResponse,
    ResponseErrorConfig<Error>,
    GetColaboradoresListQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getColaboradoresList(config);
    },
  });
}

/**
 * @description Retorna uma lista de opções de colaboradores para dropdown.
 * {@link /v1/colaboradores/list}
 */
export function useGetColaboradoresList<
  TData = GetColaboradoresListQueryResponse,
  TQueryData = GetColaboradoresListQueryResponse,
  TQueryKey extends QueryKey = GetColaboradoresListQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetColaboradoresListQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getColaboradoresListQueryKey();

  const query = useQuery(
    {
      ...getColaboradoresListQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
