/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type { GetColaboradoresKpisQueryResponse } from "../../types/GetColaboradoresKpis.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getColaboradoresKpisQueryKey = () =>
  [{ url: "/v1/colaboradores/kpis" }] as const;

export type GetColaboradoresKpisQueryKey = ReturnType<
  typeof getColaboradoresKpisQueryKey
>;

/**
 * @description Retorna os KPIs de colaboradores.
 * {@link /v1/colaboradores/kpis}
 */
export async function getColaboradoresKpis(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetColaboradoresKpisQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/colaboradores/kpis`, ...requestConfig });
  return res.data;
}

export function getColaboradoresKpisQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getColaboradoresKpisQueryKey();
  return queryOptions<
    GetColaboradoresKpisQueryResponse,
    ResponseErrorConfig<Error>,
    GetColaboradoresKpisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getColaboradoresKpis(config);
    },
  });
}

/**
 * @description Retorna os KPIs de colaboradores.
 * {@link /v1/colaboradores/kpis}
 */
export function useGetColaboradoresKpis<
  TData = GetColaboradoresKpisQueryResponse,
  TQueryData = GetColaboradoresKpisQueryResponse,
  TQueryKey extends QueryKey = GetColaboradoresKpisQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetColaboradoresKpisQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getColaboradoresKpisQueryKey();

  const query = useQuery(
    {
      ...getColaboradoresKpisQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
