/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UpdateColaboradorMutationRequest, UpdateColaboradorMutationResponse, UpdateColaboradorPathParams } from "../../types/colaborador/UpdateColaborador.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateColaboradorMutationKey = () => [{ url: '/v1/colaboradores/:colaboradorId' }] as const

export type UpdateColaboradorMutationKey = ReturnType<typeof updateColaboradorMutationKey>

/**
 * @description Atualiza um colaborador por ID.
 * {@link /v1/colaboradores/:colaboradorId}
 */
export async function updateColaborador(colaboradorId: UpdateColaboradorPathParams["colaboradorId"], data: UpdateColaboradorMutationRequest, config: Partial<RequestConfig<UpdateColaboradorMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateColaboradorMutationResponse, ResponseErrorConfig<Error>, UpdateColaboradorMutationRequest>({ method : "PATCH", url : `/v1/colaboradores/${colaboradorId}`, data : requestData, ... requestConfig })  
  return res.data
}

export function updateColaboradorMutationOptions(config: Partial<RequestConfig<UpdateColaboradorMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateColaboradorMutationKey()
  return mutationOptions<UpdateColaboradorMutationResponse, ResponseErrorConfig<Error>, {colaboradorId: UpdateColaboradorPathParams["colaboradorId"], data: UpdateColaboradorMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ colaboradorId, data }) => {
      return updateColaborador(colaboradorId, data, config)
    },
  })
}

/**
 * @description Atualiza um colaborador por ID.
 * {@link /v1/colaboradores/:colaboradorId}
 */
export function useUpdateColaborador<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateColaboradorMutationResponse, ResponseErrorConfig<Error>, {colaboradorId: UpdateColaboradorPathParams["colaboradorId"], data: UpdateColaboradorMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateColaboradorMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateColaboradorMutationKey()

  const baseOptions = updateColaboradorMutationOptions(config) as UseMutationOptions<UpdateColaboradorMutationResponse, ResponseErrorConfig<Error>, {colaboradorId: UpdateColaboradorPathParams["colaboradorId"], data: UpdateColaboradorMutationRequest}, TContext>

  return useMutation<UpdateColaboradorMutationResponse, ResponseErrorConfig<Error>, {colaboradorId: UpdateColaboradorPathParams["colaboradorId"], data: UpdateColaboradorMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateColaboradorMutationResponse, ResponseErrorConfig<Error>, {colaboradorId: UpdateColaboradorPathParams["colaboradorId"], data: UpdateColaboradorMutationRequest}, TContext>
}