/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const addressResponseDTOStateEnum = {
  AC: "AC",
  AL: "AL",
  AP: "AP",
  AM: "AM",
  BA: "BA",
  CE: "CE",
  DF: "DF",
  ES: "ES",
  GO: "GO",
  MA: "MA",
  MT: "MT",
  MS: "MS",
  MG: "MG",
  PA: "PA",
  PB: "PB",
  PR: "PR",
  PE: "PE",
  PI: "PI",
  RJ: "RJ",
  RN: "RN",
  RS: "RS",
  RO: "RO",
  RR: "RR",
  SC: "SC",
  SP: "SP",
  SE: "SE",
  TO: "TO",
} as const;

export type AddressResponseDTOStateEnumKey =
  (typeof addressResponseDTOStateEnum)[keyof typeof addressResponseDTOStateEnum];

export type AddressResponseDTO = {
  /**
   * @type string
   */
  street: string;
  /**
   * @type string
   */
  number: string;
  /**
   * @type string
   */
  complement?: string | null;
  /**
   * @type string
   */
  district: string;
  /**
   * @type string
   */
  city: string;
  /**
   * @type string
   */
  state: AddressResponseDTOStateEnumKey;
  /**
   * @type string
   */
  zip: string;
};
