/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const addressRequestDTOStateEnum = {
  AC: "AC",
  AL: "AL",
  AP: "AP",
  AM: "AM",
  BA: "BA",
  CE: "CE",
  DF: "DF",
  ES: "ES",
  GO: "GO",
  MA: "MA",
  MT: "MT",
  MS: "MS",
  MG: "MG",
  PA: "PA",
  PB: "PB",
  PR: "PR",
  PE: "PE",
  PI: "PI",
  RJ: "RJ",
  RN: "RN",
  RS: "RS",
  RO: "RO",
  RR: "RR",
  SC: "SC",
  SP: "SP",
  SE: "SE",
  TO: "TO",
} as const;

export type AddressRequestDTOStateEnumKey =
  (typeof addressRequestDTOStateEnum)[keyof typeof addressRequestDTOStateEnum];

/**
 * @description Endereço do aluno
 */
export type AddressRequestDTO = {
  /**
   * @description Rua ou Condomínio
   * @minLength 3
   * @maxLength 255
   * @type string
   */
  street: string;
  /**
   * @description Número da residência
   * @minLength 1
   * @maxLength 10
   * @type string
   */
  number: string;
  /**
   * @description Complemento do endereço
   * @maxLength 255
   * @type string | undefined
   */
  complement?: string;
  /**
   * @description Bairro do endereço
   * @minLength 3
   * @maxLength 255
   * @type string
   */
  district: string;
  /**
   * @description Cidade do endereço
   * @minLength 3
   * @maxLength 255
   * @type string
   */
  city: string;
  /**
   * @description Estado do endereço
   * @type string
   */
  state: AddressRequestDTOStateEnumKey;
  /**
   * @description CEP do endereço
   * @minLength 8
   * @maxLength 8
   * @type string
   */
  zip: string;
};
