/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo financeiro e quantitativo do aluno no periodo
 */
export type AlunoAtendimentosKpis = {
  /**
   * @description Total de atendimentos no periodo selecionado
   * @type integer | undefined, int64
   */
  totalAtendimentos?: number;
  /**
   * @description Total cobrado no periodo selecionado
   * @type number | undefined
   */
  totalCharged?: number;
  /**
   * @description Total pendente no periodo selecionado
   * @type number | undefined
   */
  totalPending?: number;
};
