/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo de alunos cadastrados
 */
export type AlunosKpisDTO = {
  /**
   * @description Total de alunos cadastrados
   * @type integer, int64
   */
  totalAlunos: number;
  /**
   * @description Total de alunos ativos
   * @type integer, int64
   */
  totalAlunosAtivos: number;
};
