/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const atendimentoResponseDTOTipoEnum = {
  AULA: "AULA",
  MENTORIA: "MENTORIA",
  TERAPIA: "TERAPIA",
  ORIENTACAO_VOCACIONAL: "ORIENTACAO_VOCACIONAL",
  ENEM: "ENEM",
  PAS: "PAS",
  OUTRO: "OUTRO",
} as const;

export type AtendimentoResponseDTOTipoEnumKey =
  (typeof atendimentoResponseDTOTipoEnum)[keyof typeof atendimentoResponseDTOTipoEnum];

export const atendimentoResponseDTOStatusEnum = {
  AGENDADO: "AGENDADO",
  CONCLUIDO: "CONCLUIDO",
  CANCELADO: "CANCELADO",
} as const;

export type AtendimentoResponseDTOStatusEnumKey =
  (typeof atendimentoResponseDTOStatusEnum)[keyof typeof atendimentoResponseDTOStatusEnum];

/**
 * @description Dados do atendimento retornados pela API
 */
export type AtendimentoResponseDTO = {
  /**
   * @description Identificador unico do atendimento
   * @type string, uuid
   */
  id: string;
  /**
   * @description Descricao do atendimento
   * @type string | undefined
   */
  descricao?: string;
  /**
   * @description Tipo de conteudo ou categoria do atendimento
   * @type string
   */
  tipo: AtendimentoResponseDTOTipoEnumKey;
  /**
   * @description Data/hora de inicio do atendimento
   * @type string, date-time
   */
  inicio: string;
  /**
   * @description Data/hora de fim do atendimento
   * @type string, date-time
   */
  fim: string;
  /**
   * @description Duracao do atendimento em horas
   * @type number, double
   */
  duracao: number;
  /**
   * @description Valor do atendimento cobrado do aluno
   * @type number
   */
  valor: number;
  /**
   * @description Pagamento do atendimento ao colaborador
   * @type number
   */
  repasse: number;
  /**
   * @description Lucro do atendimento
   * @type number
   */
  lucro: number;
  /**
   * @description ID do aluno vinculado ao atendimento
   * @type string, uuid
   */
  alunoId: string;
  /**
   * @description ID do colaborador vinculado ao atendimento
   * @type string, uuid
   */
  colaboradorId: string;
  /**
   * @description Status do atendimento
   * @type string
   */
  status: AtendimentoResponseDTOStatusEnumKey;
  /**
   * @description Data de criacao do atendimento
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @description Data de atualizacao do atendimento
   * @type string, date-time
   */
  updatedAt?: string | null;
};
