/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ColaboradorAtendimentosKpis } from "./ColaboradorAtendimentosKpis.ts";
import type { PageDTOAtendimentoResponseDTO } from "./PageDTOAtendimentoResponseDTO.ts";

/**
 * @description Agenda paginada e resumo financeiro do colaborador no periodo consultado
 */
export type AtendimentosColaboradorResponseDTO = {
  /**
   * @description Estrutura padrao de paginacao da API
   * @type object | undefined
   */
  atendimentos?: PageDTOAtendimentoResponseDTO;
  /**
   * @description Resumo financeiro e quantitativo do colaborador no periodo
   * @type object | undefined
   */
  resumo?: ColaboradorAtendimentosKpis;
};
