/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AtendimentosContentReportDTO = {
  /**
   * @type integer | undefined, int64
   */
  totalAulas?: number;
  /**
   * @type integer | undefined, int64
   */
  totalMentoria?: number;
  /**
   * @type integer | undefined, int64
   */
  totalTerapia?: number;
  /**
   * @type integer | undefined, int64
   */
  totalOV?: number;
  /**
   * @type integer | undefined, int64
   */
  totalENEM?: number;
  /**
   * @type integer | undefined, int64
   */
  totalPAS?: number;
  /**
   * @type integer | undefined, int64
   */
  totalOutros?: number;
};
