/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo financeiro de aluno no periodo
 * @example
 */
export type AtendimentosAlunosKpisDTO = {
  /**
   * @description ID do aluno
   * @type string | undefined, uuid
   */
  alunoId?: string;
  /**
   * @description Total de atendimentos no periodo
   * @type integer | undefined, int64
   */
  totalAtendimentos?: number;
  /**
   * @description Total cobrado do aluno no periodo
   * @type number | undefined
   */
  totalCobrado?: number;
  /**
   * @description Total pendente de cobranca do aluno no periodo
   * @type number | undefined
   */
  totalPendente?: number;
};
