/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const atendimentoResponseTipoEnum = {
    "AULA": "AULA",
    "MENTORIA": "MENTORIA",
    "TERAPIA": "TERAPIA",
    "ORIENTACAO_VOCACIONAL": "ORIENTACAO_VOCACIONAL",
    "ENEM": "ENEM",
    "PAS": "PAS",
    "OUTRO": "OUTRO"
} as const;

export type AtendimentoResponseTipoEnumKey = (typeof atendimentoResponseTipoEnum)[keyof typeof atendimentoResponseTipoEnum];

export const atendimentoResponseStatusEnum = {
    "AGENDADO": "AGENDADO",
    "CONCLUIDO": "CONCLUIDO",
    "CANCELADO": "CANCELADO"
} as const;

export type AtendimentoResponseStatusEnumKey = (typeof atendimentoResponseStatusEnum)[keyof typeof atendimentoResponseStatusEnum];

/**
 * @description Dados do atendimento retornados pela API
*/
export type AtendimentoResponse = {
    /**
     * @description Identificador unico do atendimento
     * @type integer, int64
    */
    id: number;
    /**
     * @description Descricao do atendimento
     * @type string | undefined
    */
    descricao?: string;
    /**
     * @description Tipo de conteudo ou categoria do atendimento
     * @type string
    */
    tipo: AtendimentoResponseTipoEnumKey;
    /**
     * @description Data/hora de inicio do atendimento
     * @type string, date-time
    */
    inicio: string;
    /**
     * @description Data/hora de fim do atendimento
     * @type string, date-time
    */
    fim: string;
    /**
     * @description Duracao do atendimento em horas
     * @type number, double
    */
    duracao: number;
    /**
     * @description Valor do atendimento cobrado do aluno
     * @type number
    */
    valor: number;
    /**
     * @description Pagamento do atendimento ao colaborador
     * @type number
    */
    repasse: number;
    /**
     * @description Lucro do atendimento
     * @type number
    */
    lucro: number;
    /**
     * @description ID do aluno vinculado ao atendimento
     * @type string, uuid
    */
    alunoId: string;
    /**
     * @description Nome do aluno vinculado ao atendimento
     * @type string
    */
    nomeAluno: string;
    /**
     * @description ID do colaborador vinculado ao atendimento
     * @type string, uuid
    */
    colaboradorId: string;
    /**
     * @description Nome do colaborador vinculado ao atendimento
     * @type string
    */
    nomeColaborador: string;
    /**
     * @description Status do atendimento
     * @type string
    */
    status: AtendimentoResponseStatusEnumKey;
    /**
     * @description Data de criacao do atendimento
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @description Data de atualizacao do atendimento
     * @type string, date-time
    */
    updatedAt?: string | null;
};