/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo financeiro consolidado baseado em atendimentos e despesas gerais
 */
export type AtendimentosKpisDTO = {
  /**
   * @description Total cobrado dos alunos no periodo
   * @type number | undefined
   */
  totalStudentCharged?: number;
  /**
   * @description Total pendente de cobranca dos alunos no periodo
   * @type number | undefined
   */
  totalStudentPending?: number;
  /**
   * @description Total pago aos colaboradores no periodo
   * @type number | undefined
   */
  totalEmployeePaid?: number;
  /**
   * @description Total pendente de pagamento aos colaboradores no periodo
   * @type number | undefined
   */
  totalEmployeePending?: number;
};
