/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Payload de autenticação
*/
export type AuthRequestDTO = {
    /**
     * @description E-mail usado no login
     * @minLength 1
     * @type string
    */
    username: string;
    /**
     * @description Senha do usuário
     * @minLength 1
     * @type string
    */
    password: string;
};