/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const authResponseDTORoleEnum = {
  STUDENT: "STUDENT",
  EMPLOYEE: "EMPLOYEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
} as const;

export type AuthResponseDTORoleEnumKey =
  (typeof authResponseDTORoleEnum)[keyof typeof authResponseDTORoleEnum];

/**
 * @description Resposta de autenticacao com access token JWT
 */
export type AuthResponseDTO = {
  /**
   * @description JWT de acesso
   * @type string | undefined
   */
  accessToken?: string;
  /**
   * @description Tempo de expiração em segundos
   * @type integer | undefined, int64
   */
  expiresIn?: number;
  /**
   * @description E-mail do usuário autenticado
   * @type string | undefined
   */
  username?: string;
  /**
   * @description Perfil de acesso do usuário autenticado
   * @type string | undefined
   */
  role?: AuthResponseDTORoleEnumKey;
};
