/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Payload para autenticar um usuário interno
 */
export type AuthLoginRequestDTO = {
  /**
   * @description Nome de usuário ou email do colaborador
   * @minLength 1
   * @type string
   */
  identifier: string;
  /**
   * @description Senha do usuário interno
   * @minLength 1
   * @type string
   */
  password: string;
};
