/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const calendarioAtendimentosResposeTipoEnum = {
  AULA: "AULA",
  MENTORIA: "MENTORIA",
  TERAPIA: "TERAPIA",
  ORIENTACAO_VOCACIONAL: "ORIENTACAO_VOCACIONAL",
  ENEM: "ENEM",
  PAS: "PAS",
  OUTRO: "OUTRO",
} as const;

export type CalendarioAtendimentosResposeTipoEnumKey =
  (typeof calendarioAtendimentosResposeTipoEnum)[keyof typeof calendarioAtendimentosResposeTipoEnum];

export type CalendarioAtendimentosRespose = {
  /**
   * @type integer | undefined, int64
   */
  id?: number;
  /**
   * @type string | undefined, uuid
   */
  colaboradorId?: string;
  /**
   * @type string | undefined, uuid
   */
  alunoId?: string;
  /**
   * @type string | undefined, date-time
   */
  inicio?: string;
  /**
   * @type string | undefined, date-time
   */
  fim?: string;
  /**
   * @description Tipo de conteudo ou categoria do atendimento
   * @type string | undefined
   */
  tipo?: CalendarioAtendimentosResposeTipoEnumKey;
  /**
   * @type string | undefined
   */
  nomeColaborador?: string;
  /**
   * @type string | undefined
   */
  nomeAluno?: string;
};
