/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CancelarTransacaoPathParams = {
  /**
   * @type integer, int64
   */
  transacaoId: number;
};

/**
 * @description Transacao cancelada com sucesso.
 */
export type CancelarTransacao200 = any;

export type CancelarTransacaoMutationResponse = CancelarTransacao200;

export type CancelarTransacaoMutation = {
  Response: CancelarTransacao200;
  PathParams: CancelarTransacaoPathParams;
  Errors: any;
};
