/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageDTOColaboradorResponseDTO } from "./PageDTOColaboradorResponseDTO.ts";

/**
 * @description Resumo e listagem paginada de colaboradores
 */
export type ColaboradoresResponseDTO = {
  /**
   * @description Total de colaboradores ativos
   * @type integer | undefined, int64
   */
  totalColaboradoresAtivos?: number;
  /**
   * @description Estrutura padrao de paginacao da API
   * @type object | undefined
   */
  colaboradores?: PageDTOColaboradorResponseDTO;
};
