/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Formato de payload para obter opções de colaboradores
 */
export type ColaboradoresKpisDTO = {
  /**
   * @description ID do funcionário
   * @type integer | undefined, int64
   */
  totalColaboradores?: number;
  /**
   * @description Total de colaboradores ativos
   * @type integer | undefined, int64
   */
  totalColaboradoresAtivos?: number;
};
