/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EnderecoRequestDTO } from "./EnderecoRequestDTO.ts";

export const colaboradorRequestDTOFuncaoEnum = {
  PROFESSOR: "PROFESSOR",
  ADMINISTRATIVO: "ADMINISTRATIVO",
  TERAPEUTA: "TERAPEUTA",
  MENTOR: "MENTOR",
} as const;

export type ColaboradorRequestDTOFuncaoEnumKey =
  (typeof colaboradorRequestDTOFuncaoEnum)[keyof typeof colaboradorRequestDTOFuncaoEnum];

/**
 * @description Formato de payload para criar um novo colaborador
 */
export type ColaboradorRequestDTO = {
  /**
   * @description Nome completo do colaborador
   * @minLength 1
   * @type string
   */
  nome: string;
  /**
   * @description Data de nascimento do colaborador
   * @type string, date
   */
  dataNascimento: string;
  /**
   * @description Chave PIX do colaborador
   * @minLength 1
   * @type string
   */
  pix: string;
  /**
   * @description Telefone de contato do colaborador
   * @minLength 1
   * @type string
   */
  telefone: string;
  /**
   * @description CPF do colaborador
   * @minLength 1
   * @type string
   */
  cpf: string;
  /**
   * @description E-mail do colaborador
   * @minLength 1
   * @type string
   */
  email: string;
  /**
   * @description Função do colaborador
   * @type string
   */
  funcao: ColaboradorRequestDTOFuncaoEnumKey;
  /**
   * @description Endereço do colaborador
   * @type object
   */
  endereco: EnderecoRequestDTO;
};
