/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const despesaRequestDTOCategoryEnum = {
  CONTAS: "CONTAS",
  ADMINISTRATIVO: "ADMINISTRATIVO",
  DESPENSA: "DESPENSA",
  MANUTENCAO: "MANUTENCAO",
  SERVICOS: "SERVICOS",
  MATERIAIS: "MATERIAIS",
  ASSINATURAS: "ASSINATURAS",
} as const;

export type DespesaRequestDTOCategoryEnumKey =
  (typeof despesaRequestDTOCategoryEnum)[keyof typeof despesaRequestDTOCategoryEnum];

/**
 * @description Payload para criacao ou atualizacao de despesa
 */
export type DespesaRequestDTO = {
  /**
   * @description Valor da despesa
   * @type number
   */
  amount: number;
  /**
   * @description Data de competencia da despesa
   * @type string, date-time
   */
  date: string;
  /**
   * @description Categoria da despesa geral
   * @type string
   */
  category: DespesaRequestDTOCategoryEnumKey;
  /**
   * @description Descricao da despesa
   * @minLength 1
   * @type string
   */
  description: string;
};
