/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EfetivarTransacaoQueryParams = {
  /**
   * @type integer, int64
   */
  transacaoId: number;
};

/**
 * @description Transacao efetivada com sucesso.
 */
export type EfetivarTransacao200 = any;

export const efetivarTransacaoMutationRequestEnum = {
  CREDITO: "CREDITO",
  DEBITO: "DEBITO",
  PIX: "PIX",
  TRANSFERENCIA: "TRANSFERENCIA",
  DINHEIRO: "DINHEIRO",
} as const;

export type EfetivarTransacaoMutationRequestEnumKey =
  (typeof efetivarTransacaoMutationRequestEnum)[keyof typeof efetivarTransacaoMutationRequestEnum];

export type EfetivarTransacaoMutationRequest =
  EfetivarTransacaoMutationRequestEnumKey;

export type EfetivarTransacaoMutationResponse = EfetivarTransacao200;

export type EfetivarTransacaoMutation = {
  Response: EfetivarTransacao200;
  Request: EfetivarTransacaoMutationRequest;
  QueryParams: EfetivarTransacaoQueryParams;
  Errors: any;
};
