/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const employeeRequestDTODutyEnum = {
  TEACHER: "TEACHER",
  ADM: "ADM",
  THERAPIST: "THERAPIST",
  MENTOR: "MENTOR",
  SYSTEM: "SYSTEM",
} as const;

export type EmployeeRequestDTODutyEnumKey =
  (typeof employeeRequestDTODutyEnum)[keyof typeof employeeRequestDTODutyEnum];

/**
 * @description Dados do funcionário
 */
export type EmployeeRequestDTO = {
  /**
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @type string, date
   */
  birthdate: string;
  /**
   * @minLength 1
   * @type string
   */
  pix: string;
  /**
   * @minLength 1
   * @pattern ^\(\d{2}\)\s?\d{4,5}-\d{4}$
   * @type string
   */
  contact: string;
  /**
   * @minLength 1
   * @pattern ^\d{3}\.\d{3}\.\d{3}-\d{2}$
   * @type string
   */
  cpf: string;
  /**
   * @minLength 1
   * @type string
   */
  email: string;
  /**
   * @type string
   */
  duty: EmployeeRequestDTODutyEnumKey;
};
