/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddressResponseDTO } from "./AddressResponseDTO.ts";

export const employeeResponseDTODutyEnum = {
  TEACHER: "TEACHER",
  ADM: "ADM",
  THERAPIST: "THERAPIST",
  MENTOR: "MENTOR",
  SYSTEM: "SYSTEM",
} as const;

export type EmployeeResponseDTODutyEnumKey =
  (typeof employeeResponseDTODutyEnum)[keyof typeof employeeResponseDTODutyEnum];

export type EmployeeResponseDTO = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string, date
   */
  birthdate: string;
  /**
   * @type string
   */
  pix: string;
  /**
   * @type string
   */
  contact: string;
  /**
   * @type string
   */
  cpf: string;
  /**
   * @type string
   */
  email: string;
  /**
   * @description Função/Papel do funcionário
   * @type string
   */
  duty: EmployeeResponseDTODutyEnumKey;
  /**
   * @description Endereço
   * @type object
   */
  address: AddressResponseDTO;
  /**
   * @type boolean
   */
  active?: boolean | null;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt?: string | null;
};
