/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ExcluirAtendimentoPathParams = {
  /**
   * @type integer, int64
   */
  id: number;
};

/**
 * @description Atendimento removido sem corpo de resposta.
 */
export type ExcluirAtendimento204 = any;

export type ExcluirAtendimentoMutationResponse = ExcluirAtendimento204;

export type ExcluirAtendimentoMutation = {
  Response: ExcluirAtendimento204;
  PathParams: ExcluirAtendimentoPathParams;
  Errors: any;
};
