/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlunoResponseDTO } from "./AlunoResponseDTO.ts";

export type GetAlunoByIdPathParams = {
  /**
   * @type string, uuid
   */
  alunoId: string;
};

/**
 * @description Aluno retornado com sucesso.
 */
export type GetAlunoById200 = AlunoResponseDTO;

export type GetAlunoByIdQueryResponse = GetAlunoById200;

export type GetAlunoByIdQuery = {
  Response: GetAlunoById200;
  PathParams: GetAlunoByIdPathParams;
  Errors: any;
};
