/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ColaboradoresKpisDTO } from "./ColaboradoresKpisDTO.ts";

/**
 * @description KPIs de colaboradores retornados com sucesso.
 */
export type GetColaboradoresKpis200 = ColaboradoresKpisDTO;

export type GetColaboradoresKpisQueryResponse = GetColaboradoresKpis200;

export type GetColaboradoresKpisQuery = {
  Response: GetColaboradoresKpis200;
  Errors: any;
};
