/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PagedModelTransacaoResponseDTO } from "./PagedModelTransacaoResponseDTO.ts";

export const getTransacoesQueryParamsTipoEnum = {
  ENTRADA: "ENTRADA",
  SAIDA: "SAIDA",
} as const;

export type GetTransacoesQueryParamsTipoEnumKey =
  (typeof getTransacoesQueryParamsTipoEnum)[keyof typeof getTransacoesQueryParamsTipoEnum];

export const getTransacoesQueryParamsCategoriaEnum = {
  PGTO_ALUNO: "PGTO_ALUNO",
  INVESTIMENTO: "INVESTIMENTO",
  PGTO_COLABORADOR: "PGTO_COLABORADOR",
  CONTAS: "CONTAS",
  MATERIAL: "MATERIAL",
  DESPENSA: "DESPENSA",
  MANUTENCAO: "MANUTENCAO",
} as const;

export type GetTransacoesQueryParamsCategoriaEnumKey =
  (typeof getTransacoesQueryParamsCategoriaEnum)[keyof typeof getTransacoesQueryParamsCategoriaEnum];

export const getTransacoesQueryParamsStatusEnum = {
  PAGO: "PAGO",
  PENDENTE: "PENDENTE",
  ATRASADO: "ATRASADO",
  CANCELADO: "CANCELADO",
} as const;

export type GetTransacoesQueryParamsStatusEnumKey =
  (typeof getTransacoesQueryParamsStatusEnum)[keyof typeof getTransacoesQueryParamsStatusEnum];

export const getTransacoesQueryParamsFormaPagamentoEnum = {
  CREDITO: "CREDITO",
  DEBITO: "DEBITO",
  PIX: "PIX",
  TRANSFERENCIA: "TRANSFERENCIA",
  DINHEIRO: "DINHEIRO",
} as const;

export type GetTransacoesQueryParamsFormaPagamentoEnumKey =
  (typeof getTransacoesQueryParamsFormaPagamentoEnum)[keyof typeof getTransacoesQueryParamsFormaPagamentoEnum];

export type GetTransacoesQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type string | undefined, uuid
   */
  pagadorId?: string;
  /**
   * @type string | undefined, uuid
   */
  recebedorId?: string;
  /**
   * @type string | undefined, date-time
   */
  dataEfetivada?: string;
  /**
   * @type string | undefined
   */
  tipo?: GetTransacoesQueryParamsTipoEnumKey;
  /**
   * @type string | undefined
   */
  categoria?: GetTransacoesQueryParamsCategoriaEnumKey;
  /**
   * @type string | undefined
   */
  status?: GetTransacoesQueryParamsStatusEnumKey;
  /**
   * @type string | undefined
   */
  formaPagamento?: GetTransacoesQueryParamsFormaPagamentoEnumKey;
  /**
   * @type string | undefined
   */
  busca?: string;
};

/**
 * @description Pagina de transacoes retornada conforme os filtros informados.
 */
export type GetTransacoes200 = PagedModelTransacaoResponseDTO;

export type GetTransacoesQueryResponse = GetTransacoes200;

export type GetTransacoesQuery = {
  Response: GetTransacoes200;
  QueryParams: GetTransacoesQueryParams;
  Errors: any;
};
