/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EventResponseDTO } from "./EventResponseDTO.ts";

export type PageDTOEventResponseDTO = {
  /**
   * @description Número da página atual
   * @type integer, int32
   */
  page: number;
  /**
   * @description Tamanho da página
   * @type integer, int32
   */
  size: number;
  /**
   * @description Total de elementos
   * @type integer, int64
   */
  totalElements: number;
  /**
   * @description Total de páginas
   * @type integer, int32
   */
  totalPages: number;
  /**
   * @description Lista de elementos
   * @type array
   */
  content: EventResponseDTO[];
};
