/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageMetadata } from "./PageMetadata.ts";
import type { StudentResponseDTO } from "./StudentResponseDTO.ts";

export type PagedModelStudentResponseDTO = {
  /**
   * @type array | undefined
   */
  content?: StudentResponseDTO[];
  /**
   * @type object | undefined
   */
  page?: PageMetadata;
};
