/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PageMetadata } from "./PageMetadata.ts";
import type { ResponsavelResponseDTO } from "./ResponsavelResponseDTO.ts";

export type PagedModelResponsavelResponseDTO = {
    /**
     * @type array | undefined
    */
    content?: ResponsavelResponseDTO[];
    /**
     * @type object | undefined
    */
    page?: PageMetadata;
};