/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoResponse } from "./AtendimentoResponse.ts";
import type { PageMetadata } from "./PageMetadata.ts";

export type PagedModelAtendimentoResponse = {
  /**
   * @type array | undefined
   */
  content?: AtendimentoResponse[];
  /**
   * @type object | undefined
   */
  page?: PageMetadata;
};
