/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ParentResponseDTO = {
  /**
   * @description ID do responsável
   * @type string, uuid
   */
  id: string;
  /**
   * @description Nome do responsável
   * @type string
   */
  name: string;
  /**
   * @description Email do responsável
   * @type string
   */
  email: string;
  /**
   * @description Contato do responsável
   * @type string
   */
  contact: string;
  /**
   * @description CPF do responsável
   * @type string
   */
  cpf: string;
  /**
   * @type string, date-time
   */
  archivedAt?: string | null;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt?: string | null;
};
