/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Reagendar um atendimento
 */
export type ReagendarRequestDTO = {
  /**
   * @description Novo inicio do atendimento
   * @type string | undefined, date-time
   */
  novoInicio?: string;
  /**
   * @description Duracao do atendimento
   * @type number | undefined, double
   */
  duracao?: number;
};
