/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RelatorioAtendimentosResponse = {
  /**
   * @type integer | undefined, int64
   */
  totalAtendimentos?: number;
  /**
   * @type integer | undefined, int64
   */
  totalAulas?: number;
  /**
   * @type number | undefined, double
   */
  procentagemAulas?: number;
  /**
   * @type integer | undefined, int64
   */
  totalMentoria?: number;
  /**
   * @type number | undefined, double
   */
  procentagemMentoria?: number;
  /**
   * @type integer | undefined, int64
   */
  totalTerapia?: number;
  /**
   * @type number | undefined, double
   */
  procentagemTerapia?: number;
  /**
   * @type integer | undefined, int64
   */
  totalOV?: number;
  /**
   * @type number | undefined, double
   */
  procentagemOV?: number;
  /**
   * @type integer | undefined, int64
   */
  totalENEM?: number;
  /**
   * @type number | undefined, double
   */
  procentagemENEM?: number;
  /**
   * @type integer | undefined, int64
   */
  totalPAS?: number;
  /**
   * @type number | undefined, double
   */
  procentagemPAS?: number;
  /**
   * @type integer | undefined, int64
   */
  totalOutros?: number;
  /**
   * @type number | undefined, double
   */
  procentagemOutros?: number;
};
