/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddressRequestDTO } from "./AddressRequestDTO.ts";
import type { ParentUpdateDTO } from "./ParentUpdateDTO.ts";

/**
 * @description Formato de payload para o update de um aluno
 */
export type StudentUpdateDTO = {
  /**
   * @description Nome do aluno
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @description Data de nascimento do aluno
   * @type string, date
   */
  birthdate: string;
  /**
   * @description Escola do aluno
   * @minLength 1
   * @type string
   */
  school: string;
  /**
   * @description Contato do aluno
   * @minLength 1
   * @type string
   */
  contact: string;
  /**
   * @description Email do aluno
   * @minLength 1
   * @type string
   */
  email: string;
  /**
   * @description Endereço do aluno
   * @type object
   */
  address: AddressRequestDTO;
  /**
   * @description Formato de payload para o update de um responsável
   * @type object
   */
  parent: ParentUpdateDTO;
};
