/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo do responsável vinculado ao aluno
 */
export type StudentResponsibleSummaryDTO = {
  /**
   * @description ID do responsável
   * @type string, uuid
   */
  responsibleId: string;
  /**
   * @description Nome do responsável
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @description Contato do responsável
   * @minLength 1
   * @type string
   */
  contact: string;
  /**
   * @description CPF do responsável
   * @minLength 1
   * @type string
   */
  cpf: string;
};
