/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddressRequestDTO } from "./AddressRequestDTO.ts";

/**
 * @description Formato de payload para o cadastro de um aluno
 */
export type StudentRequestDTO = {
  /**
   * @description Nome do aluno
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @description Data de nascimento do aluno
   * @type string, date
   */
  birthdate: string;
  /**
   * @description CPF do aluno
   * @minLength 1
   * @type string
   */
  cpf: string;
  /**
   * @description Escola do aluno
   * @minLength 1
   * @type string
   */
  school: string;
  /**
   * @description Contato do aluno
   * @minLength 1
   * @type string
   */
  contact: string;
  /**
   * @description Email do aluno
   * @minLength 1
   * @type string
   */
  email: string;
  /**
   * @description Endereço do aluno
   * @type object
   */
  address: AddressRequestDTO;
  /**
   * @description ID do responsável do aluno
   * @type string, uuid
   */
  parentId: string;
};
