/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const transacaoRequestDTOCategoriaEnum = {
  PGTO_ALUNO: "PGTO_ALUNO",
  INVESTIMENTO: "INVESTIMENTO",
  PGTO_COLABORADOR: "PGTO_COLABORADOR",
  CONTAS: "CONTAS",
  MATERIAL: "MATERIAL",
  DESPENSA: "DESPENSA",
  MANUTENCAO: "MANUTENCAO",
} as const;

export type TransacaoRequestDTOCategoriaEnumKey =
  (typeof transacaoRequestDTOCategoriaEnum)[keyof typeof transacaoRequestDTOCategoriaEnum];

/**
 * @description Payload para criar uma despesa manual
 */
export type TransacaoRequestDTO = {
  /**
   * @description Valor da despesa
   * @type number
   */
  valor: number;
  /**
   * @description Categoria da despesa
   * @type string
   */
  categoria: TransacaoRequestDTOCategoriaEnumKey;
};
