/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const userResponseDTORoleEnum = {
  STUDENT: "STUDENT",
  EMPLOYEE: "EMPLOYEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
} as const;

export type UserResponseDTORoleEnumKey =
  (typeof userResponseDTORoleEnum)[keyof typeof userResponseDTORoleEnum];

/**
 * @description Dados do usuario retornados pela API
 */
export type UserResponseDTO = {
  /**
   * @description ID do usuario
   * @type string, uuid
   */
  id: string;
  /**
   * @description E-mail usado no login
   * @type string
   */
  username: string;
  /**
   * @description Perfil de acesso
   * @type string
   */
  role: UserResponseDTORoleEnumKey;
  /**
   * @description Indica se a conta esta ativa
   * @type boolean
   */
  active: boolean;
  /**
   * @description Data de criacao
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @description Data de atualizacao
   * @type string, date-time
   */
  updatedAt: string;
};
