/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetEventsByEmployeeQueryResponse,
  GetEventsByEmployeePathParams,
  GetEventsByEmployeeQueryParams,
  GetEventsByEmployee400,
} from "../../types/event/GetEventsByEmployee.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getEventsByEmployeeQueryResponseSchema } from "../../schemas/event/getEventsByEmployeeSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getEventsByEmployeeQueryKey = (
  employeeId: GetEventsByEmployeePathParams["employeeId"],
  params?: GetEventsByEmployeeQueryParams,
) =>
  [
    {
      url: "/v1/events/employee/:employeeId",
      params: { employeeId: employeeId },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetEventsByEmployeeQueryKey = ReturnType<
  typeof getEventsByEmployeeQueryKey
>;

/**
 * @description Retorna um evento específico com base no ID do colaborador.
 * @summary Listar evento por ID
 * {@link /v1/events/employee/:employeeId}
 */
export async function getEventsByEmployee(
  employeeId: GetEventsByEmployeePathParams["employeeId"],
  params?: GetEventsByEmployeeQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetEventsByEmployeeQueryResponse,
    ResponseErrorConfig<GetEventsByEmployee400>,
    unknown
  >({
    method: "GET",
    url: `/v1/events/employee/${employeeId}`,
    baseURL: `http://localhost:8080`,
    params,
    ...requestConfig,
  });
  return getEventsByEmployeeQueryResponseSchema.parse(res.data);
}

export function getEventsByEmployeeQueryOptions(
  employeeId: GetEventsByEmployeePathParams["employeeId"],
  params?: GetEventsByEmployeeQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getEventsByEmployeeQueryKey(employeeId, params);
  return queryOptions<
    GetEventsByEmployeeQueryResponse,
    ResponseErrorConfig<GetEventsByEmployee400>,
    GetEventsByEmployeeQueryResponse,
    typeof queryKey
  >({
    enabled: !!employeeId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getEventsByEmployee(employeeId, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna um evento específico com base no ID do colaborador.
 * @summary Listar evento por ID
 * {@link /v1/events/employee/:employeeId}
 */
export function useGetEventsByEmployee<
  TData = GetEventsByEmployeeQueryResponse,
  TQueryData = GetEventsByEmployeeQueryResponse,
  TQueryKey extends QueryKey = GetEventsByEmployeeQueryKey,
>(
  employeeId: GetEventsByEmployeePathParams["employeeId"],
  params?: GetEventsByEmployeeQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetEventsByEmployeeQueryResponse,
        ResponseErrorConfig<GetEventsByEmployee400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getEventsByEmployeeQueryKey(employeeId, params);

  const query = useQuery(
    {
      ...getEventsByEmployeeQueryOptions(employeeId, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetEventsByEmployee400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
