/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetEventsByStudentQueryResponse,
  GetEventsByStudentPathParams,
  GetEventsByStudentQueryParams,
  GetEventsByStudent400,
} from "../../types/event/GetEventsByStudent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getEventsByStudentQueryKey = (
  studentId: GetEventsByStudentPathParams["studentId"],
  params?: GetEventsByStudentQueryParams,
) =>
  [
    { url: "/v1/events/student/:studentId", params: { studentId: studentId } },
    ...(params ? [params] : []),
  ] as const;

export type GetEventsByStudentQueryKey = ReturnType<
  typeof getEventsByStudentQueryKey
>;

/**
 * @description Retorna um evento específico com base no ID do aluno.
 * @summary Listar evento por ID
 * {@link /v1/events/student/:studentId}
 */
export async function getEventsByStudent(
  studentId: GetEventsByStudentPathParams["studentId"],
  params?: GetEventsByStudentQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetEventsByStudentQueryResponse,
    ResponseErrorConfig<GetEventsByStudent400>,
    unknown
  >({
    method: "GET",
    url: `/v1/events/student/${studentId}`,
    baseURL: `http://localhost:8080`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getEventsByStudentQueryOptions(
  studentId: GetEventsByStudentPathParams["studentId"],
  params?: GetEventsByStudentQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getEventsByStudentQueryKey(studentId, params);
  return queryOptions<
    GetEventsByStudentQueryResponse,
    ResponseErrorConfig<GetEventsByStudent400>,
    GetEventsByStudentQueryResponse,
    typeof queryKey
  >({
    enabled: !!studentId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getEventsByStudent(studentId, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna um evento específico com base no ID do aluno.
 * @summary Listar evento por ID
 * {@link /v1/events/student/:studentId}
 */
export function useGetEventsByStudent<
  TData = GetEventsByStudentQueryResponse,
  TQueryData = GetEventsByStudentQueryResponse,
  TQueryKey extends QueryKey = GetEventsByStudentQueryKey,
>(
  studentId: GetEventsByStudentPathParams["studentId"],
  params?: GetEventsByStudentQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetEventsByStudentQueryResponse,
        ResponseErrorConfig<GetEventsByStudent400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getEventsByStudentQueryKey(studentId, params);

  const query = useQuery(
    {
      ...getEventsByStudentQueryOptions(studentId, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetEventsByStudent400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
