/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetEventByIdQueryResponse,
  GetEventByIdPathParams,
} from "../../types/events/GetEventById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getEventByIdQueryKey = (
  eventId: GetEventByIdPathParams["eventId"],
) => [{ url: "/v1/events/:eventId", params: { eventId: eventId } }] as const;

export type GetEventByIdQueryKey = ReturnType<typeof getEventByIdQueryKey>;

/**
 * @description Retorna um evendo por ID.
 * {@link /v1/events/:eventId}
 */
export async function getEventById(
  eventId: GetEventByIdPathParams["eventId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetEventByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/events/${eventId}`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function getEventByIdQueryOptions(
  eventId: GetEventByIdPathParams["eventId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getEventByIdQueryKey(eventId);
  return queryOptions<
    GetEventByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetEventByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!eventId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getEventById(eventId, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna um evendo por ID.
 * {@link /v1/events/:eventId}
 */
export function useGetEventById<
  TData = GetEventByIdQueryResponse,
  TQueryData = GetEventByIdQueryResponse,
  TQueryKey extends QueryKey = GetEventByIdQueryKey,
>(
  eventId: GetEventByIdPathParams["eventId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetEventByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getEventByIdQueryKey(eventId);

  const query = useQuery(
    {
      ...getEventByIdQueryOptions(eventId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
