
import aprimorar.financeiro.repasses.domain.RepasseIndividualEntity;
import aprimorar.financeiro.repasses.repository.RepasseIndividualRepository;
import aprimorar.financeiro.repasses.repository.specifications.RepasseIndividualSpecifications;
import aprimorar.financeiro.repasses.web.dto.RepasseIndividualFiltroRequest;
import aprimorar.financeiro.repasses.web.dto.RepasseIndividualResponse;
