/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/validations/zod";

export const classesByContentDTOSchema = z.object({
  content: z.optional(z.string()),
  count: z.optional(z.int()),
  percentage: z.optional(z.number()),
});

export type ClassesByContentDTOSchema = z.infer<
  typeof classesByContentDTOSchema
>;
