/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/validations/zod";

export const employeeSummaryDTOSchema = z.object({
  id: z.uuid(),
  name: z.string(),
});

export type EmployeeSummaryDTOSchema = z.infer<typeof employeeSummaryDTOSchema>;
