/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Dados do funcionário
 */
export const employeeRequestDTOSchema = z
  .object({
    name: z.string().min(1),
    birthdate: z.iso.date(),
    pix: z.string().min(1),
    contact: z
      .string()
      .min(1)
      .regex(/^\(\d{2}\)\s?\d{4,5}-\d{4}$/),
    cpf: z
      .string()
      .min(1)
      .regex(/^\d{3}\.\d{3}\.\d{3}-\d{2}$/),
    email: z.string().min(1),
    duty: z.enum(["TEACHER", "ADM", "THERAPIST", "MENTOR", "SYSTEM"]),
  })
  .describe("Dados do funcionário");

export type EmployeeRequestDTOSchema = z.infer<typeof employeeRequestDTOSchema>;
