/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/validations/zod";

/**
 * @description Dados do evento
 */
export const eventRequestDTOSchema = z
  .object({
    title: z.string().min(0).max(100),
    description: z.optional(z.string().min(0).max(500)),
    startDate: z.iso.datetime(),
    endDate: z.iso.datetime(),
    price: z.number(),
    payment: z.number(),
    content: z.enum([
      "AULA",
      "MENTORIA",
      "TERAPIA",
      "ORIENTACAO_VOCACIONAL",
      "ENEM",
      "PAS",
      "OUTRO",
    ]),
    studentId: z.uuid(),
    employeeId: z.uuid(),
  })
  .describe("Dados do evento");

export type EventRequestDTOSchema = z.infer<typeof eventRequestDTOSchema>;
