/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/validations/zod";

export const pageMetadataSchema = z.object({
  size: z.optional(z.int()),
  number: z.optional(z.int()),
  totalElements: z.optional(z.int()),
  totalPages: z.optional(z.int()),
});

export type PageMetadataSchema = z.infer<typeof pageMetadataSchema>;
