/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Dados do responsável
 */
export const parentRequestDTOSchema = z
  .object({
    name: z.string().describe("Nome do responsável"),
    email: z.string().describe("Email do responsável"),
    contact: z.string().describe("Contato do responsável"),
    cpf: z.string().describe("CPF do responsável"),
  })
  .describe("Dados do responsável");

export type ParentRequestDTOSchema = z.infer<typeof parentRequestDTOSchema>;
