/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const problemDetailResponseDTOSchema = z.object({
  type: z.optional(z.string().describe("Tipo do Erro")),
  title: z.optional(z.string().describe("Título")),
  status: z.optional(z.int().describe("Status HTTP")),
  detail: z.optional(z.string().describe("Detalhe geral do erro")),
  instance: z.optional(z.string().describe("Caminho (URI) onde ocorreu")),
  errors: z.optional(
    z
      .object({})
      .catchall(z.string().describe("Dicionário de erros por campo"))
      .describe("Dicionário de erros por campo"),
  ),
});

export type ProblemDetailResponseDTOSchema = z.infer<
  typeof problemDetailResponseDTOSchema
>;
