/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addressResponseDTOSchema } from "./addressResponseDTOSchema.ts";
import { parentResponseDTOSchema } from "./parentResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

export const studentResponseDTOSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  contact: z.string(),
  email: z.string(),
  cpf: z.string(),
  birthdate: z.iso.date(),
  school: z.string(),
  age: z.int(),
  get address() {
    return addressResponseDTOSchema;
  },
  get parent() {
    return parentResponseDTOSchema;
  },
  archivedAt: z.iso.datetime().nullish(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime().nullish(),
});

export type StudentResponseDTOSchema = z.infer<typeof studentResponseDTOSchema>;
