/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const studentSummaryDTOSchema = z.object({
  id: z.uuid(),
  name: z.string(),
});

export type StudentSummaryDTOSchema = z.infer<typeof studentSummaryDTOSchema>;
