/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const studentOptionDTOSchema = z.object({
  id: z.uuid(),
  name: z.string(),
});

export type StudentOptionDTOSchema = z.infer<typeof studentOptionDTOSchema>;
