spring.datasource.url=jdbc:postgresql://db:5432/aprimorar
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.sql.init.mode=never

spring.jpa.show-sql=false

logging.level.com.aprimorar=INFO
