/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { eventRequestDTOSchema } from "../eventRequestDTOSchema.ts";
import { eventResponseDTOSchema } from "../eventResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Evento criado com sucesso.
 */
export const createEvent201Schema = z
  .lazy(() => eventResponseDTOSchema)
  .describe("Dados do evento retornados pela API");

export const createEventMutationRequestSchema = z
  .lazy(() => eventRequestDTOSchema)
  .describe("Formato de payload para o cadastro e/ou update de um evento");

export const createEventMutationResponseSchema = z.lazy(
  () => createEvent201Schema,
);
