/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageDTOEventResponseDTOSchema } from "../pageDTOEventResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getEventsByStudentPathParamsSchema = z.object({
  studentId: z.uuid(),
});

export const getEventsByStudentQueryParamsSchema = z.object({
  page: z.coerce
    .number()
    .int()
    .min(0)
    .default(0)
    .describe("Zero-based page index (0..N)"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(20)
    .describe("The size of the page to be returned"),
  sort: z.optional(
    z
      .array(z.string())
      .describe(
        "Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
      ),
  ),
});

/**
 * @description Lista de eventos do aluno retornada com sucesso.
 */
export const getEventsByStudent200Schema = z.lazy(
  () => pageDTOEventResponseDTOSchema,
);

export const getEventsByStudentQueryResponseSchema = z.lazy(
  () => getEventsByStudent200Schema,
);
