/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { eventRequestDTOSchema } from "../eventRequestDTOSchema.ts";
import { eventResponseDTOSchema } from "../eventResponseDTOSchema.ts";
import { z } from "zod/v4";

export const updateEventPathParamsSchema = z.object({
  eventId: z.uuid(),
});

/**
 * @description Evento autalizado com sucesso.
 */
export const updateEvent200Schema = z
  .lazy(() => eventResponseDTOSchema)
  .describe("Dados do evento retornados pela API");

export const updateEventMutationRequestSchema = z
  .lazy(() => eventRequestDTOSchema)
  .describe("Formato de payload para o cadastro e/ou update de um evento");

export const updateEventMutationResponseSchema = z.lazy(
  () => updateEvent200Schema,
);
