/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ColaboradorRequestDTO } from "../ColaboradorRequestDTO.ts";
import type { ColaboradorResponseDTO } from "../ColaboradorResponseDTO.ts";

/**
 * @description Colaborador criado com sucesso.
 */
export type CreateColaborador201 = ColaboradorResponseDTO;

export type CreateColaboradorMutationRequest = ColaboradorRequestDTO;

export type CreateColaboradorMutationResponse = CreateColaborador201;

export type CreateColaboradorMutation = {
  Response: CreateColaborador201;
  Request: CreateColaboradorMutationRequest;
  Errors: any;
};
