/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ColaboradorResponseDTO } from "../ColaboradorResponseDTO.ts";

export type FindColaboradorByIdPathParams = {
  /**
   * @type string, uuid
   */
  colaboradorId: string;
};

/**
 * @description Colaborador retornado com sucesso.
 */
export type FindColaboradorById200 = ColaboradorResponseDTO;

export type FindColaboradorByIdQueryResponse = FindColaboradorById200;

export type FindColaboradorByIdQuery = {
  Response: FindColaboradorById200;
  PathParams: FindColaboradorByIdPathParams;
  Errors: any;
};
