/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ColaboradoresResponseDTO } from "../ColaboradoresResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetColaboradoresQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 10
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type string | undefined
   */
  busca?: string;
  /**
   * @type boolean | undefined
   */
  arquivado?: boolean;
};

/**
 * @description Lista de colaboradores retornada com sucesso.
 */
export type GetColaboradores200 = ColaboradoresResponseDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetColaboradores400 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetColaboradores500 = ProblemResponseDTO;

export type GetColaboradoresQueryResponse = GetColaboradores200;

export type GetColaboradoresQuery = {
  Response: GetColaboradores200;
  QueryParams: GetColaboradoresQueryParams;
  Errors: GetColaboradores400 | GetColaboradores500;
};
