/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ColaboradoresListDTO } from "../ColaboradoresListDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

/**
 * @description Lista de opções de colaboradores retornada com sucesso.
 */
export type ListColaboradores200 = ColaboradoresListDTO[];

/**
 * @description Erro interno do sistema
 */
export type ListColaboradores500 = ProblemResponseDTO;

export type ListColaboradoresQueryResponse = ListColaboradores200;

export type ListColaboradoresQuery = {
  Response: ListColaboradores200;
  Errors: ListColaboradores500;
};
