/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ColaboradorRequestDTO } from "../ColaboradorRequestDTO.ts";
import type { ColaboradorResponseDTO } from "../ColaboradorResponseDTO.ts";

export type UpdateColaboradorPathParams = {
    /**
     * @type string, uuid
    */
    colaboradorId: string;
};

/**
 * @description Colaborador atualizado com sucesso.
*/
export type UpdateColaborador200 = ColaboradorResponseDTO;

export type UpdateColaboradorMutationRequest = ColaboradorRequestDTO;

export type UpdateColaboradorMutationResponse = UpdateColaborador200;

export type UpdateColaboradorMutation = {
    Response: UpdateColaborador200;
    Request: UpdateColaboradorMutationRequest;
    PathParams: UpdateColaboradorPathParams;
    Errors: any;
};