/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const arquivarResponsavelPathParamsSchema = z.object({
  responsavelId: z.uuid(),
});

/**
 * @description Responsável arquivado com sucesso
 */
export const arquivarResponsavel204Schema = z.any();

/**
 * @description Responsável não encontrado
 */
export const arquivarResponsavel404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const arquivarResponsavel409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const arquivarResponsavel500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const arquivarResponsavelMutationResponseSchema = z.lazy(
  () => arquivarResponsavel204Schema,
);
