/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { responsavelRequestDTOSchema } from "../responsavelRequestDTOSchema.ts";
import { responsavelResponseDTOSchema } from "../responsavelResponseDTOSchema.ts";
import { z } from "zod/v4";

export const atualizarResponsavelPathParamsSchema = z.object({
  responsavelId: z.uuid(),
});

/**
 * @description Responsável atualizado com sucesso
 */
export const atualizarResponsavel200Schema = z
  .lazy(() => responsavelResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

/**
 * @description Falha de validação
 */
export const atualizarResponsavel400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Responsável não encontrado
 */
export const atualizarResponsavel404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const atualizarResponsavel409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const atualizarResponsavel500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const atualizarResponsavelMutationRequestSchema = z
  .lazy(() => responsavelRequestDTOSchema)
  .describe("Formato de payload para criar um novo responsável");

export const atualizarResponsavelMutationResponseSchema = z.lazy(
  () => atualizarResponsavel200Schema,
);
