/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { responsavelResponseDTOSchema } from "../responsavelResponseDTOSchema.ts";
import { z } from "zod/v4";

export const buscarResponsavelPorIdPathParamsSchema = z.object({
  responsavelId: z.uuid(),
});

/**
 * @description Responsável retornado com sucesso
 */
export const buscarResponsavelPorId200Schema = z
  .lazy(() => responsavelResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

/**
 * @description Responsável não encontrado
 */
export const buscarResponsavelPorId404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const buscarResponsavelPorId500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const buscarResponsavelPorIdQueryResponseSchema = z.lazy(
  () => buscarResponsavelPorId200Schema,
);
