/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { responsavelRequestDTOSchema } from "../responsavelRequestDTOSchema.ts";
import { responsavelResponseDTOSchema } from "../responsavelResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Responsável criado com sucesso
 */
export const createResponsavel201Schema = z
  .lazy(() => responsavelResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

/**
 * @description Falha de validação
 */
export const createResponsavel400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const createResponsavel409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const createResponsavel500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const createResponsavelMutationRequestSchema = z
  .lazy(() => responsavelRequestDTOSchema)
  .describe("Formato de payload para criar um novo responsável");

export const createResponsavelMutationResponseSchema = z.lazy(
  () => createResponsavel201Schema,
);
