/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageDTOResponsavelResponseDTOSchema } from "../pageDTOResponsavelResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getResponsaveisQueryParamsSchema = z.object({
  page: z.coerce
    .number()
    .int()
    .min(0)
    .default(0)
    .describe("Zero-based page index (0..N)"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(10)
    .describe("The size of the page to be returned"),
  sort: z
    .array(z.string())
    .describe(
      "Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
    ),
  search: z.optional(z.string()),
  archived: z.optional(z.boolean()),
});

/**
 * @description Lista de responsáveis retornada com sucesso.
 */
export const getResponsaveis200Schema = z
  .lazy(() => pageDTOResponsavelResponseDTOSchema)
  .describe("Estrutura padrao de paginacao da API");

/**
 * @description Parâmetros inválidos
 */
export const getResponsaveis400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const getResponsaveis500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const getResponsaveisQueryResponseSchema = z.lazy(
  () => getResponsaveis200Schema,
);
