/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { responsaveisListDTOSchema } from "../responsaveisListDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de opções retornada com sucesso.
 */
export const listResponsaveis200Schema = z.array(
  z
    .lazy(() => responsaveisListDTOSchema)
    .describe("Lista de responsáveis para dropdown retornados da API"),
);

/**
 * @description Erro interno do sistema
 */
export const listResponsaveis500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const listResponsaveisQueryResponseSchema = z.lazy(
  () => listResponsaveis200Schema,
);
