/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const unarchiveResponsavelPathParamsSchema = z.object({
  responsavelId: z.uuid(),
});

/**
 * @description Responsável desarquivado com sucesso
 */
export const unarchiveResponsavel204Schema = z.any();

/**
 * @description Responsável não encontrado
 */
export const unarchiveResponsavel404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const unarchiveResponsavel409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const unarchiveResponsavel500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const unarchiveResponsavelMutationResponseSchema = z.lazy(
  () => unarchiveResponsavel204Schema,
);
