/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { responsavelRequestDTOSchema } from "../responsavelRequestDTOSchema.ts";
import { responsavelResponseDTOSchema } from "../responsavelResponseDTOSchema.ts";
import { z } from "zod/v4";

export const updateResponsavelPathParamsSchema = z.object({
  responsavelId: z.uuid(),
});

/**
 * @description Responsável atualizado com sucesso
 */
export const updateResponsavel200Schema = z
  .lazy(() => responsavelResponseDTOSchema)
  .describe("Dados do responsável retornados pela API");

/**
 * @description Falha de validação
 */
export const updateResponsavel400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Responsável não encontrado
 */
export const updateResponsavel404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const updateResponsavel409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const updateResponsavel500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const updateResponsavelMutationRequestSchema = z
  .lazy(() => responsavelRequestDTOSchema)
  .describe("Formato de payload para criar um novo responsável");

export const updateResponsavelMutationResponseSchema = z.lazy(
  () => updateResponsavel200Schema,
);
