/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ArchiveStudentMutationResponse,
  ArchiveStudentPathParams,
} from "../../types/student/ArchiveStudent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const archiveStudentMutationKey = () =>
  [{ url: "/v1/students/:studentId/archive" }] as const;

export type ArchiveStudentMutationKey = ReturnType<
  typeof archiveStudentMutationKey
>;

/**
 * @description Arquiva um aluno por ID.
 * {@link /v1/students/:studentId/archive}
 */
export async function archiveStudent(
  studentId: ArchiveStudentPathParams["studentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ArchiveStudentMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/students/${studentId}/archive`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function archiveStudentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = archiveStudentMutationKey();
  return mutationOptions<
    ArchiveStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { studentId: ArchiveStudentPathParams["studentId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ studentId }) => {
      return archiveStudent(studentId, config);
    },
  });
}

/**
 * @description Arquiva um aluno por ID.
 * {@link /v1/students/:studentId/archive}
 */
export function useArchiveStudent<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ArchiveStudentMutationResponse,
      ResponseErrorConfig<Error>,
      { studentId: ArchiveStudentPathParams["studentId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? archiveStudentMutationKey();

  const baseOptions = archiveStudentMutationOptions(
    config,
  ) as UseMutationOptions<
    ArchiveStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { studentId: ArchiveStudentPathParams["studentId"] },
    TContext
  >;

  return useMutation<
    ArchiveStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { studentId: ArchiveStudentPathParams["studentId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ArchiveStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { studentId: ArchiveStudentPathParams["studentId"] },
    TContext
  >;
}
