/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CreateStudentMutationRequest,
  CreateStudentMutationResponse,
} from "../../types/student/CreateStudent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createStudentMutationKey = () =>
  [{ url: "/v1/students" }] as const;

export type CreateStudentMutationKey = ReturnType<
  typeof createStudentMutationKey
>;

/**
 * @description Cria um novo aluno com os dados fornecidos.
 * {@link /v1/students}
 */
export async function createStudent(
  data: CreateStudentMutationRequest,
  config: Partial<RequestConfig<CreateStudentMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    CreateStudentMutationRequest
  >({
    method: "POST",
    url: `/v1/students`,
    baseURL: `http://localhost:8080`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createStudentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateStudentMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createStudentMutationKey();
  return mutationOptions<
    CreateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateStudentMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createStudent(data, config);
    },
  });
}

/**
 * @description Cria um novo aluno com os dados fornecidos.
 * {@link /v1/students}
 */
export function useCreateStudent<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateStudentMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CreateStudentMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateStudentMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createStudentMutationKey();

  const baseOptions = createStudentMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateStudentMutationRequest },
    TContext
  >;

  return useMutation<
    CreateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateStudentMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateStudentMutationRequest },
    TContext
  >;
}
