/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetStudentsByParentQueryResponse,
  GetStudentsByParentQueryParams,
} from "../../types/student/GetStudentsByParent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getStudentsByParentQueryKey = (
  params: GetStudentsByParentQueryParams,
) =>
  [
    { url: "/v1/students/:parentId", params: { parentId: parentId } },
    ...(params ? [params] : []),
  ] as const;

export type GetStudentsByParentQueryKey = ReturnType<
  typeof getStudentsByParentQueryKey
>;

/**
 * @description Retorna uma lista de alunos pelo ID do pai.
 * {@link /v1/students/:parentId}
 */
export async function getStudentsByParent(
  params: GetStudentsByParentQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetStudentsByParentQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/students/${parentId}`,
    baseURL: `http://localhost:8080`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getStudentsByParentQueryOptions(
  params: GetStudentsByParentQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getStudentsByParentQueryKey(params);
  return queryOptions<
    GetStudentsByParentQueryResponse,
    ResponseErrorConfig<Error>,
    GetStudentsByParentQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return getStudentsByParent(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna uma lista de alunos pelo ID do pai.
 * {@link /v1/students/:parentId}
 */
export function useGetStudentsByParent<
  TData = GetStudentsByParentQueryResponse,
  TQueryData = GetStudentsByParentQueryResponse,
  TQueryKey extends QueryKey = GetStudentsByParentQueryKey,
>(
  params: GetStudentsByParentQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetStudentsByParentQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getStudentsByParentQueryKey(params);

  const query = useQuery(
    {
      ...getStudentsByParentQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
