/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetStudentsByParentQueryResponse,
  GetStudentsByParentPathParams,
} from "../../types/student/GetStudentsByParent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getStudentsByParentQueryKey = (
  parentId: GetStudentsByParentPathParams["parentId"],
) =>
  [
    { url: "/v1/students/students/:parentId", params: { parentId: parentId } },
  ] as const;

export type GetStudentsByParentQueryKey = ReturnType<
  typeof getStudentsByParentQueryKey
>;

/**
 * @description Retorna uma lista de alunos por ID do pai.
 * {@link /v1/students/students/:parentId}
 */
export async function getStudentsByParent(
  parentId: GetStudentsByParentPathParams["parentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetStudentsByParentQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/students/students/${parentId}`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function getStudentsByParentQueryOptions(
  parentId: GetStudentsByParentPathParams["parentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getStudentsByParentQueryKey(parentId);
  return queryOptions<
    GetStudentsByParentQueryResponse,
    ResponseErrorConfig<Error>,
    GetStudentsByParentQueryResponse,
    typeof queryKey
  >({
    enabled: !!parentId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getStudentsByParent(parentId, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna uma lista de alunos por ID do pai.
 * {@link /v1/students/students/:parentId}
 */
export function useGetStudentsByParent<
  TData = GetStudentsByParentQueryResponse,
  TQueryData = GetStudentsByParentQueryResponse,
  TQueryKey extends QueryKey = GetStudentsByParentQueryKey,
>(
  parentId: GetStudentsByParentPathParams["parentId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetStudentsByParentQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getStudentsByParentQueryKey(parentId);

  const query = useQuery(
    {
      ...getStudentsByParentQueryOptions(parentId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
