/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UpdateStudentMutationRequest,
  UpdateStudentMutationResponse,
  UpdateStudentPathParams,
} from "../../types/student/UpdateStudent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateStudentMutationKey = () =>
  [{ url: "/v1/students/:studentId" }] as const;

export type UpdateStudentMutationKey = ReturnType<
  typeof updateStudentMutationKey
>;

/**
 * @description Atualiza um aluno por ID.
 * {@link /v1/students/:studentId}
 */
export async function updateStudent(
  studentId: UpdateStudentPathParams["studentId"],
  data: UpdateStudentMutationRequest,
  config: Partial<RequestConfig<UpdateStudentMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    UpdateStudentMutationRequest
  >({
    method: "PUT",
    url: `/v1/students/${studentId}`,
    baseURL: `http://localhost:8080`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateStudentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateStudentMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updateStudentMutationKey();
  return mutationOptions<
    UpdateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    {
      studentId: UpdateStudentPathParams["studentId"];
      data: UpdateStudentMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ studentId, data }) => {
      return updateStudent(studentId, data, config);
    },
  });
}

/**
 * @description Atualiza um aluno por ID.
 * {@link /v1/students/:studentId}
 */
export function useUpdateStudent<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateStudentMutationResponse,
      ResponseErrorConfig<Error>,
      {
        studentId: UpdateStudentPathParams["studentId"];
        data: UpdateStudentMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateStudentMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateStudentMutationKey();

  const baseOptions = updateStudentMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    {
      studentId: UpdateStudentPathParams["studentId"];
      data: UpdateStudentMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    {
      studentId: UpdateStudentPathParams["studentId"];
      data: UpdateStudentMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateStudentMutationResponse,
    ResponseErrorConfig<Error>,
    {
      studentId: UpdateStudentPathParams["studentId"];
      data: UpdateStudentMutationRequest;
    },
    TContext
  >;
}
