/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Endereço do aluno
 */
export const addressResponseDTOSchema = z
  .object({
    street: z.string(),
    district: z.string(),
    city: z.string(),
    state: z
      .enum([
        "AC",
        "AL",
        "AP",
        "AM",
        "BA",
        "CE",
        "DF",
        "ES",
        "GO",
        "MA",
        "MT",
        "MS",
        "MG",
        "PA",
        "PB",
        "PR",
        "PE",
        "PI",
        "RJ",
        "RN",
        "RS",
        "RO",
        "RR",
        "SC",
        "SP",
        "SE",
        "TO",
      ])
      .describe("Estados Brasileiros"),
    zip: z.string(),
    complement: z.string().nullish(),
  })
  .describe("Endereço do aluno");
