/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Opção simplificada de aluno para seletores
 */
export const alunosListDTOSchema = z
  .object({
    id: z.uuid().describe("Identificador único do aluno"),
    name: z.string().describe("Nome completo do aluno"),
  })
  .describe("Opção simplificada de aluno para seletores");
