/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageDTOAlunoResponseDTOSchema } from "./pageDTOAlunoResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Resumo e listagem paginada de alunos
 */
export const alunosResponseDTOSchema = z
  .object({
    totalActiveStudents: z.optional(z.int().describe("Total de alunos ativos")),
    get alunos() {
      return pageDTOAlunoResponseDTOSchema
        .describe("Estrutura padrao de paginacao da API")
        .optional();
    },
  })
  .describe("Resumo e listagem paginada de alunos");
