/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Resumo financeiro e quantitativo do aluno no periodo
 */
export const alunoAtendimentosKpisSchema = z
  .object({
    totalAtendimentos: z.optional(
      z.int().describe("Total de atendimentos no periodo selecionado"),
    ),
    totalCharged: z.optional(
      z.number().describe("Total cobrado no periodo selecionado"),
    ),
    totalPending: z.optional(
      z.number().describe("Total pendente no periodo selecionado"),
    ),
  })
  .describe("Resumo financeiro e quantitativo do aluno no periodo");
