/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { alunoAtendimentosKpisSchema } from "./alunoAtendimentosKpisSchema.ts";
import { pageDTOAtendimentoResponseDTOSchema } from "./pageDTOAtendimentoResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Agenda paginada e resumo financeiro do aluno no periodo consultado
 */
export const atendimentosAlunoResponseDTOSchema = z
  .object({
    get atendimentos() {
      return pageDTOAtendimentoResponseDTOSchema
        .describe("Estrutura padrao de paginacao da API")
        .optional();
    },
    get summary() {
      return alunoAtendimentosKpisSchema
        .describe("Resumo financeiro e quantitativo do aluno no periodo")
        .optional();
    },
  })
  .describe(
    "Agenda paginada e resumo financeiro do aluno no periodo consultado",
  );
