/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { colaboradorAtendimentosKpisSchema } from "./colaboradorAtendimentosKpisSchema.ts";
import { pageDTOAtendimentoResponseDTOSchema } from "./pageDTOAtendimentoResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Agenda paginada e resumo financeiro do colaborador no periodo consultado
 */
export const atendimentosColaboradorResponseDTOSchema = z
  .object({
    get atendimentos() {
      return pageDTOAtendimentoResponseDTOSchema
        .describe("Estrutura padrao de paginacao da API")
        .optional();
    },
    get summary() {
      return colaboradorAtendimentosKpisSchema
        .describe("Resumo financeiro e quantitativo do colaborador no periodo")
        .optional();
    },
  })
  .describe(
    "Agenda paginada e resumo financeiro do colaborador no periodo consultado",
  );
