/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Resumo financeiro consolidado baseado em atendimentos e despesas gerais
 */
export const atendimentosKpisDTOSchema = z
  .object({
    totalStudentCharged: z.optional(
      z.number().describe("Total cobrado dos alunos no periodo"),
    ),
    totalStudentPending: z.optional(
      z.number().describe("Total pendente de cobranca dos alunos no periodo"),
    ),
    totalEmployeePaid: z.optional(
      z.number().describe("Total pago aos colaboradores no periodo"),
    ),
    totalEmployeePending: z.optional(
      z
        .number()
        .describe("Total pendente de pagamento aos colaboradores no periodo"),
    ),
  })
  .describe(
    "Resumo financeiro consolidado baseado em atendimentos e despesas gerais",
  );
