/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Resumo financeiro de colaborador no periodo
 */
export const atendimentosColaboradorKpisDTOSchema = z
  .object({
    employeeId: z.optional(z.uuid().describe("ID do colaborador")),
    totalAtendimentos: z.optional(
      z.int().describe("Total de atendimentos no periodo"),
    ),
    totalPaid: z.optional(
      z.number().describe("Total pago ao colaborador no periodo"),
    ),
    totalPending: z.optional(
      z
        .number()
        .describe("Total pendente de pagamento ao colaborador no periodo"),
    ),
  })
  .describe("Resumo financeiro de colaborador no periodo");
