/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Resposta de autenticacao com access token JWT
 */
export const authResponseDTOSchema = z
  .object({
    accessToken: z.optional(z.string().describe("JWT de acesso")),
    expiresIn: z.optional(z.int().describe("Tempo de expiração em segundos")),
    username: z.optional(z.string().describe("E-mail do usuário autenticado")),
    role: z.optional(
      z
        .enum(["STUDENT", "EMPLOYEE", "PARENT", "ADMIN"])
        .describe("Perfil de acesso do usuário autenticado"),
    ),
  })
  .describe("Resposta de autenticacao com access token JWT");
