/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Dados do usuário autenticado
 */
export const authCurrentUserResponseDTOSchema = z
  .object({
    id: z.uuid(),
    username: z.string(),
    displayName: z.string(),
    email: z.string(),
    employeeId: z.uuid(),
    duty: z.enum(["TEACHER", "ADM", "THERAPIST", "MENTOR", "SYSTEM"]),
  })
  .describe("Dados do usuário autenticado");
