/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Payload de autenticacao
 */
export const authRequestDTOSchema = z
  .object({
    email: z.string().min(1).describe("E-mail usado no login"),
    password: z.string().min(1).describe("Senha do usuário"),
  })
  .describe("Payload de autenticacao");
