/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const classesByContentDTOSchema = z.object({
  content: z.optional(z.string()),
  count: z.optional(z.int()),
  percentage: z.optional(z.number()),
});
