/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addressResponseDTOSchema } from "./addressResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Dados do colaborador retornados pela API
 */
export const colaboradorResponseDTOSchema = z
  .object({
    id: z.uuid().describe("Identificador unico do colaborador"),
    name: z.string().describe("Nome completo do colaborador"),
    birthdate: z.iso.date().describe("Data de nascimento do colaborador"),
    pix: z.string().describe("Chave PIX do colaborador"),
    contact: z.string().describe("Telefone de contato do colaborador"),
    cpf: z.string().describe("CPF do colaborador"),
    email: z.string().describe("Email do colaborador"),
    duty: z
      .enum(["TEACHER", "ADM", "THERAPIST", "MENTOR", "SYSTEM"])
      .describe("Função/Papel do funcionário"),
    get address() {
      return addressResponseDTOSchema.describe("Endereço");
    },
    active: z.optional(
      z.boolean().describe("Indica se o colaborador esta ativo"),
    ),
    createdAt: z.iso.datetime().describe("Data de criacao do colaborador"),
    updatedAt: z.iso
      .datetime()
      .describe("Data da ultima atualizacao do colaborador")
      .nullish(),
  })
  .describe("Dados do colaborador retornados pela API");
