/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Formato de payload para obter opções de colaboradores
 */
export const colaboradoresKpisDTOSchema = z
  .object({
    totalColaboradores: z.optional(z.int().describe("ID do funcionário")),
    totalColaboradoresAtivos: z.optional(
      z.int().describe("Total de colaboradores ativos"),
    ),
  })
  .describe("Formato de payload para obter opções de colaboradores");
