/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { classesByContentDTOSchema } from "./classesByContentDTOSchema.ts";
import { z } from "zod/v4";

export const dashboardSummaryResponseDTOSchema = z.object({
  year: z.optional(z.int()),
  month: z.optional(z.int()),
  prevYear: z.optional(z.int()),
  prevMonth: z.optional(z.int()),
  nextYear: z.optional(z.int()),
  nextMonth: z.optional(z.int()),
  classesInMonth: z.optional(z.int()),
  get charts() {
    return z.array(classesByContentDTOSchema).optional();
  },
  generatedAt: z.optional(z.iso.datetime()),
  refreshSeconds: z.optional(z.int()),
});
