/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageDTODespesaResponseDTOSchema } from "./pageDTODespesaResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Despesas paginadas e resumo financeiro do periodo consultado
 */
export const despesasResponseDTOSchema = z
  .object({
    totalExpenses: z.optional(
      z.number().describe("Total de despesas gerais no periodo"),
    ),
    pendingExpenses: z.optional(
      z
        .number()
        .describe("Total de despesas gerais pendentes de pagamento no periodo"),
    ),
    get expenses() {
      return pageDTODespesaResponseDTOSchema
        .describe("Estrutura padrao de paginacao da API")
        .optional();
    },
  })
  .describe("Despesas paginadas e resumo financeiro do periodo consultado");
