/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Payload para criacao ou atualizacao de despesa
 */
export const despesaRequestDTOSchema = z
  .object({
    amount: z.number().describe("Valor da despesa"),
    date: z.iso.datetime().describe("Data de competencia da despesa"),
    category: z
      .enum([
        "CONTAS",
        "ADMINISTRATIVO",
        "DESPENSA",
        "MANUTENCAO",
        "SERVICOS",
        "MATERIAIS",
        "ASSINATURAS",
      ])
      .describe("Categoria da despesa geral"),
    description: z.string().min(1).describe("Descricao da despesa"),
  })
  .describe("Payload para criacao ou atualizacao de despesa");
