/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addressRequestDTOSchema } from "./addressRequestDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Formato de payload para criar um novo colaborador
 */
export const employeeRequestDTOSchema = z
  .object({
    name: z.string().min(1),
    birthdate: z.iso.date(),
    pix: z.string().min(1),
    contact: z.string().min(1),
    cpf: z.string().min(1),
    email: z.string().min(1),
    duty: z
      .enum(["TEACHER", "ADM", "THERAPIST", "MENTOR", "SYSTEM"])
      .describe("Função/Papel do funcionário"),
    get address() {
      return addressRequestDTOSchema.describe("Endereço");
    },
  })
  .describe("Formato de payload para criar um novo colaborador");
