/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addressResponseDTOSchema } from "./addressResponseDTOSchema.ts";
import { z } from "zod/v4";

export const employeeResponseDTOSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  birthdate: z.iso.date(),
  pix: z.string(),
  contact: z.string(),
  cpf: z.string(),
  email: z.string(),
  duty: z
    .enum(["TEACHER", "ADM", "THERAPIST", "MENTOR", "SYSTEM"])
    .describe("Função/Papel do funcionário"),
  get address() {
    return addressResponseDTOSchema.describe("Endereço");
  },
  active: z.boolean().nullish(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime().nullish(),
});
