/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Formato de payload para o cadastro e/ou update de um evento
 */
export const eventRequestDTOSchema = z
  .object({
    description: z.optional(z.string().describe("Descrição do evento")),
    content: z
      .enum([
        "AULA",
        "MENTORIA",
        "TERAPIA",
        "ORIENTACAO_VOCACIONAL",
        "ENEM",
        "PAS",
        "OUTRO",
      ])
      .describe("Tipo de conteúdo ou categoria do atendimento/evento"),
    startDate: z.iso.datetime().describe("Data/Horário de início do evento"),
    endDate: z.iso.datetime().describe("Data/Horário de fim do evento"),
    price: z.number().describe("Preço do evento pago pelo aluno"),
    payment: z.number().describe("Preço do evento pago ao colaborador"),
    studentId: z.uuid().describe("ID do estudante vinculado ao evento"),
    employeeId: z.uuid().describe("ID do colaborador vinculado ao evento"),
  })
  .describe("Formato de payload para o cadastro e/ou update de um evento");
