/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { studentResponseDTOSchema } from "./studentResponseDTOSchema.ts";
import { z } from "zod/v4";

export const pageDTOStudentResponseDTOSchema = z.object({
  page: z.int().describe("Número da página atual"),
  size: z.int().describe("Tamanho da página"),
  totalElements: z.int().describe("Total de elementos"),
  totalPages: z.int().describe("Total de páginas"),
  get content() {
    return z
      .array(
        studentResponseDTOSchema.describe("Dados do aluno retornados pela API"),
      )
      .describe("Lista de elementos");
  },
});
