/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { employeeResponseDTOSchema } from "./employeeResponseDTOSchema.ts";
import { z } from "zod/v4";

export const pageDTOEmployeeResponseDTOSchema = z.object({
  page: z.int().describe("Número da página atual"),
  size: z.int().describe("Tamanho da página"),
  totalElements: z.int().describe("Total de elementos"),
  totalPages: z.int().describe("Total de páginas"),
  get content() {
    return z.array(employeeResponseDTOSchema).describe("Lista de elementos");
  },
});
