/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { atendimentosColaboradorKpisDTOSchema } from "./atendimentosColaboradorKpisDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Estrutura padrao de paginacao da API
 */
export const pageDTOAtendimentosColaboradorKpisDTOSchema = z
  .object({
    page: z.int().describe("Número da página atual"),
    size: z.int().describe("Tamanho da página"),
    totalElements: z.int().describe("Total de elementos"),
    totalPages: z.int().describe("Total de páginas"),
    get content() {
      return z
        .array(
          atendimentosColaboradorKpisDTOSchema.describe(
            "Resumo financeiro de colaborador no periodo",
          ),
        )
        .describe("Lista de elementos da pagina");
    },
  })
  .describe("Estrutura padrao de paginacao da API");
