/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { responsavelResponseDTOSchema } from "./responsavelResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Estrutura padrao de paginacao da API
 */
export const pageDTOResponsavelResponseDTOSchema = z
  .object({
    page: z.int().describe("Número da página atual"),
    size: z.int().describe("Tamanho da página"),
    totalElements: z.int().describe("Total de elementos"),
    totalPages: z.int().describe("Total de páginas"),
    get content() {
      return z
        .array(
          responsavelResponseDTOSchema.describe(
            "Dados do responsável retornados pela API",
          ),
        )
        .describe("Lista de elementos da pagina");
    },
  })
  .describe("Estrutura padrao de paginacao da API");
