/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Lista de responsáveis para dropdown retornados da API
 */
export const parentOptionsDTOSchema = z
  .object({
    id: z.uuid().describe("Identificador único do responsável"),
    name: z.string().describe("Nome do responsável"),
  })
  .describe("Lista de responsáveis para dropdown retornados da API");
