/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Dados do responsável retornados pela API
 */
export const parentResponseDTOSchema = z
  .object({
    parentId: z.uuid().describe("ID do responsável"),
    name: z.string().describe("Nome do responsável"),
    email: z.string().describe("Email do responsável"),
    contact: z.string().describe("Contato do responsável"),
    cpf: z.string().describe("CPF do responsável"),
    archivedAt: z.iso
      .datetime()
      .describe("Data e hora quando o aluno foi arquivado")
      .nullish(),
    createdAt: z.iso
      .datetime()
      .describe("Data e hora quando o aluno foi criado"),
    updatedAt: z.iso
      .datetime()
      .describe("Data e hora quando o aluno foi atualizado")
      .nullish(),
  })
  .describe("Dados do responsável retornados pela API");
