/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Formato de payload para criar um novo responsável
 */
export const parentCreateDTOSchema = z
  .object({
    name: z.string().min(1).describe("Nome do responsável"),
    email: z.string().min(1).describe("Email do responsável"),
    contact: z.string().min(1).describe("Contato do responsável"),
    cpf: z.string().min(1).describe("CPF do responsável"),
  })
  .describe("Formato de payload para criar um novo responsável");
