/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Payload para criacao de usuario
 */
export const userRequestDTOSchema = z
  .object({
    username: z.string().min(1).describe("E-mail usado no login"),
    password: z.string().min(1).describe("Senha"),
    role: z
      .enum(["STUDENT", "EMPLOYEE", "PARENT", "ADMIN"])
      .describe("Perfil de acesso"),
  })
  .describe("Payload para criacao de usuario");
