/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthCurrentUserResponseDTO } from "../AuthCurrentUserResponseDTO.ts";

/**
 * @description OK
 */
export type Me200 = AuthCurrentUserResponseDTO;

export type MeQueryResponse = Me200;

export type MeQuery = {
  Response: Me200;
  Errors: any;
};
