/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ArchiveAlunoMutationResponse, ArchiveAlunoPathParams } from "../../types/aluno/ArchiveAluno.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const archiveAlunoMutationKey = () => [{ url: '/v1/alunos/:alunoId/archive' }] as const

export type ArchiveAlunoMutationKey = ReturnType<typeof archiveAlunoMutationKey>

/**
 * @description Arquiva um aluno por ID.
 * {@link /v1/alunos/:alunoId/archive}
 */
export async function archiveAluno(alunoId: ArchiveAlunoPathParams["alunoId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ArchiveAlunoMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "PATCH", url : `/v1/alunos/${alunoId}/archive`, ... requestConfig })  
  return res.data
}

export function archiveAlunoMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = archiveAlunoMutationKey()
  return mutationOptions<ArchiveAlunoMutationResponse, ResponseErrorConfig<Error>, {alunoId: ArchiveAlunoPathParams["alunoId"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ alunoId }) => {
      return archiveAluno(alunoId, config)
    },
  })
}

/**
 * @description Arquiva um aluno por ID.
 * {@link /v1/alunos/:alunoId/archive}
 */
export function useArchiveAluno<TContext>(options: 
{
  mutation?: UseMutationOptions<ArchiveAlunoMutationResponse, ResponseErrorConfig<Error>, {alunoId: ArchiveAlunoPathParams["alunoId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? archiveAlunoMutationKey()

  const baseOptions = archiveAlunoMutationOptions(config) as UseMutationOptions<ArchiveAlunoMutationResponse, ResponseErrorConfig<Error>, {alunoId: ArchiveAlunoPathParams["alunoId"]}, TContext>

  return useMutation<ArchiveAlunoMutationResponse, ResponseErrorConfig<Error>, {alunoId: ArchiveAlunoPathParams["alunoId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ArchiveAlunoMutationResponse, ResponseErrorConfig<Error>, {alunoId: ArchiveAlunoPathParams["alunoId"]}, TContext>
}