/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  AtualizarAlunoMutationRequest,
  AtualizarAlunoMutationResponse,
  AtualizarAlunoPathParams,
  AtualizarAluno400,
  AtualizarAluno404,
  AtualizarAluno409,
  AtualizarAluno500,
} from "../../types/aluno/AtualizarAluno.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const atualizarAlunoMutationKey = () =>
  [{ url: "/v1/alunos/:studentId" }] as const;

export type AtualizarAlunoMutationKey = ReturnType<
  typeof atualizarAlunoMutationKey
>;

/**
 * @description Atualiza um aluno por ID.
 * {@link /v1/alunos/:studentId}
 */
export async function atualizarAluno(
  studentId: AtualizarAlunoPathParams["studentId"],
  data: AtualizarAlunoMutationRequest,
  config: Partial<RequestConfig<AtualizarAlunoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AtualizarAlunoMutationResponse,
    ResponseErrorConfig<
      | AtualizarAluno400
      | AtualizarAluno404
      | AtualizarAluno409
      | AtualizarAluno500
    >,
    AtualizarAlunoMutationRequest
  >({
    method: "PUT",
    url: `/v1/alunos/${studentId}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function atualizarAlunoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AtualizarAlunoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = atualizarAlunoMutationKey();
  return mutationOptions<
    AtualizarAlunoMutationResponse,
    ResponseErrorConfig<
      | AtualizarAluno400
      | AtualizarAluno404
      | AtualizarAluno409
      | AtualizarAluno500
    >,
    {
      studentId: AtualizarAlunoPathParams["studentId"];
      data: AtualizarAlunoMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ studentId, data }) => {
      return atualizarAluno(studentId, data, config);
    },
  });
}

/**
 * @description Atualiza um aluno por ID.
 * {@link /v1/alunos/:studentId}
 */
export function useAtualizarAluno<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AtualizarAlunoMutationResponse,
      ResponseErrorConfig<
        | AtualizarAluno400
        | AtualizarAluno404
        | AtualizarAluno409
        | AtualizarAluno500
      >,
      {
        studentId: AtualizarAlunoPathParams["studentId"];
        data: AtualizarAlunoMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AtualizarAlunoMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? atualizarAlunoMutationKey();

  const baseOptions = atualizarAlunoMutationOptions(
    config,
  ) as UseMutationOptions<
    AtualizarAlunoMutationResponse,
    ResponseErrorConfig<
      | AtualizarAluno400
      | AtualizarAluno404
      | AtualizarAluno409
      | AtualizarAluno500
    >,
    {
      studentId: AtualizarAlunoPathParams["studentId"];
      data: AtualizarAlunoMutationRequest;
    },
    TContext
  >;

  return useMutation<
    AtualizarAlunoMutationResponse,
    ResponseErrorConfig<
      | AtualizarAluno400
      | AtualizarAluno404
      | AtualizarAluno409
      | AtualizarAluno500
    >,
    {
      studentId: AtualizarAlunoPathParams["studentId"];
      data: AtualizarAlunoMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AtualizarAlunoMutationResponse,
    ResponseErrorConfig<
      | AtualizarAluno400
      | AtualizarAluno404
      | AtualizarAluno409
      | AtualizarAluno500
    >,
    {
      studentId: AtualizarAlunoPathParams["studentId"];
      data: AtualizarAlunoMutationRequest;
    },
    TContext
  >;
}
