/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ArquivarAlunoMutationResponse,
  ArquivarAlunoPathParams,
  ArquivarAluno404,
  ArquivarAluno409,
  ArquivarAluno500,
} from "../../types/aluno/ArquivarAluno.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const arquivarAlunoMutationKey = () =>
  [{ url: "/v1/alunos/:studentId/archive" }] as const;

export type ArquivarAlunoMutationKey = ReturnType<
  typeof arquivarAlunoMutationKey
>;

/**
 * @description Arquiva um aluno por ID.
 * {@link /v1/alunos/:studentId/archive}
 */
export async function arquivarAluno(
  studentId: ArquivarAlunoPathParams["studentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ArquivarAlunoMutationResponse,
    ResponseErrorConfig<ArquivarAluno404 | ArquivarAluno409 | ArquivarAluno500>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/alunos/${studentId}/archive`,
    ...requestConfig,
  });
  return res.data;
}

export function arquivarAlunoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = arquivarAlunoMutationKey();
  return mutationOptions<
    ArquivarAlunoMutationResponse,
    ResponseErrorConfig<ArquivarAluno404 | ArquivarAluno409 | ArquivarAluno500>,
    { studentId: ArquivarAlunoPathParams["studentId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ studentId }) => {
      return arquivarAluno(studentId, config);
    },
  });
}

/**
 * @description Arquiva um aluno por ID.
 * {@link /v1/alunos/:studentId/archive}
 */
export function useArquivarAluno<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ArquivarAlunoMutationResponse,
      ResponseErrorConfig<
        ArquivarAluno404 | ArquivarAluno409 | ArquivarAluno500
      >,
      { studentId: ArquivarAlunoPathParams["studentId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? arquivarAlunoMutationKey();

  const baseOptions = arquivarAlunoMutationOptions(
    config,
  ) as UseMutationOptions<
    ArquivarAlunoMutationResponse,
    ResponseErrorConfig<ArquivarAluno404 | ArquivarAluno409 | ArquivarAluno500>,
    { studentId: ArquivarAlunoPathParams["studentId"] },
    TContext
  >;

  return useMutation<
    ArquivarAlunoMutationResponse,
    ResponseErrorConfig<ArquivarAluno404 | ArquivarAluno409 | ArquivarAluno500>,
    { studentId: ArquivarAlunoPathParams["studentId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ArquivarAlunoMutationResponse,
    ResponseErrorConfig<ArquivarAluno404 | ArquivarAluno409 | ArquivarAluno500>,
    { studentId: ArquivarAlunoPathParams["studentId"] },
    TContext
  >;
}
