/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CriarAlunoMutationRequest,
  CriarAlunoMutationResponse,
} from "../../types/aluno/CriarAluno.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const criarAlunoMutationKey = () => [{ url: "/v1/alunos" }] as const;

export type CriarAlunoMutationKey = ReturnType<typeof criarAlunoMutationKey>;

/**
 * @description Cria um novo aluno com os dados fornecidos.
 * {@link /v1/alunos}
 */
export async function criarAluno(
  data: CriarAlunoMutationRequest,
  config: Partial<RequestConfig<CriarAlunoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CriarAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    CriarAlunoMutationRequest
  >({ method: "POST", url: `/v1/alunos`, data: requestData, ...requestConfig });
  return res.data;
}

export function criarAlunoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CriarAlunoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = criarAlunoMutationKey();
  return mutationOptions<
    CriarAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CriarAlunoMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return criarAluno(data, config);
    },
  });
}

/**
 * @description Cria um novo aluno com os dados fornecidos.
 * {@link /v1/alunos}
 */
export function useCriarAluno<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CriarAlunoMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CriarAlunoMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CriarAlunoMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? criarAlunoMutationKey();

  const baseOptions = criarAlunoMutationOptions(config) as UseMutationOptions<
    CriarAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CriarAlunoMutationRequest },
    TContext
  >;

  return useMutation<
    CriarAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CriarAlunoMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CriarAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CriarAlunoMutationRequest },
    TContext
  >;
}
