/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DesarquivarAlunoMutationResponse,
  DesarquivarAlunoPathParams,
  DesarquivarAluno404,
  DesarquivarAluno409,
  DesarquivarAluno500,
} from "../../types/aluno/DesarquivarAluno.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const desarquivarAlunoMutationKey = () =>
  [{ url: "/v1/alunos/:studentId/unarchive" }] as const;

export type DesarquivarAlunoMutationKey = ReturnType<
  typeof desarquivarAlunoMutationKey
>;

/**
 * @description Desarquiva um aluno por ID.
 * {@link /v1/alunos/:studentId/unarchive}
 */
export async function desarquivarAluno(
  studentId: DesarquivarAlunoPathParams["studentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DesarquivarAlunoMutationResponse,
    ResponseErrorConfig<
      DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500
    >,
    unknown
  >({
    method: "PATCH",
    url: `/v1/alunos/${studentId}/unarchive`,
    ...requestConfig,
  });
  return res.data;
}

export function desarquivarAlunoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = desarquivarAlunoMutationKey();
  return mutationOptions<
    DesarquivarAlunoMutationResponse,
    ResponseErrorConfig<
      DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500
    >,
    { studentId: DesarquivarAlunoPathParams["studentId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ studentId }) => {
      return desarquivarAluno(studentId, config);
    },
  });
}

/**
 * @description Desarquiva um aluno por ID.
 * {@link /v1/alunos/:studentId/unarchive}
 */
export function useDesarquivarAluno<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DesarquivarAlunoMutationResponse,
      ResponseErrorConfig<
        DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500
      >,
      { studentId: DesarquivarAlunoPathParams["studentId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? desarquivarAlunoMutationKey();

  const baseOptions = desarquivarAlunoMutationOptions(
    config,
  ) as UseMutationOptions<
    DesarquivarAlunoMutationResponse,
    ResponseErrorConfig<
      DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500
    >,
    { studentId: DesarquivarAlunoPathParams["studentId"] },
    TContext
  >;

  return useMutation<
    DesarquivarAlunoMutationResponse,
    ResponseErrorConfig<
      DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500
    >,
    { studentId: DesarquivarAlunoPathParams["studentId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DesarquivarAlunoMutationResponse,
    ResponseErrorConfig<
      DesarquivarAluno404 | DesarquivarAluno409 | DesarquivarAluno500
    >,
    { studentId: DesarquivarAlunoPathParams["studentId"] },
    TContext
  >;
}
