/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteAlunoMutationResponse,
  DeleteAlunoPathParams,
} from "../../types/aluno/DeleteAluno.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteAlunoMutationKey = () =>
  [{ url: "/v1/alunos/:alunoId" }] as const;

export type DeleteAlunoMutationKey = ReturnType<typeof deleteAlunoMutationKey>;

/**
 * @description Deleta um aluno por ID.
 * {@link /v1/alunos/:alunoId}
 */
export async function deleteAluno(
  alunoId: DeleteAlunoPathParams["alunoId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "DELETE", url: `/v1/alunos/${alunoId}`, ...requestConfig });
  return res.data;
}

export function deleteAlunoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteAlunoMutationKey();
  return mutationOptions<
    DeleteAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: DeleteAlunoPathParams["alunoId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ alunoId }) => {
      return deleteAluno(alunoId, config);
    },
  });
}

/**
 * @description Deleta um aluno por ID.
 * {@link /v1/alunos/:alunoId}
 */
export function useDeleteAluno<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteAlunoMutationResponse,
      ResponseErrorConfig<Error>,
      { alunoId: DeleteAlunoPathParams["alunoId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteAlunoMutationKey();

  const baseOptions = deleteAlunoMutationOptions(config) as UseMutationOptions<
    DeleteAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: DeleteAlunoPathParams["alunoId"] },
    TContext
  >;

  return useMutation<
    DeleteAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: DeleteAlunoPathParams["alunoId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: DeleteAlunoPathParams["alunoId"] },
    TContext
  >;
}
