/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetAlunosQueryResponse,
  GetAlunosQueryParams,
} from "../../types/aluno/GetAlunos.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAlunosQueryKey = (params?: GetAlunosQueryParams) =>
  [{ url: "/v1/alunos" }, ...(params ? [params] : [])] as const;

export type GetAlunosQueryKey = ReturnType<typeof getAlunosQueryKey>;

/**
 * @description Retorna uma lista paginada de alunos.
 * {@link /v1/alunos}
 */
export async function getAlunos(
  params?: GetAlunosQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAlunosQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/alunos`, params, ...requestConfig });
  return res.data;
}

export function getAlunosQueryOptions(
  params?: GetAlunosQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getAlunosQueryKey(params);
  return queryOptions<
    GetAlunosQueryResponse,
    ResponseErrorConfig<Error>,
    GetAlunosQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getAlunos(params, config);
    },
  });
}

/**
 * @description Retorna uma lista paginada de alunos.
 * {@link /v1/alunos}
 */
export function useGetAlunos<
  TData = GetAlunosQueryResponse,
  TQueryData = GetAlunosQueryResponse,
  TQueryKey extends QueryKey = GetAlunosQueryKey,
>(
  params?: GetAlunosQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAlunosQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getAlunosQueryKey(params);

  const query = useQuery(
    {
      ...getAlunosQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
