/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetAlunosByResponsavelQueryResponse,
  GetAlunosByResponsavelPathParams,
  GetAlunosByResponsavel500,
} from "../../types/aluno/GetAlunosByResponsavel.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAlunosByResponsavelQueryKey = (
  parentId: GetAlunosByResponsavelPathParams["parentId"] | undefined,
) =>
  [
    { url: "/v1/alunos/responsavel/:parentId", params: { parentId: parentId } },
  ] as const;

export type GetAlunosByResponsavelQueryKey = ReturnType<
  typeof getAlunosByResponsavelQueryKey
>;

/**
 * @description Retorna uma lista de alunos pelo ID do responsável.
 * {@link /v1/alunos/responsavel/:parentId}
 */
export async function getAlunosByResponsavel(
  parentId: GetAlunosByResponsavelPathParams["parentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAlunosByResponsavelQueryResponse,
    ResponseErrorConfig<GetAlunosByResponsavel500>,
    unknown
  >({
    method: "GET",
    url: `/v1/alunos/responsavel/${parentId}`,
    ...requestConfig,
  });
  return res.data;
}

export function getAlunosByResponsavelQueryOptions(
  parentId: GetAlunosByResponsavelPathParams["parentId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAlunosByResponsavelQueryKey(parentId);
  return queryOptions<
    GetAlunosByResponsavelQueryResponse,
    ResponseErrorConfig<GetAlunosByResponsavel500>,
    GetAlunosByResponsavelQueryResponse,
    typeof queryKey
  >({
    enabled: !!parentId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getAlunosByResponsavel(parentId!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna uma lista de alunos pelo ID do responsável.
 * {@link /v1/alunos/responsavel/:parentId}
 */
export function useGetAlunosByResponsavel<
  TData = GetAlunosByResponsavelQueryResponse,
  TQueryData = GetAlunosByResponsavelQueryResponse,
  TQueryKey extends QueryKey = GetAlunosByResponsavelQueryKey,
>(
  parentId: GetAlunosByResponsavelPathParams["parentId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAlunosByResponsavelQueryResponse,
        ResponseErrorConfig<GetAlunosByResponsavel500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getAlunosByResponsavelQueryKey(parentId);

  const query = useQuery(
    {
      ...getAlunosByResponsavelQueryOptions(parentId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetAlunosByResponsavel500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
