/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type { GetAlunosKpisQueryResponse } from "../../types/GetAlunosKpis.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAlunosKpisQueryKey = () =>
  [{ url: "/v1/alunos/kpis" }] as const;

export type GetAlunosKpisQueryKey = ReturnType<typeof getAlunosKpisQueryKey>;

/**
 * @description Retorna os KPIs de alunos.
 * {@link /v1/alunos/kpis}
 */
export async function getAlunosKpis(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAlunosKpisQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/alunos/kpis`, ...requestConfig });
  return res.data;
}

export function getAlunosKpisQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getAlunosKpisQueryKey();
  return queryOptions<
    GetAlunosKpisQueryResponse,
    ResponseErrorConfig<Error>,
    GetAlunosKpisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getAlunosKpis(config);
    },
  });
}

/**
 * @description Retorna os KPIs de alunos.
 * {@link /v1/alunos/kpis}
 */
export function useGetAlunosKpis<
  TData = GetAlunosKpisQueryResponse,
  TQueryData = GetAlunosKpisQueryResponse,
  TQueryKey extends QueryKey = GetAlunosKpisQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAlunosKpisQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getAlunosKpisQueryKey();

  const query = useQuery(
    {
      ...getAlunosKpisQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
