/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetAlunosByResponsavelQueryResponse,
  GetAlunosByResponsavelPathParams,
} from "../../types/aluno/GetAlunosByResponsavel.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAlunosByResponsavelQueryKey = (
  responsavelId: GetAlunosByResponsavelPathParams["responsavelId"],
) =>
  [
    {
      url: "/v1/alunos/responsavel/:responsavelId",
      params: { responsavelId: responsavelId },
    },
  ] as const;

export type GetAlunosByResponsavelQueryKey = ReturnType<
  typeof getAlunosByResponsavelQueryKey
>;

/**
 * @description Retorna uma lista de alunos pelo ID do responsável.
 * {@link /v1/alunos/responsavel/:responsavelId}
 */
export async function getAlunosByResponsavel(
  responsavelId: GetAlunosByResponsavelPathParams["responsavelId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAlunosByResponsavelQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/alunos/responsavel/${responsavelId}`,
    ...requestConfig,
  });
  return res.data;
}

export function getAlunosByResponsavelQueryOptions(
  responsavelId: GetAlunosByResponsavelPathParams["responsavelId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getAlunosByResponsavelQueryKey(responsavelId);
  return queryOptions<
    GetAlunosByResponsavelQueryResponse,
    ResponseErrorConfig<Error>,
    GetAlunosByResponsavelQueryResponse,
    typeof queryKey
  >({
    enabled: !!responsavelId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getAlunosByResponsavel(responsavelId, config);
    },
  });
}

/**
 * @description Retorna uma lista de alunos pelo ID do responsável.
 * {@link /v1/alunos/responsavel/:responsavelId}
 */
export function useGetAlunosByResponsavel<
  TData = GetAlunosByResponsavelQueryResponse,
  TQueryData = GetAlunosByResponsavelQueryResponse,
  TQueryKey extends QueryKey = GetAlunosByResponsavelQueryKey,
>(
  responsavelId: GetAlunosByResponsavelPathParams["responsavelId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAlunosByResponsavelQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getAlunosByResponsavelQueryKey(responsavelId);

  const query = useQuery(
    {
      ...getAlunosByResponsavelQueryOptions(responsavelId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
