/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type { ListAlunosQueryResponse } from "../../types/ListAlunos.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listAlunosQueryKey = () =>
  [{ url: "/v1/alunos/options" }] as const;

export type ListAlunosQueryKey = ReturnType<typeof listAlunosQueryKey>;

/**
 * @description Retorna uma lista de opções de alunos.
 * {@link /v1/alunos/options}
 */
export async function listAlunos(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListAlunosQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/alunos/options`, ...requestConfig });
  return res.data;
}

export function listAlunosQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = listAlunosQueryKey();
  return queryOptions<
    ListAlunosQueryResponse,
    ResponseErrorConfig<Error>,
    ListAlunosQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listAlunos(config);
    },
  });
}

/**
 * @description Retorna uma lista de opções de alunos.
 * {@link /v1/alunos/options}
 */
export function useListAlunos<
  TData = ListAlunosQueryResponse,
  TQueryData = ListAlunosQueryResponse,
  TQueryKey extends QueryKey = ListAlunosQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListAlunosQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listAlunosQueryKey();

  const query = useQuery(
    {
      ...listAlunosQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
