/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type {
  UnarchiveAlunoMutationResponse,
  UnarchiveAlunoPathParams,
} from "../../types/UnarchiveAluno.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const unarchiveAlunoMutationKey = () =>
  [{ url: "/v1/alunos/:alunoId/unarchive" }] as const;

export type UnarchiveAlunoMutationKey = ReturnType<
  typeof unarchiveAlunoMutationKey
>;

/**
 * @description Desarquiva um aluno por ID.
 * {@link /v1/alunos/:alunoId/unarchive}
 */
export async function unarchiveAluno(
  alunoId: UnarchiveAlunoPathParams["alunoId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    UnarchiveAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/alunos/${alunoId}/unarchive`,
    ...requestConfig,
  });
  return res.data;
}

export function unarchiveAlunoMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = unarchiveAlunoMutationKey();
  return mutationOptions<
    UnarchiveAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: UnarchiveAlunoPathParams["alunoId"] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ alunoId }) => {
      return unarchiveAluno(alunoId, config);
    },
  });
}

/**
 * @description Desarquiva um aluno por ID.
 * {@link /v1/alunos/:alunoId/unarchive}
 */
export function useUnarchiveAluno<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UnarchiveAlunoMutationResponse,
      ResponseErrorConfig<Error>,
      { alunoId: UnarchiveAlunoPathParams["alunoId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? unarchiveAlunoMutationKey();

  const baseOptions = unarchiveAlunoMutationOptions(
    config,
  ) as UseMutationOptions<
    UnarchiveAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: UnarchiveAlunoPathParams["alunoId"] },
    TContext
  >;

  return useMutation<
    UnarchiveAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: UnarchiveAlunoPathParams["alunoId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UnarchiveAlunoMutationResponse,
    ResponseErrorConfig<Error>,
    { alunoId: UnarchiveAlunoPathParams["alunoId"] },
    TContext
  >;
}
