/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { userResponseDTOSchema } from "../userResponseDTOSchema.ts";
import { z } from "zod/v4";

export const archiveUserPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Status ativo alternado com sucesso
 */
export const archiveUser200Schema = z
  .lazy(() => userResponseDTOSchema)
  .describe("Dados do usuario retornados pela API");

/**
 * @description Usuario nao encontrado
 */
export const archiveUser404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const archiveUser500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const archiveUserMutationResponseSchema = z.lazy(
  () => archiveUser200Schema,
);
