/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { userRequestDTOSchema } from "../userRequestDTOSchema.ts";
import { userResponseDTOSchema } from "../userResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Usuario criado com sucesso
 */
export const createUser201Schema = z
  .lazy(() => userResponseDTOSchema)
  .describe("Dados do usuario retornados pela API");

/**
 * @description Falha de validação
 */
export const createUser400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const createUser409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const createUser500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const createUserMutationRequestSchema = z
  .lazy(() => userRequestDTOSchema)
  .describe("Payload para criacao de usuario");

export const createUserMutationResponseSchema = z.lazy(
  () => createUser201Schema,
);
