/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const deleteUserPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Usuario excluido com sucesso
 */
export const deleteUser204Schema = z.any();

/**
 * @description Usuario nao encontrado
 */
export const deleteUser404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const deleteUser500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const deleteUserMutationResponseSchema = z.lazy(
  () => deleteUser204Schema,
);
