/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DespesaRequestDTO } from "../DespesaRequestDTO.ts";
import type { DespesaResponseDTO } from "../DespesaResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

/**
 * @description Despesa criada com sucesso.
 */
export type CreateDespesa201 = DespesaResponseDTO;

/**
 * @description Falha de validação
 */
export type CreateDespesa400 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type CreateDespesa409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type CreateDespesa500 = ProblemResponseDTO;

export type CreateDespesaMutationRequest = DespesaRequestDTO;

export type CreateDespesaMutationResponse = CreateDespesa201;

export type CreateDespesaMutation = {
  Response: CreateDespesa201;
  Request: CreateDespesaMutationRequest;
  Errors: CreateDespesa400 | CreateDespesa409 | CreateDespesa500;
};
