/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DespesasResponseDTO } from "../DespesasResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export const getDespesasQueryParamsCategoriaEnum = {
  CONTAS: "CONTAS",
  ADMINISTRATIVO: "ADMINISTRATIVO",
  DESPENSA: "DESPENSA",
  MANUTENCAO: "MANUTENCAO",
  SERVICOS: "SERVICOS",
  MATERIAIS: "MATERIAIS",
  ASSINATURAS: "ASSINATURAS",
} as const;

export type GetDespesasQueryParamsCategoriaEnumKey =
  (typeof getDespesasQueryParamsCategoriaEnum)[keyof typeof getDespesasQueryParamsCategoriaEnum];

export type GetDespesasQueryParams = {
  /**
   * @description Categoria da despesa geral
   * @type string | undefined
   */
  categoria?: GetDespesasQueryParamsCategoriaEnumKey;
  /**
   * @type string | undefined, date-time
   */
  startDate?: string;
  /**
   * @type string | undefined, date-time
   */
  endDate?: string;
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
};

/**
 * @description Despesas e resumo financeiro retornados com sucesso.
 */
export type GetDespesas200 = DespesasResponseDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetDespesas400 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetDespesas500 = ProblemResponseDTO;

export type GetDespesasQueryResponse = GetDespesas200;

export type GetDespesasQuery = {
  Response: GetDespesas200;
  QueryParams: GetDespesasQueryParams;
  Errors: GetDespesas400 | GetDespesas500;
};
