/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DespesaRequestDTO } from "../DespesaRequestDTO.ts";
import type { DespesaResponseDTO } from "../DespesaResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type UpdateDespesaPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Despesa atualizada com sucesso.
 */
export type UpdateDespesa200 = DespesaResponseDTO;

/**
 * @description Falha de validação
 */
export type UpdateDespesa400 = ProblemResponseDTO;

/**
 * @description Despesa não encontrada
 */
export type UpdateDespesa404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type UpdateDespesa409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type UpdateDespesa500 = ProblemResponseDTO;

export type UpdateDespesaMutationRequest = DespesaRequestDTO;

export type UpdateDespesaMutationResponse = UpdateDespesa200;

export type UpdateDespesaMutation = {
  Response: UpdateDespesa200;
  Request: UpdateDespesaMutationRequest;
  PathParams: UpdateDespesaPathParams;
  Errors:
    | UpdateDespesa400
    | UpdateDespesa404
    | UpdateDespesa409
    | UpdateDespesa500;
};
