/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type ArchiveResponsavelPathParams = {
  /**
   * @type string, uuid
   */
  responsavelId: string;
};

/**
 * @description Responsável arquivado com sucesso
 */
export type ArchiveResponsavel204 = any;

/**
 * @description Responsável não encontrado
 */
export type ArchiveResponsavel404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type ArchiveResponsavel409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type ArchiveResponsavel500 = ProblemResponseDTO;

export type ArchiveResponsavelMutationResponse = ArchiveResponsavel204;

export type ArchiveResponsavelMutation = {
  Response: ArchiveResponsavel204;
  PathParams: ArchiveResponsavelPathParams;
  Errors: ArchiveResponsavel404 | ArchiveResponsavel409 | ArchiveResponsavel500;
};
