/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type ArquivarResponsavelPathParams = {
  /**
   * @type string, uuid
   */
  responsavelId: string;
};

/**
 * @description Responsável arquivado com sucesso
 */
export type ArquivarResponsavel204 = any;

/**
 * @description Responsável não encontrado
 */
export type ArquivarResponsavel404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type ArquivarResponsavel409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type ArquivarResponsavel500 = ProblemResponseDTO;

export type ArquivarResponsavelMutationResponse = ArquivarResponsavel204;

export type ArquivarResponsavelMutation = {
  Response: ArquivarResponsavel204;
  PathParams: ArquivarResponsavelPathParams;
  Errors:
    | ArquivarResponsavel404
    | ArquivarResponsavel409
    | ArquivarResponsavel500;
};
