/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";
import type { ResponsavelResponseDTO } from "../ResponsavelResponseDTO.ts";

export type BuscarResponsavelPorIdPathParams = {
  /**
   * @type string, uuid
   */
  responsavelId: string;
};

/**
 * @description Responsável retornado com sucesso
 */
export type BuscarResponsavelPorId200 = ResponsavelResponseDTO;

/**
 * @description Responsável não encontrado
 */
export type BuscarResponsavelPorId404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type BuscarResponsavelPorId500 = ProblemResponseDTO;

export type BuscarResponsavelPorIdQueryResponse = BuscarResponsavelPorId200;

export type BuscarResponsavelPorIdQuery = {
  Response: BuscarResponsavelPorId200;
  PathParams: BuscarResponsavelPorIdPathParams;
  Errors: BuscarResponsavelPorId404 | BuscarResponsavelPorId500;
};
