/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";
import type { ResponsavelRequestDTO } from "../ResponsavelRequestDTO.ts";
import type { ResponsavelResponseDTO } from "../ResponsavelResponseDTO.ts";

/**
 * @description Responsável criado com sucesso
 */
export type CriarResponsavel201 = ResponsavelResponseDTO;

/**
 * @description Falha de validação
 */
export type CriarResponsavel400 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type CriarResponsavel409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type CriarResponsavel500 = ProblemResponseDTO;

export type CriarResponsavelMutationRequest = ResponsavelRequestDTO;

export type CriarResponsavelMutationResponse = CriarResponsavel201;

export type CriarResponsavelMutation = {
  Response: CriarResponsavel201;
  Request: CriarResponsavelMutationRequest;
  Errors: CriarResponsavel400 | CriarResponsavel409 | CriarResponsavel500;
};
