/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type DeleteResponsavelPathParams = {
  /**
   * @type string, uuid
   */
  responsavelId: string;
};

export type DeleteResponsavelQueryParams = {
  /**
   * @default false
   * @type boolean | undefined
   */
  cascade?: boolean;
};

/**
 * @description Responsável deletado com sucesso
 */
export type DeleteResponsavel204 = any;

/**
 * @description Responsável não encontrado
 */
export type DeleteResponsavel404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type DeleteResponsavel409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type DeleteResponsavel500 = ProblemResponseDTO;

export type DeleteResponsavelMutationResponse = DeleteResponsavel204;

export type DeleteResponsavelMutation = {
  Response: DeleteResponsavel204;
  PathParams: DeleteResponsavelPathParams;
  QueryParams: DeleteResponsavelQueryParams;
  Errors: DeleteResponsavel404 | DeleteResponsavel409 | DeleteResponsavel500;
};
