/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type DeletarResponsavelPathParams = {
  /**
   * @type string, uuid
   */
  responsavelId: string;
};

/**
 * @description Responsável deletado com sucesso
 */
export type DeletarResponsavel204 = any;

/**
 * @description Responsável não encontrado
 */
export type DeletarResponsavel404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type DeletarResponsavel409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type DeletarResponsavel500 = ProblemResponseDTO;

export type DeletarResponsavelMutationResponse = DeletarResponsavel204;

export type DeletarResponsavelMutation = {
  Response: DeletarResponsavel204;
  PathParams: DeletarResponsavelPathParams;
  Errors: DeletarResponsavel404 | DeletarResponsavel409 | DeletarResponsavel500;
};
