/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedModelResponsavelResponseDTO } from "../PagedModelResponsavelResponseDTO.ts";

export type GetResponsaveisQueryParams = {
    /**
     * @type string | undefined
    */
    nome?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    cpf?: string;
    /**
     * @description Zero-based page index (0..N)
     * @minLength 0
     * @default 0
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The size of the page to be returned
     * @minLength 1
     * @default 10
     * @type integer | undefined
    */
    size?: number;
    /**
     * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @type array | undefined
    */
    sort?: string[];
};

/**
 * @description Lista de responsáveis retornada com sucesso.
*/
export type GetResponsaveis200 = PagedModelResponsavelResponseDTO;

export type GetResponsaveisQueryResponse = GetResponsaveis200;

export type GetResponsaveisQuery = {
    Response: GetResponsaveis200;
    QueryParams: GetResponsaveisQueryParams;
    Errors: any;
};