/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageDTOResponsavelResponseDTO } from "../PageDTOResponsavelResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetResponsaveisQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 10
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type string | undefined
   */
  search?: string;
  /**
   * @type boolean | undefined
   */
  archived?: boolean;
};

/**
 * @description Lista de responsáveis retornada com sucesso.
 */
export type GetResponsaveis200 = PageDTOResponsavelResponseDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetResponsaveis400 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetResponsaveis500 = ProblemResponseDTO;

export type GetResponsaveisQueryResponse = GetResponsaveis200;

export type GetResponsaveisQuery = {
  Response: GetResponsaveis200;
  QueryParams: GetResponsaveisQueryParams;
  Errors: GetResponsaveis400 | GetResponsaveis500;
};
