/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResponsavelResponseDTO } from "../ResponsavelResponseDTO.ts";

export type GetResponsavelByIdPathParams = {
  /**
   * @type string, uuid
   */
  responsavelId: string;
};

/**
 * @description Responsável retornado com sucesso
 */
export type GetResponsavelById200 = ResponsavelResponseDTO;

export type GetResponsavelByIdQueryResponse = GetResponsavelById200;

export type GetResponsavelByIdQuery = {
  Response: GetResponsavelById200;
  PathParams: GetResponsavelByIdPathParams;
  Errors: any;
};
