/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResponsavelResponseDTO } from "../ResponsavelResponseDTO.ts";

/**
 * @description Lista de opções retornada com sucesso.
 */
export type ListResponsaveis200 = ResponsavelResponseDTO[];

export type ListResponsaveisQueryResponse = ListResponsaveis200;

export type ListResponsaveisQuery = {
  Response: ListResponsaveis200;
  Errors: any;
};
