/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const archiveAlunoPathParamsSchema = z.object({
  studentId: z.uuid(),
});

/**
 * @description Aluno arquivado com sucesso.
 */
export const archiveAluno204Schema = z.any();

/**
 * @description Aluno não encontrado
 */
export const archiveAluno404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const archiveAluno409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const archiveAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const archiveAlunoMutationResponseSchema = z.lazy(
  () => archiveAluno204Schema,
);
