/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const arquivarAlunoPathParamsSchema = z.object({
  studentId: z.uuid(),
});

/**
 * @description Aluno arquivado com sucesso.
 */
export const arquivarAluno204Schema = z.any();

/**
 * @description Aluno não encontrado
 */
export const arquivarAluno404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const arquivarAluno409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const arquivarAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const arquivarAlunoMutationResponseSchema = z.lazy(
  () => arquivarAluno204Schema,
);
