/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { alunoRequestDTOSchema } from "../alunoRequestDTOSchema.ts";
import { alunoResponseDTOSchema } from "../alunoResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Aluno criado com sucesso.
 */
export const criarAluno201Schema = z
  .lazy(() => alunoResponseDTOSchema)
  .describe("Dados do aluno retornados pela API");

/**
 * @description Falha de validação
 */
export const criarAluno400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const criarAluno409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const criarAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const criarAlunoMutationRequestSchema = z
  .lazy(() => alunoRequestDTOSchema)
  .describe("Formato de payload para o cadastro de um aluno");

export const criarAlunoMutationResponseSchema = z.lazy(
  () => criarAluno201Schema,
);
