/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const deleteAlunoPathParamsSchema = z.object({
  studentId: z.uuid(),
});

/**
 * @description Aluno deletado com sucesso.
 */
export const deleteAluno204Schema = z.any();

/**
 * @description Aluno não encontrado
 */
export const deleteAluno404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const deleteAluno409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const deleteAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const deleteAlunoMutationResponseSchema = z.lazy(
  () => deleteAluno204Schema,
);
