/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const desarquivarAlunoPathParamsSchema = z.object({
  studentId: z.uuid(),
});

/**
 * @description Aluno desarquivado com sucesso.
 */
export const desarquivarAluno204Schema = z.any();

/**
 * @description Aluno não encontrado
 */
export const desarquivarAluno404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const desarquivarAluno409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const desarquivarAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const desarquivarAlunoMutationResponseSchema = z.lazy(
  () => desarquivarAluno204Schema,
);
