/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const unarchiveAlunoPathParamsSchema = z.object({
  studentId: z.uuid(),
});

/**
 * @description Aluno desarquivado com sucesso.
 */
export const unarchiveAluno204Schema = z.any();

/**
 * @description Aluno não encontrado
 */
export const unarchiveAluno404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const unarchiveAluno409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const unarchiveAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const unarchiveAlunoMutationResponseSchema = z.lazy(
  () => unarchiveAluno204Schema,
);
