/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { authRequestDTOSchema } from "../authRequestDTOSchema.ts";
import { authResponseDTOSchema } from "../authResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Usuario autenticado com sucesso.
 */
export const login200Schema = z
  .lazy(() => authResponseDTOSchema)
  .describe("Resposta de autenticacao com access token JWT");

/**
 * @description Falha de validação
 */
export const login400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Credenciais invalidas.
 */
export const login401Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const login500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const loginMutationRequestSchema = z
  .lazy(() => authRequestDTOSchema)
  .describe("Payload de autenticacao");

export const loginMutationResponseSchema = z.lazy(() => login200Schema);
