/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { authCurrentUserResponseDTOSchema } from "../authCurrentUserResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const me200Schema = z
  .lazy(() => authCurrentUserResponseDTOSchema)
  .describe("Dados do usuário autenticado");

export const meQueryResponseSchema = z.lazy(() => me200Schema);
