import Head from "next/head";
import ErrorPageMain from "../components/ErrorPage/ErrorPageMain";
import Footer from "../components/Layout/Footer/FooterOne/Footer";
import Header from "../components/Layout/Header/Header/Header";

export default function ErrorPage() {
  return (
    <>
      <Head>
        <title>Aprimorar - Cursos preparatórios para o PAS e ENEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ErrorPageMain />
      <Footer />
    </>
  );
}
