import Head from "next/head";
import InstructorProMain from "../components/InstructorProfile/InstructorProMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header/Header";

export default function InstructorProfile() {
  return (
    <>
      <Head>
        <title>
          Eduman - Education And Online Courses React, NextJs Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <InstructorProMain />
      <Footer />
    </>
  );
}
