import Head from "next/head";
import HomeMain from "../components/Home/HomeMain";
import Footer from "../components/Layout/Footer/Footer";
import HeaderFour from "../components/Layout/Header/Header";

import { createClient } from "../services/prismicio";

export default function HomeThree(props) {
  const { universityCards } = props;
  return (
    <>
      <Head>
        {/* TODO - Mudar isso aqui e o favicon */}
        <title>Aprimorar - Aprimorando sua vida</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderFour />
      <HomeMain uniCards={universityCards} />
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const client = createClient();

  const universityCards = await client.getAllByType("universitycard");

  return {
    props: { cards: universityCards },
    revalidate: 86400,
  };
}
