import Head from "next/head";
import Footer from "../components/Layout/Footer/FooterOne/Footer";
import Header from "../components/Layout/Header/Header/Header";
import MembershipMain from "../components/Membership/MembershipMain";

export default function Membership() {
  return (
    <>
      <Head>
        <title>
          Eduman - Education And Online Courses React, NextJs Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MembershipMain />
      <Footer />
    </>
  );
}
