import Head from "next/head";
import Footer from "../components/Layout/Footer/FooterOne/Footer";
import Header from "../components/Layout/Header/Header/Header";
import ZoomClassMain from "../components/ZoomClass/ZoomClassMain";

export default function ZoomClass() {
  return (
    <>
      <Head>
        <title>
          Eduman - Education And Online Courses React, NextJs Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ZoomClassMain />
      <Footer />
    </>
  );
}
