/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type {
  EfetivarTransacaoMutationRequest,
  EfetivarTransacaoMutationResponse,
  EfetivarTransacaoQueryParams,
} from "../../types/EfetivarTransacao.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const efetivarTransacaoMutationKey = () =>
  [{ url: "/transacoes/transacoes/:transacaoId/efetivar" }] as const;

export type EfetivarTransacaoMutationKey = ReturnType<
  typeof efetivarTransacaoMutationKey
>;

/**
 * @description Efetiva uma transacao pendente informando a forma de pagamento.
 * {@link /transacoes/transacoes/:transacaoId/efetivar}
 */
export async function efetivarTransacao(
  params: EfetivarTransacaoQueryParams,
  data?: EfetivarTransacaoMutationRequest,
  config: Partial<RequestConfig<EfetivarTransacaoMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    EfetivarTransacaoMutationResponse,
    ResponseErrorConfig<Error>,
    EfetivarTransacaoMutationRequest
  >({
    method: "POST",
    url: `/transacoes/transacoes/${transacaoId}/efetivar`,
    params,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function efetivarTransacaoMutationOptions(
  config: Partial<RequestConfig<EfetivarTransacaoMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = efetivarTransacaoMutationKey();
  return mutationOptions<
    EfetivarTransacaoMutationResponse,
    ResponseErrorConfig<Error>,
    {
      params: EfetivarTransacaoQueryParams;
      data?: EfetivarTransacaoMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ params, data }) => {
      return efetivarTransacao(params, data, config);
    },
  });
}

/**
 * @description Efetiva uma transacao pendente informando a forma de pagamento.
 * {@link /transacoes/transacoes/:transacaoId/efetivar}
 */
export function useEfetivarTransacao<TContext>(
  options: {
    mutation?: UseMutationOptions<
      EfetivarTransacaoMutationResponse,
      ResponseErrorConfig<Error>,
      {
        params: EfetivarTransacaoQueryParams;
        data?: EfetivarTransacaoMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<EfetivarTransacaoMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? efetivarTransacaoMutationKey();

  const baseOptions = efetivarTransacaoMutationOptions(
    config,
  ) as UseMutationOptions<
    EfetivarTransacaoMutationResponse,
    ResponseErrorConfig<Error>,
    {
      params: EfetivarTransacaoQueryParams;
      data?: EfetivarTransacaoMutationRequest;
    },
    TContext
  >;

  return useMutation<
    EfetivarTransacaoMutationResponse,
    ResponseErrorConfig<Error>,
    {
      params: EfetivarTransacaoQueryParams;
      data?: EfetivarTransacaoMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    EfetivarTransacaoMutationResponse,
    ResponseErrorConfig<Error>,
    {
      params: EfetivarTransacaoQueryParams;
      data?: EfetivarTransacaoMutationRequest;
    },
    TContext
  >;
}
