/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type {
  GetTransacaoByIdQueryResponse,
  GetTransacaoByIdPathParams,
} from "../../types/GetTransacaoById.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getTransacaoByIdQueryKey = (
  id: GetTransacaoByIdPathParams["id"],
) => [{ url: "/v1/transacoes/:id", params: { id: id } }] as const;

export type GetTransacaoByIdQueryKey = ReturnType<
  typeof getTransacaoByIdQueryKey
>;

/**
 * @description Consulta uma transacao especifica pelo ID.
 * {@link /v1/transacoes/:id}
 */
export async function getTransacaoById(
  id: GetTransacaoByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTransacaoByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/transacoes/${id}`, ...requestConfig });
  return res.data;
}

export function getTransacaoByIdQueryOptions(
  id: GetTransacaoByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getTransacaoByIdQueryKey(id);
  return queryOptions<
    GetTransacaoByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetTransacaoByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getTransacaoById(id, config);
    },
  });
}

/**
 * @description Consulta uma transacao especifica pelo ID.
 * {@link /v1/transacoes/:id}
 */
export function useGetTransacaoById<
  TData = GetTransacaoByIdQueryResponse,
  TQueryData = GetTransacaoByIdQueryResponse,
  TQueryKey extends QueryKey = GetTransacaoByIdQueryKey,
>(
  id: GetTransacaoByIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetTransacaoByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getTransacaoByIdQueryKey(id);

  const query = useQuery(
    {
      ...getTransacaoByIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
