/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AtendimentoRequest } from "../AtendimentoRequest.ts";
import type { AtendimentoResponse } from "../AtendimentoResponse.ts";

/**
 * @description Atendimento agendado e retornado com os dados consolidados de aluno e colaborador.
*/
export type AgendarAtendimento201 = AtendimentoResponse;

export type AgendarAtendimentoMutationRequest = AtendimentoRequest;

export type AgendarAtendimentoMutationResponse = AgendarAtendimento201;

export type AgendarAtendimentoMutation = {
    Response: AgendarAtendimento201;
    Request: AgendarAtendimentoMutationRequest;
    Errors: any;
};