/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoRequestDTO } from "../AtendimentoRequestDTO.ts";
import type { AtendimentoResponseDTO } from "../AtendimentoResponseDTO.ts";

/**
 * @description Atendimento agendado e retornado com os dados consolidados de aluno e colaborador.
 */
export type AgendarAtendimento201 = AtendimentoResponseDTO;

export type AgendarAtendimentoMutationRequest = AtendimentoRequestDTO;

export type AgendarAtendimentoMutationResponse = AgendarAtendimento201;

export type AgendarAtendimentoMutation = {
  Response: AgendarAtendimento201;
  Request: AgendarAtendimentoMutationRequest;
  Errors: any;
};
