/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoResponseDTO } from "../AtendimentoResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type AlternarPagamentoColaboradorAtendimentoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Status de pagamento do colaborador atualizado e atendimento retornado.
 */
export type AlternarPagamentoColaboradorAtendimento200 = AtendimentoResponseDTO;

/**
 * @description Atendimento não encontrado
 */
export type AlternarPagamentoColaboradorAtendimento404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type AlternarPagamentoColaboradorAtendimento500 = ProblemResponseDTO;

export type AlternarPagamentoColaboradorAtendimentoMutationResponse =
  AlternarPagamentoColaboradorAtendimento200;

export type AlternarPagamentoColaboradorAtendimentoMutation = {
  Response: AlternarPagamentoColaboradorAtendimento200;
  PathParams: AlternarPagamentoColaboradorAtendimentoPathParams;
  Errors:
    | AlternarPagamentoColaboradorAtendimento404
    | AlternarPagamentoColaboradorAtendimento500;
};
