/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AtendimentoResponse } from "../AtendimentoResponse.ts";

export type CancelarAtendimentoPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

/**
 * @description Atendimento cancelado e retornado com os dados consolidados de aluno e colaborador.
*/
export type CancelarAtendimento200 = AtendimentoResponse;

export type CancelarAtendimentoMutationResponse = CancelarAtendimento200;

export type CancelarAtendimentoMutation = {
    Response: CancelarAtendimento200;
    PathParams: CancelarAtendimentoPathParams;
    Errors: any;
};