/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoResponseDTO } from "../AtendimentoResponseDTO.ts";

export type ConcluirAtendimentoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Atendimento concluído e retornado com os dados consolidados de aluno e colaborador.
 */
export type ConcluirAtendimento200 = AtendimentoResponseDTO;

export type ConcluirAtendimentoMutationResponse = ConcluirAtendimento200;

export type ConcluirAtendimentoMutation = {
  Response: ConcluirAtendimento200;
  PathParams: ConcluirAtendimentoPathParams;
  Errors: any;
};
