/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type DeleteAtendimentoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Atendimento removido sem corpo de resposta.
 */
export type DeleteAtendimento204 = any;

/**
 * @description Atendimento não encontrado
 */
export type DeleteAtendimento404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type DeleteAtendimento409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type DeleteAtendimento500 = ProblemResponseDTO;

export type DeleteAtendimentoMutationResponse = DeleteAtendimento204;

export type DeleteAtendimentoMutation = {
  Response: DeleteAtendimento204;
  PathParams: DeleteAtendimentoPathParams;
  Errors: DeleteAtendimento404 | DeleteAtendimento409 | DeleteAtendimento500;
};
