/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageDTOAtendimentoResponseDTO } from "../PageDTOAtendimentoResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetAtendimentosQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type string | undefined
   */
  search?: string;
  /**
   * @type string | undefined, date-time
   */
  startDate?: string;
  /**
   * @type string | undefined, date-time
   */
  endDate?: string;
  /**
   * @type boolean | undefined
   */
  hideCharged?: boolean;
  /**
   * @type boolean | undefined
   */
  hidePaid?: boolean;
};

/**
 * @description Pagina de atendimentos retornada conforme os filtros informados.
 */
export type GetAtendimentos200 = PageDTOAtendimentoResponseDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetAtendimentos400 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetAtendimentos500 = ProblemResponseDTO;

export type GetAtendimentosQueryResponse = GetAtendimentos200;

export type GetAtendimentosQuery = {
  Response: GetAtendimentos200;
  QueryParams: GetAtendimentosQueryParams;
  Errors: GetAtendimentos400 | GetAtendimentos500;
};
