/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentosContentReportDTO } from "../AtendimentosContentReportDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetAtendimentosContentReportQueryParams = {
  /**
   * @type string | undefined, date-time
   */
  startDate?: string;
  /**
   * @type string | undefined, date-time
   */
  endDate?: string;
};

/**
 * @description Relatório de atendimentos por tipo de conteúdo retornado com totais consolidados.
 */
export type GetAtendimentosContentReport200 = AtendimentosContentReportDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetAtendimentosContentReport400 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetAtendimentosContentReport500 = ProblemResponseDTO;

export type GetAtendimentosContentReportQueryResponse =
  GetAtendimentosContentReport200;

export type GetAtendimentosContentReportQuery = {
  Response: GetAtendimentosContentReport200;
  QueryParams: GetAtendimentosContentReportQueryParams;
  Errors: GetAtendimentosContentReport400 | GetAtendimentosContentReport500;
};
