/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentosColaboradorResponseDTO } from "../AtendimentosColaboradorResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetAtendimentosByColaboradorPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

export type GetAtendimentosByColaboradorQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type boolean | undefined
   */
  ocultarPagos?: boolean;
  /**
   * @type string | undefined, date-time
   */
  inicio?: string;
  /**
   * @type string | undefined, date-time
   */
  fim?: string;
};

/**
 * @description Agenda e resumo financeiro do colaborador retornados conforme periodo e filtros informados.
 */
export type GetAtendimentosByColaborador200 =
  AtendimentosColaboradorResponseDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetAtendimentosByColaborador400 = ProblemResponseDTO;

/**
 * @description Colaborador não encontrado
 */
export type GetAtendimentosByColaborador404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetAtendimentosByColaborador500 = ProblemResponseDTO;

export type GetAtendimentosByColaboradorQueryResponse =
  GetAtendimentosByColaborador200;

export type GetAtendimentosByColaboradorQuery = {
  Response: GetAtendimentosByColaborador200;
  PathParams: GetAtendimentosByColaboradorPathParams;
  QueryParams: GetAtendimentosByColaboradorQueryParams;
  Errors:
    | GetAtendimentosByColaborador400
    | GetAtendimentosByColaborador404
    | GetAtendimentosByColaborador500;
};
