/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardResponse } from "../DashboardResponse.ts";

export type GetDashboardQueryParams = {
  /**
   * @type string
   */
  mes: string;
};

/**
 * @description Dashboard retornado com sucesso.
 */
export type GetDashboard200 = DashboardResponse;

export type GetDashboardQueryResponse = GetDashboard200;

export type GetDashboardQuery = {
  Response: GetDashboard200;
  QueryParams: GetDashboardQueryParams;
  Errors: any;
};
