/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentosKpisDTO } from "../AtendimentosKpisDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetIndicadoresAtendimentosQueryParams = {
  /**
   * @type string | undefined, date-time
   */
  inicio?: string;
  /**
   * @type string | undefined, date-time
   */
  fim?: string;
};

/**
 * @description Relatorio financeiro institucional retornado com totais consolidados.
 */
export type GetIndicadoresAtendimentos200 = AtendimentosKpisDTO;

/**
 * @description Parâmetros inválidos
 */
export type GetIndicadoresAtendimentos400 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type GetIndicadoresAtendimentos500 = ProblemResponseDTO;

export type GetIndicadoresAtendimentosQueryResponse =
  GetIndicadoresAtendimentos200;

export type GetIndicadoresAtendimentosQuery = {
  Response: GetIndicadoresAtendimentos200;
  QueryParams: GetIndicadoresAtendimentosQueryParams;
  Errors: GetIndicadoresAtendimentos400 | GetIndicadoresAtendimentos500;
};
