/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoResponse } from "../AtendimentoResponse.ts";
import type { ReagendarAtendimentoRequest } from "../ReagendarAtendimentoRequest.ts";

export type ReagendarAtendimentoPathParams = {
  /**
   * @type integer, int64
   */
  id: number;
};

/**
 * @description Atendimento reagendado e retornado com os dados consolidados de aluno e colaborador.
 */
export type ReagendarAtendimento200 = AtendimentoResponse;

export type ReagendarAtendimentoMutationRequest = ReagendarAtendimentoRequest;

export type ReagendarAtendimentoMutationResponse = ReagendarAtendimento200;

export type ReagendarAtendimentoMutation = {
  Response: ReagendarAtendimento200;
  Request: ReagendarAtendimentoMutationRequest;
  PathParams: ReagendarAtendimentoPathParams;
  Errors: any;
};
