/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoResponseDTO } from "../AtendimentoResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type ToggleEmployeeAtendimentoPaymentPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Status de pagamento do colaborador atualizado e atendimento retornado.
 */
export type ToggleEmployeeAtendimentoPayment200 = AtendimentoResponseDTO;

/**
 * @description Atendimento não encontrado
 */
export type ToggleEmployeeAtendimentoPayment404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type ToggleEmployeeAtendimentoPayment500 = ProblemResponseDTO;

export type ToggleEmployeeAtendimentoPaymentMutationResponse =
  ToggleEmployeeAtendimentoPayment200;

export type ToggleEmployeeAtendimentoPaymentMutation = {
  Response: ToggleEmployeeAtendimentoPayment200;
  PathParams: ToggleEmployeeAtendimentoPaymentPathParams;
  Errors:
    | ToggleEmployeeAtendimentoPayment404
    | ToggleEmployeeAtendimentoPayment500;
};
