/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtendimentoRequestDTO } from "../AtendimentoRequestDTO.ts";
import type { AtendimentoResponseDTO } from "../AtendimentoResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type UpdateAtendimentoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Atendimento atualizado e retornado com os dados atuais.
 */
export type UpdateAtendimento200 = AtendimentoResponseDTO;

/**
 * @description Falha de validação
 */
export type UpdateAtendimento400 = ProblemResponseDTO;

/**
 * @description Atendimento não encontrado
 */
export type UpdateAtendimento404 = ProblemResponseDTO;

/**
 * @description Conflito de regra de negócio
 */
export type UpdateAtendimento409 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
 */
export type UpdateAtendimento500 = ProblemResponseDTO;

export type UpdateAtendimentoMutationRequest = AtendimentoRequestDTO;

export type UpdateAtendimentoMutationResponse = UpdateAtendimento200;

export type UpdateAtendimentoMutation = {
  Response: UpdateAtendimento200;
  Request: UpdateAtendimentoMutationRequest;
  PathParams: UpdateAtendimentoPathParams;
  Errors:
    | UpdateAtendimento400
    | UpdateAtendimento404
    | UpdateAtendimento409
    | UpdateAtendimento500;
};
