/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const deleteAtendimentoPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Atendimento removido sem corpo de resposta.
 */
export const deleteAtendimento204Schema = z.any();

/**
 * @description Atendimento não encontrado
 */
export const deleteAtendimento404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const deleteAtendimento409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const deleteAtendimento500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const deleteAtendimentoMutationResponseSchema = z.lazy(
  () => deleteAtendimento204Schema,
);
