/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { atendimentosAlunoResponseDTOSchema } from "../atendimentosAlunoResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getAtendimentosByAlunoPathParamsSchema = z.object({
  id: z.uuid(),
});

export const getAtendimentosByAlunoQueryParamsSchema = z.object({
  page: z.coerce
    .number()
    .int()
    .min(0)
    .default(0)
    .describe("Zero-based page index (0..N)"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(20)
    .describe("The size of the page to be returned"),
  sort: z.optional(
    z
      .array(z.string())
      .describe(
        "Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
      ),
  ),
  startDate: z.optional(z.iso.datetime()),
  endDate: z.optional(z.iso.datetime()),
  charged: z.optional(z.boolean()),
});

/**
 * @description Agenda e resumo financeiro do aluno retornados conforme periodo e filtros informados.
 */
export const getAtendimentosByAluno200Schema = z
  .lazy(() => atendimentosAlunoResponseDTOSchema)
  .describe(
    "Agenda paginada e resumo financeiro do aluno no periodo consultado",
  );

/**
 * @description Parâmetros inválidos
 */
export const getAtendimentosByAluno400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Aluno não encontrado
 */
export const getAtendimentosByAluno404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const getAtendimentosByAluno500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const getAtendimentosByAlunoQueryResponseSchema = z.lazy(
  () => getAtendimentosByAluno200Schema,
);
