/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EventRequestDTO } from "../EventRequestDTO.ts";
import type { EventResponseDTO } from "../EventResponseDTO.ts";
import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

/**
 * @description Evento criado com sucesso
 */
export type CreateEvent200 = EventResponseDTO;

/**
 * @description Requisição inválida
 */
export type CreateEvent400 = ProblemDetailResponseDTO;

export type CreateEventMutationRequest = EventRequestDTO;

export type CreateEventMutationResponse = CreateEvent200;

export type CreateEventMutation = {
  Response: CreateEvent200;
  Request: CreateEventMutationRequest;
  Errors: CreateEvent400;
};
