/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EventResponseDTO } from "../EventResponseDTO.ts";
import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

export type GetEventByIdPathParams = {
  /**
   * @description ID do evento
   * @type string, uuid
   */
  eventId: string;
};

/**
 * @description Listagem do evento por ID
 */
export type GetEventById200 = EventResponseDTO;

/**
 * @description Requisição inválida
 */
export type GetEventById400 = ProblemDetailResponseDTO;

export type GetEventByIdQueryResponse = GetEventById200;

export type GetEventByIdQuery = {
  Response: GetEventById200;
  PathParams: GetEventByIdPathParams;
  Errors: GetEventById400;
};
