/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PagedModelEventResponseDTO } from "../PagedModelEventResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetEventsByEmployeePathParams = {
  /**
   * @description ID do colaborador
   * @type string, uuid
   */
  employeeId: string;
};

export type GetEventsByEmployeeQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
};

/**
 * @description Listagem do evento por ID
 */
export type GetEventsByEmployee200 = PagedModelEventResponseDTO;

/**
 * @description Requisição inválida
 */
export type GetEventsByEmployee400 = ProblemResponseDTO;

export type GetEventsByEmployeeQueryResponse = GetEventsByEmployee200;

export type GetEventsByEmployeeQuery = {
  Response: GetEventsByEmployee200;
  PathParams: GetEventsByEmployeePathParams;
  QueryParams: GetEventsByEmployeeQueryParams;
  Errors: GetEventsByEmployee400;
};
