/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserRequestDTO } from "../UserRequestDTO.ts";
import type { UserResponseDTO } from "../UserResponseDTO.ts";

/**
 * @description Usuario criado com sucesso
 */
export type CreateUser201 = UserResponseDTO;

export type CreateUserMutationRequest = UserRequestDTO;

export type CreateUserMutationResponse = CreateUser201;

export type CreateUserMutation = {
  Response: CreateUser201;
  Request: CreateUserMutationRequest;
  Errors: any;
};
