/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type DeleteUserPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

/**
 * @description Usuario excluido com sucesso
*/
export type DeleteUser204 = any;

/**
 * @description Usuario nao encontrado
*/
export type DeleteUser404 = ProblemResponseDTO;

/**
 * @description Erro interno do sistema
*/
export type DeleteUser500 = ProblemResponseDTO;

export type DeleteUserMutationResponse = DeleteUser204;

export type DeleteUserMutation = {
    Response: DeleteUser204;
    PathParams: DeleteUserPathParams;
    Errors: DeleteUser404 | DeleteUser500;
};