/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserResponseDTO } from "../UserResponseDTO.ts";

/**
 * @description Lista de usuarios retornada com sucesso
 */
export type ListUsers200 = UserResponseDTO[];

export type ListUsersQueryResponse = ListUsers200;

export type ListUsersQuery = {
  Response: ListUsers200;
  Errors: any;
};
