/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";
import type { UserResponseDTO } from "../UserResponseDTO.ts";

/**
 * @description Lista de usuarios retornada com sucesso
 */
export type ListUsers200 = UserResponseDTO[];

/**
 * @description Erro interno do sistema
 */
export type ListUsers500 = ProblemResponseDTO;

export type ListUsersQueryResponse = ListUsers200;

export type ListUsersQuery = {
  Response: ListUsers200;
  Errors: ListUsers500;
};
