/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { LoginMutationRequest, LoginMutationResponse } from "../../types/auth/Login.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const loginMutationKey = () => [{ url: '/v1/auth/login' }] as const

export type LoginMutationKey = ReturnType<typeof loginMutationKey>

/**
 * @description Autentica um usuario e retorna um access token JWT.
 * {@link /v1/Auth/login}
 */
export async function login(data: LoginMutationRequest, config: Partial<RequestConfig<LoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<LoginMutationResponse, ResponseErrorConfig<Error>, LoginMutationRequest>({ method : "POST", url : `/v1/auth/login`, data : requestData, ... requestConfig })  
  return res.data
}

export function loginMutationOptions(config: Partial<RequestConfig<LoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = loginMutationKey()
  return mutationOptions<LoginMutationResponse, ResponseErrorConfig<Error>, {data: LoginMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return login(data, config)
    },
  })
}

/**
 * @description Autentica um usuario e retorna um access token JWT.
 * {@link /v1/Auth/login}
 */
export function useLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<LoginMutationResponse, ResponseErrorConfig<Error>, {data: LoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<LoginMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? loginMutationKey()

  const baseOptions = loginMutationOptions(config) as UseMutationOptions<LoginMutationResponse, ResponseErrorConfig<Error>, {data: LoginMutationRequest}, TContext>

  return useMutation<LoginMutationResponse, ResponseErrorConfig<Error>, {data: LoginMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<LoginMutationResponse, ResponseErrorConfig<Error>, {data: LoginMutationRequest}, TContext>
}