/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ArchiveEmployeePathParams = {
  /**
   * @type string, uuid
   */
  employeeId: string;
};

/**
 * @description Colaborador arquivado com sucesso.
 */
export type ArchiveEmployee204 = any;

export type ArchiveEmployeeMutationResponse = ArchiveEmployee204;

export type ArchiveEmployeeMutation = {
  Response: ArchiveEmployee204;
  PathParams: ArchiveEmployeePathParams;
  Errors: any;
};
