/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmployeeCreateDTO } from "../EmployeeCreateDTO.ts";
import type { EmployeeResponseDTO } from "../EmployeeResponseDTO.ts";

/**
 * @description Colaborador criado com sucesso.
 */
export type CreateEmployee201 = EmployeeResponseDTO;

export type CreateEmployeeMutationRequest = EmployeeCreateDTO;

export type CreateEmployeeMutationResponse = CreateEmployee201;

export type CreateEmployeeMutation = {
  Response: CreateEmployee201;
  Request: CreateEmployeeMutationRequest;
  Errors: any;
};
