/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmployeeSummaryDTO } from "../EmployeeSummaryDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

/**
 * @description Listagem dos funcionários para opções e dropdown
 */
export type GetEmployeeSummary200 = EmployeeSummaryDTO[];

/**
 * @description Requisição inválida
 */
export type GetEmployeeSummary400 = ProblemResponseDTO;

export type GetEmployeeSummaryQueryResponse = GetEmployeeSummary200;

export type GetEmployeeSummaryQuery = {
  Response: GetEmployeeSummary200;
  Errors: GetEmployeeSummary400;
};
