/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageDTOEmployeeResponseDTO } from "../PageDTOEmployeeResponseDTO.ts";

export type GetEmployeesQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 10
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @type string | undefined
   */
  search?: string;
  /**
   * @type boolean | undefined
   */
  archived?: boolean;
};

/**
 * @description Lista de colaboradores retornada com sucesso.
 */
export type GetEmployees200 = PageDTOEmployeeResponseDTO;

export type GetEmployeesQueryResponse = GetEmployees200;

export type GetEmployeesQuery = {
  Response: GetEmployees200;
  QueryParams: GetEmployeesQueryParams;
  Errors: any;
};
