/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PagedModelEmployeeResponseDTO } from "../PagedModelEmployeeResponseDTO.ts";
import type { ProblemResponseDTO } from "../ProblemResponseDTO.ts";

export type GetEmployeesQueryParams = {
  /**
   * @description Zero-based page index (0..N)
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description The size of the page to be returned
   * @minLength 1
   * @default 20
   * @type integer | undefined
   */
  size?: number;
  /**
   * @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @type array | undefined
   */
  sort?: string[];
  /**
   * @description Termo de busca
   * @type string | undefined
   */
  search?: string;
};

/**
 * @description Listagem dos funcionários com paginação
 */
export type GetEmployees200 = PagedModelEmployeeResponseDTO;

/**
 * @description Requisição inválida
 */
export type GetEmployees400 = ProblemResponseDTO;

export type GetEmployeesQueryResponse = GetEmployees200;

export type GetEmployeesQuery = {
  Response: GetEmployees200;
  QueryParams: GetEmployeesQueryParams;
  Errors: GetEmployees400;
};
