/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmployeeResponseDTO } from "../EmployeeResponseDTO.ts";

export type GetEmployeeByIdPathParams = {
  /**
   * @type string, uuid
   */
  employeeId: string;
};

/**
 * @description Colaborador retornado com sucesso.
 */
export type GetEmployeeById200 = EmployeeResponseDTO;

export type GetEmployeeByIdQueryResponse = GetEmployeeById200;

export type GetEmployeeByIdQuery = {
  Response: GetEmployeeById200;
  PathParams: GetEmployeeByIdPathParams;
  Errors: any;
};
