/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UnarchiveEmployeePathParams = {
  /**
   * @type string, uuid
   */
  employeeId: string;
};

/**
 * @description Colaborador desarquivado com sucesso.
 */
export type UnarchiveEmployee204 = any;

export type UnarchiveEmployeeMutationResponse = UnarchiveEmployee204;

export type UnarchiveEmployeeMutation = {
  Response: UnarchiveEmployee204;
  PathParams: UnarchiveEmployeePathParams;
  Errors: any;
};
