/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

export type UnarchiveEmployeePathParams = {
  /**
   * @description ID do funcionário
   * @type string, uuid
   */
  employeeId: string;
};

/**
 * @description Funcionário desarquivado com sucesso
 */
export type UnarchiveEmployee204 = any;

/**
 * @description Requisição inválida
 */
export type UnarchiveEmployee400 = ProblemDetailResponseDTO;

export type UnarchiveEmployeeMutationResponse = UnarchiveEmployee204;

export type UnarchiveEmployeeMutation = {
  Response: UnarchiveEmployee204;
  PathParams: UnarchiveEmployeePathParams;
  Errors: UnarchiveEmployee400;
};
