/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmployeeRequestDTO } from "../EmployeeRequestDTO.ts";
import type { EmployeeResponseDTO } from "../EmployeeResponseDTO.ts";

export type UpdateEmployeePathParams = {
  /**
   * @type string, uuid
   */
  employeeId: string;
};

/**
 * @description Colaborador atualizado com sucesso.
 */
export type UpdateEmployee200 = EmployeeResponseDTO;

export type UpdateEmployeeMutationRequest = EmployeeRequestDTO;

export type UpdateEmployeeMutationResponse = UpdateEmployee200;

export type UpdateEmployeeMutation = {
  Response: UpdateEmployee200;
  Request: UpdateEmployeeMutationRequest;
  PathParams: UpdateEmployeePathParams;
  Errors: any;
};
