/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { eventResponseDTOSchema } from "../eventResponseDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getEventByIdPathParamsSchema = z.object({
  eventId: z.uuid().describe("ID do evento"),
});

export type GetEventByIdPathParamsSchema = z.infer<
  typeof getEventByIdPathParamsSchema
>;

/**
 * @description Listagem do evento por ID
 */
export const getEventById200Schema = z.lazy(() => eventResponseDTOSchema);

export type GetEventById200Schema = z.infer<typeof getEventById200Schema>;

/**
 * @description Requisição inválida
 */
export const getEventById400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type GetEventById400Schema = z.infer<typeof getEventById400Schema>;

export const getEventByIdQueryResponseSchema = z.lazy(
  () => getEventById200Schema,
);

export type GetEventByIdQueryResponseSchema = z.infer<
  typeof getEventByIdQueryResponseSchema
>;
