/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pagedModelEventResponseDTOSchema } from "../pagedModelEventResponseDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

export const getEventsQueryParamsSchema = z.object({
  page: z.coerce
    .number()
    .int()
    .min(0)
    .default(0)
    .describe("Zero-based page index (0..N)"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(20)
    .describe("The size of the page to be returned"),
  sort: z
    .array(z.string())
    .describe(
      "Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
    ),
  search: z.optional(z.string().describe("Termo de busca")),
});

export type GetEventsQueryParamsSchema = z.infer<
  typeof getEventsQueryParamsSchema
>;

/**
 * @description Listagem dos eventos com paginação
 */
export const getEvents200Schema = z.lazy(
  () => pagedModelEventResponseDTOSchema,
);

export type GetEvents200Schema = z.infer<typeof getEvents200Schema>;

/**
 * @description Requisição inválida
 */
export const getEvents400Schema = z.lazy(() => problemDetailResponseDTOSchema);

export type GetEvents400Schema = z.infer<typeof getEvents400Schema>;

export const getEventsQueryResponseSchema = z.lazy(() => getEvents200Schema);

export type GetEventsQueryResponseSchema = z.infer<
  typeof getEventsQueryResponseSchema
>;
