/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetDashboardSummaryQueryResponse,
  GetDashboardSummaryQueryParams,
} from "../../types/dashboard-controller/GetDashboardSummary.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDashboardSummaryQueryKey = (
  params: GetDashboardSummaryQueryParams,
) => [{ url: "/v1/dashboard/summary" }, ...(params ? [params] : [])] as const;

export type GetDashboardSummaryQueryKey = ReturnType<
  typeof getDashboardSummaryQueryKey
>;

/**
 * @description Retorna os indicadores e KPI's do dashboard.
 * {@link /v1/dashboard/summary}
 */
export async function getDashboardSummary(
  params: GetDashboardSummaryQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDashboardSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/dashboard/summary`,
    baseURL: `http://localhost:8080`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getDashboardSummaryQueryOptions(
  params: GetDashboardSummaryQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDashboardSummaryQueryKey(params);
  return queryOptions<
    GetDashboardSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardSummaryQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardSummary(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna os indicadores e KPI's do dashboard.
 * {@link /v1/dashboard/summary}
 */
export function useGetDashboardSummary<
  TData = GetDashboardSummaryQueryResponse,
  TQueryData = GetDashboardSummaryQueryResponse,
  TQueryKey extends QueryKey = GetDashboardSummaryQueryKey,
>(
  params: GetDashboardSummaryQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDashboardSummaryQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardSummaryQueryKey(params);

  const query = useQuery(
    {
      ...getDashboardSummaryQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
