/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "zod/v4";

export const deleteEmployeePathParamsSchema = z.object({
  employeeId: z.uuid().describe("ID do funcionário"),
});

export type DeleteEmployeePathParamsSchema = z.infer<
  typeof deleteEmployeePathParamsSchema
>;

/**
 * @description Funcionário deletado com sucesso
 */
export const deleteEmployee204Schema = z.any();

export type DeleteEmployee204Schema = z.infer<typeof deleteEmployee204Schema>;

/**
 * @description Requisição inválida
 */
export const deleteEmployee400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type DeleteEmployee400Schema = z.infer<typeof deleteEmployee400Schema>;

export const deleteEmployeeMutationResponseSchema = z.lazy(
  () => deleteEmployee204Schema,
);

export type DeleteEmployeeMutationResponseSchema = z.infer<
  typeof deleteEmployeeMutationResponseSchema
>;
