/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { employeeSummaryDTOSchema } from "../employeeSummaryDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

/**
 * @description Listagem dos funcionários para opções e dropdown
 */
export const getEmployeeSummary200Schema = z.array(
  z.lazy(() => employeeSummaryDTOSchema),
);

export type GetEmployeeSummary200Schema = z.infer<
  typeof getEmployeeSummary200Schema
>;

/**
 * @description Requisição inválida
 */
export const getEmployeeSummary400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type GetEmployeeSummary400Schema = z.infer<
  typeof getEmployeeSummary400Schema
>;

export const getEmployeeSummaryQueryResponseSchema = z.lazy(
  () => getEmployeeSummary200Schema,
);

export type GetEmployeeSummaryQueryResponseSchema = z.infer<
  typeof getEmployeeSummaryQueryResponseSchema
>;
