/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { employeeResponseDTOSchema } from "../employeeResponseDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getEmployeeByIdPathParamsSchema = z.object({
  employeeId: z.uuid().describe("ID do funcionário"),
});

export type GetEmployeeByIdPathParamsSchema = z.infer<
  typeof getEmployeeByIdPathParamsSchema
>;

/**
 * @description Listagem do funcionário por ID
 */
export const getEmployeeById200Schema = z.lazy(() => employeeResponseDTOSchema);

export type GetEmployeeById200Schema = z.infer<typeof getEmployeeById200Schema>;

/**
 * @description Requisição inválida
 */
export const getEmployeeById400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type GetEmployeeById400Schema = z.infer<typeof getEmployeeById400Schema>;

export const getEmployeeByIdQueryResponseSchema = z.lazy(
  () => getEmployeeById200Schema,
);

export type GetEmployeeByIdQueryResponseSchema = z.infer<
  typeof getEmployeeByIdQueryResponseSchema
>;
