/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { dashboardSummaryResponseDTOSchema } from "../dashboardSummaryResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getDashboardSummaryQueryParamsSchema = z.object({
  year: z.coerce.number().int().describe("Ano do período (ex: 2026)"),
  month: z.coerce.number().int().describe("Mês do período (1-12)"),
});

/**
 * @description Payload do dashboard retornado com sucesso.
 */
export const getDashboardSummary200Schema = z.lazy(
  () => dashboardSummaryResponseDTOSchema,
);

export const getDashboardSummaryQueryResponseSchema = z.lazy(
  () => getDashboardSummary200Schema,
);
