/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CreateEmployeeMutationRequest,
  CreateEmployeeMutationResponse,
} from "../../types/employee/CreateEmployee.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createEmployeeMutationKey = () =>
  [{ url: "/v1/employees" }] as const;

export type CreateEmployeeMutationKey = ReturnType<
  typeof createEmployeeMutationKey
>;

/**
 * @description Cria um novo colaborador com os dados fornecidos.
 * {@link /v1/employees}
 */
export async function createEmployee(
  data: CreateEmployeeMutationRequest,
  config: Partial<RequestConfig<CreateEmployeeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    CreateEmployeeMutationRequest
  >({
    method: "POST",
    url: `/v1/employees`,
    baseURL: `http://localhost:8080`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createEmployeeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateEmployeeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createEmployeeMutationKey();
  return mutationOptions<
    CreateEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateEmployeeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createEmployee(data, config);
    },
  });
}

/**
 * @description Cria um novo colaborador com os dados fornecidos.
 * {@link /v1/employees}
 */
export function useCreateEmployee<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateEmployeeMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CreateEmployeeMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateEmployeeMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createEmployeeMutationKey();

  const baseOptions = createEmployeeMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateEmployeeMutationRequest },
    TContext
  >;

  return useMutation<
    CreateEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateEmployeeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateEmployeeMutationRequest },
    TContext
  >;
}
