/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteEmployeeMutationResponse,
  DeleteEmployeePathParams,
} from "../../types/employee/DeleteEmployee.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteEmployeeMutationKey = () =>
  [{ url: "/v1/employees/:employeeId" }] as const;

export type DeleteEmployeeMutationKey = ReturnType<
  typeof deleteEmployeeMutationKey
>;

/**
 * @description Deleta um colaborador por ID.
 * {@link /v1/employees/:employeeId}
 */
export async function deleteEmployee(
  employeeId: DeleteEmployeePathParams["employeeId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: `/v1/employees/${employeeId}`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteEmployeeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteEmployeeMutationKey();
  return mutationOptions<
    DeleteEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: DeleteEmployeePathParams["employeeId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ employeeId }) => {
      return deleteEmployee(employeeId, config);
    },
  });
}

/**
 * @description Deleta um colaborador por ID.
 * {@link /v1/employees/:employeeId}
 */
export function useDeleteEmployee<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteEmployeeMutationResponse,
      ResponseErrorConfig<Error>,
      { employeeId: DeleteEmployeePathParams["employeeId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteEmployeeMutationKey();

  const baseOptions = deleteEmployeeMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: DeleteEmployeePathParams["employeeId"] },
    TContext
  >;

  return useMutation<
    DeleteEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: DeleteEmployeePathParams["employeeId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: DeleteEmployeePathParams["employeeId"] },
    TContext
  >;
}
