/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UnarchiveEmployeeMutationResponse,
  UnarchiveEmployeePathParams,
} from "../../types/employee/UnarchiveEmployee.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const unarchiveEmployeeMutationKey = () =>
  [{ url: "/v1/employees/:employeeId/unarchive" }] as const;

export type UnarchiveEmployeeMutationKey = ReturnType<
  typeof unarchiveEmployeeMutationKey
>;

/**
 * @description Desarquiva um colaborador por ID.
 * {@link /v1/employees/:employeeId/unarchive}
 */
export async function unarchiveEmployee(
  employeeId: UnarchiveEmployeePathParams["employeeId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    UnarchiveEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/employees/${employeeId}/unarchive`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function unarchiveEmployeeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = unarchiveEmployeeMutationKey();
  return mutationOptions<
    UnarchiveEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: UnarchiveEmployeePathParams["employeeId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ employeeId }) => {
      return unarchiveEmployee(employeeId, config);
    },
  });
}

/**
 * @description Desarquiva um colaborador por ID.
 * {@link /v1/employees/:employeeId/unarchive}
 */
export function useUnarchiveEmployee<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UnarchiveEmployeeMutationResponse,
      ResponseErrorConfig<Error>,
      { employeeId: UnarchiveEmployeePathParams["employeeId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? unarchiveEmployeeMutationKey();

  const baseOptions = unarchiveEmployeeMutationOptions(
    config,
  ) as UseMutationOptions<
    UnarchiveEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: UnarchiveEmployeePathParams["employeeId"] },
    TContext
  >;

  return useMutation<
    UnarchiveEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: UnarchiveEmployeePathParams["employeeId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UnarchiveEmployeeMutationResponse,
    ResponseErrorConfig<Error>,
    { employeeId: UnarchiveEmployeePathParams["employeeId"] },
    TContext
  >;
}
