/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { despesaRequestDTOSchema } from "../despesaRequestDTOSchema.ts";
import { despesaResponseDTOSchema } from "../despesaResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Despesa criada com sucesso.
 */
export const createDespesa201Schema = z
  .lazy(() => despesaResponseDTOSchema)
  .describe("Dados de despesa retornados pela API");

/**
 * @description Falha de validação
 */
export const createDespesa400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const createDespesa409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const createDespesa500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const createDespesaMutationRequestSchema = z
  .lazy(() => despesaRequestDTOSchema)
  .describe("Payload para criacao ou atualizacao de despesa");

export const createDespesaMutationResponseSchema = z.lazy(
  () => createDespesa201Schema,
);
