/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const deleteDespesaPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Despesa excluída com sucesso.
 */
export const deleteDespesa204Schema = z.any();

/**
 * @description Despesa não encontrada
 */
export const deleteDespesa404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const deleteDespesa409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const deleteDespesa500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const deleteDespesaMutationResponseSchema = z.lazy(
  () => deleteDespesa204Schema,
);
