/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { despesaResponseDTOSchema } from "../despesaResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const toggleDespesaPaymentPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Status de pagamento da despesa atualizado com sucesso.
 */
export const toggleDespesaPayment200Schema = z
  .lazy(() => despesaResponseDTOSchema)
  .describe("Dados de despesa retornados pela API");

/**
 * @description Despesa não encontrada
 */
export const toggleDespesaPayment404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const toggleDespesaPayment500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const toggleDespesaPaymentMutationResponseSchema = z.lazy(
  () => toggleDespesaPayment200Schema,
);
