/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pagedModelParentResponseDTOSchema } from "../pagedModelParentResponseDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "zod/v4";

export const getParentsQueryParamsSchema = z.object({
  page: z.coerce
    .number()
    .int()
    .min(0)
    .default(0)
    .describe("Zero-based page index (0..N)"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(20)
    .describe("The size of the page to be returned"),
  sort: z.optional(
    z
      .array(z.string())
      .describe(
        "Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
      ),
  ),
  search: z.optional(z.string().describe("Termo de busca")),
});

export type GetParentsQueryParamsSchema = z.infer<
  typeof getParentsQueryParamsSchema
>;

/**
 * @description Responsáveis listados com sucesso
 */
export const getParents200Schema = z.lazy(
  () => pagedModelParentResponseDTOSchema,
);

export type GetParents200Schema = z.infer<typeof getParents200Schema>;

/**
 * @description Requisição inválida
 */
export const getParents400Schema = z.lazy(() => problemDetailResponseDTOSchema);

export type GetParents400Schema = z.infer<typeof getParents400Schema>;

export const getParentsQueryResponseSchema = z.lazy(() => getParents200Schema);

export type GetParentsQueryResponseSchema = z.infer<
  typeof getParentsQueryResponseSchema
>;
