/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { parentSummaryDTOSchema } from "../parentSummaryDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

/**
 * @description Responsáveis listados com sucesso
 */
export const getParentsSummary200Schema = z.array(
  z.lazy(() => parentSummaryDTOSchema),
);

export type GetParentsSummary200Schema = z.infer<
  typeof getParentsSummary200Schema
>;

/**
 * @description Requisição inválida
 */
export const getParentsSummary400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type GetParentsSummary400Schema = z.infer<
  typeof getParentsSummary400Schema
>;

export const getParentsSummaryQueryResponseSchema = z.lazy(
  () => getParentsSummary200Schema,
);

export type GetParentsSummaryQueryResponseSchema = z.infer<
  typeof getParentsSummaryQueryResponseSchema
>;
