/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { parentOptionDTOSchema } from "../parentOptionDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Responsáveis listados com sucesso
 */
export const getParentsOptions200Schema = z.array(
  z.lazy(() => parentOptionDTOSchema),
);

export type GetParentsOptions200Schema = z.infer<
  typeof getParentsOptions200Schema
>;

/**
 * @description Requisição inválida
 */
export const getParentsOptions400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type GetParentsOptions400Schema = z.infer<
  typeof getParentsOptions400Schema
>;

export const getParentsOptionsQueryResponseSchema = z.lazy(
  () => getParentsOptions200Schema,
);

export type GetParentsOptionsQueryResponseSchema = z.infer<
  typeof getParentsOptionsQueryResponseSchema
>;
