/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { parentRequestDTOSchema } from "../parentRequestDTOSchema.ts";
import { parentResponseDTOSchema } from "../parentResponseDTOSchema.ts";
import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

export const updateParentPathParamsSchema = z.object({
  parentId: z.uuid().describe("ID do responsável"),
});

export type UpdateParentPathParamsSchema = z.infer<
  typeof updateParentPathParamsSchema
>;

/**
 * @description Responsável atualizado com sucesso
 */
export const updateParent200Schema = z.lazy(() => parentResponseDTOSchema);

export type UpdateParent200Schema = z.infer<typeof updateParent200Schema>;

/**
 * @description Requisição inválida
 */
export const updateParent400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type UpdateParent400Schema = z.infer<typeof updateParent400Schema>;

export const updateParentMutationRequestSchema = z
  .lazy(() => parentRequestDTOSchema)
  .describe("Dados do responsável");

export type UpdateParentMutationRequestSchema = z.infer<
  typeof updateParentMutationRequestSchema
>;

export const updateParentMutationResponseSchema = z.lazy(
  () => updateParent200Schema,
);

export type UpdateParentMutationResponseSchema = z.infer<
  typeof updateParentMutationResponseSchema
>;
