/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ParentRequestDTO } from "../ParentRequestDTO.ts";
import type { ParentResponseDTO } from "../ParentResponseDTO.ts";
import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

/**
 * @description Responsável criado com sucesso
 */
export type CreateParent200 = ParentResponseDTO;

/**
 * @description Requisição inválida
 */
export type CreateParent400 = ProblemDetailResponseDTO;

export type CreateParentMutationRequest = ParentRequestDTO;

export type CreateParentMutationResponse = CreateParent200;

export type CreateParentMutation = {
  Response: CreateParent200;
  Request: CreateParentMutationRequest;
  Errors: CreateParent400;
};
