/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetailResponseDTO } from "../ProblemDetailResponseDTO.ts";

export type DeleteParentPathParams = {
  /**
   * @description ID do responsável
   * @type string, uuid
   */
  parentId: string;
};

/**
 * @description Responsável deletado com sucesso
 */
export type DeleteParent200 = any;

/**
 * @description Requisição inválida
 */
export type DeleteParent400 = ProblemDetailResponseDTO;

export type DeleteParentMutationResponse = DeleteParent200;

export type DeleteParentMutation = {
  Response: DeleteParent200;
  PathParams: DeleteParentPathParams;
  Errors: DeleteParent400;
};
