/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteParentPathParams = {
  /**
   * @type string, uuid
   */
  parentId: string;
};

/**
 * @description Responsável deletado com sucesso
 */
export type DeleteParent204 = any;

export type DeleteParentMutationResponse = DeleteParent204;

export type DeleteParentMutation = {
  Response: DeleteParent204;
  PathParams: DeleteParentPathParams;
  Errors: any;
};
