/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ParentResponseDTO } from "../ParentResponseDTO.ts";

export type GetParentByIdPathParams = {
  /**
   * @type string, uuid
   */
  parentId: string;
};

/**
 * @description Responsável retornado com sucesso
 * @example Parent Name
 */
export type GetParentById200 = ParentResponseDTO;

export type GetParentByIdQueryResponse = GetParentById200;

export type GetParentByIdQuery = {
  Response: GetParentById200;
  PathParams: GetParentByIdPathParams;
  Errors: any;
};
