/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ParentOptionsDTO } from "../ParentOptionsDTO.ts";

/**
 * @description Lista de opções retornada com sucesso.
 */
export type GetParentsOptions200 = ParentOptionsDTO[];

export type GetParentsOptionsQueryResponse = GetParentsOptions200;

export type GetParentsOptionsQuery = {
  Response: GetParentsOptions200;
  Errors: any;
};
