/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ParentRequestDTO } from "../ParentRequestDTO.ts";
import type { ParentResponseDTO } from "../ParentResponseDTO.ts";

export type UpdateParentPathParams = {
  /**
   * @type string, uuid
   */
  parentId: string;
};

/**
 * @description Responsável atualizado com sucesso
 */
export type UpdateParent200 = ParentResponseDTO;

export type UpdateParentMutationRequest = ParentRequestDTO;

export type UpdateParentMutationResponse = UpdateParent200;

export type UpdateParentMutation = {
  Response: UpdateParent200;
  Request: UpdateParentMutationRequest;
  PathParams: UpdateParentPathParams;
  Errors: any;
};
