/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const deleteStudentPathParamsSchema = z.object({
  studentId: z.uuid(),
});

/**
 * @description Aluno deletado com sucesso.
 */
export const deleteStudent204Schema = z.any();

export const deleteStudentMutationResponseSchema = z.lazy(
  () => deleteStudent204Schema,
);
