/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

export const deleteStudentPathParamsSchema = z.object({
  studentId: z.uuid(),
});

export type DeleteStudentPathParamsSchema = z.infer<
  typeof deleteStudentPathParamsSchema
>;

/**
 * @description Aluno deletado com sucesso
 */
export const deleteStudent204Schema = z.any();

export type DeleteStudent204Schema = z.infer<typeof deleteStudent204Schema>;

/**
 * @description Requisição inválida
 */
export const deleteStudent400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type DeleteStudent400Schema = z.infer<typeof deleteStudent400Schema>;

export const deleteStudentMutationResponseSchema = z.lazy(
  () => deleteStudent204Schema,
);

export type DeleteStudentMutationResponseSchema = z.infer<
  typeof deleteStudentMutationResponseSchema
>;
