/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { studentOptionDTOSchema } from "../studentOptionDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Listagem dos alunos para opções e dropdown
 */
export const getStudentOptions200Schema = z.array(
  z.lazy(() => studentOptionDTOSchema),
);

export type GetStudentOptions200Schema = z.infer<
  typeof getStudentOptions200Schema
>;

/**
 * @description Requisição inválida
 */
export const getStudentOptions400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type GetStudentOptions400Schema = z.infer<
  typeof getStudentOptions400Schema
>;

export const getStudentOptionsQueryResponseSchema = z.lazy(
  () => getStudentOptions200Schema,
);

export type GetStudentOptionsQueryResponseSchema = z.infer<
  typeof getStudentOptionsQueryResponseSchema
>;
