/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { z } from "@/lib/validations/zod";

export const unarchiveStudentPathParamsSchema = z.object({
  studentId: z.uuid(),
});

export type UnarchiveStudentPathParamsSchema = z.infer<
  typeof unarchiveStudentPathParamsSchema
>;

/**
 * @description Aluno desarquivado com sucesso
 */
export const unarchiveStudent204Schema = z.any();

export type UnarchiveStudent204Schema = z.infer<
  typeof unarchiveStudent204Schema
>;

/**
 * @description Requisição inválida
 */
export const unarchiveStudent400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type UnarchiveStudent400Schema = z.infer<
  typeof unarchiveStudent400Schema
>;

export const unarchiveStudentMutationResponseSchema = z.lazy(
  () => unarchiveStudent204Schema,
);

export type UnarchiveStudentMutationResponseSchema = z.infer<
  typeof unarchiveStudentMutationResponseSchema
>;
