/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailResponseDTOSchema } from "../problemDetailResponseDTOSchema.ts";
import { studentRequestDTOSchema } from "../studentRequestDTOSchema.ts";
import { studentResponseDTOSchema } from "../studentResponseDTOSchema.ts";
import { z } from "zod/v4";

export const updateStudentPathParamsSchema = z.object({
  studentId: z.uuid().describe("ID do aluno"),
});

export type UpdateStudentPathParamsSchema = z.infer<
  typeof updateStudentPathParamsSchema
>;

/**
 * @description Aluno atualizado com sucesso
 */
export const updateStudent200Schema = z.lazy(() => studentResponseDTOSchema);

export type UpdateStudent200Schema = z.infer<typeof updateStudent200Schema>;

/**
 * @description Requisição inválida
 */
export const updateStudent400Schema = z.lazy(
  () => problemDetailResponseDTOSchema,
);

export type UpdateStudent400Schema = z.infer<typeof updateStudent400Schema>;

export const updateStudentMutationRequestSchema = z
  .lazy(() => studentRequestDTOSchema)
  .describe("Dados do aluno");

export type UpdateStudentMutationRequestSchema = z.infer<
  typeof updateStudentMutationRequestSchema
>;

export const updateStudentMutationResponseSchema = z.lazy(
  () => updateStudent200Schema,
);

export type UpdateStudentMutationResponseSchema = z.infer<
  typeof updateStudentMutationResponseSchema
>;
