/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { colaboradorRequestDTOSchema } from "../colaboradorRequestDTOSchema.ts";
import { colaboradorResponseDTOSchema } from "../colaboradorResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Colaborador criado com sucesso.
 */
export const createColaborador201Schema = z
  .lazy(() => colaboradorResponseDTOSchema)
  .describe("Dados do colaborador retornados pela API");

/**
 * @description Falha de validação
 */
export const createColaborador400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const createColaborador409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const createColaborador500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const createColaboradorMutationRequestSchema = z
  .lazy(() => colaboradorRequestDTOSchema)
  .describe("Formato de payload para criar um novo colaborador");

export const createColaboradorMutationResponseSchema = z.lazy(
  () => createColaborador201Schema,
);
