/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const deleteColaboradorPathParamsSchema = z.object({
  colaboradorId: z.uuid(),
});

/**
 * @description Colaborador deletado com sucesso.
 */
export const deleteColaborador204Schema = z.any();

/**
 * @description Colaborador não encontrado
 */
export const deleteColaborador404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const deleteColaborador409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const deleteColaborador500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const deleteColaboradorMutationResponseSchema = z.lazy(
  () => deleteColaborador204Schema,
);
