/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { colaboradorResponseDTOSchema } from "../colaboradorResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const findColaboradorByIdPathParamsSchema = z.object({
  colaboradorId: z.uuid(),
});

/**
 * @description Colaborador retornado com sucesso.
 */
export const findColaboradorById200Schema = z
  .lazy(() => colaboradorResponseDTOSchema)
  .describe("Dados do colaborador retornados pela API");

/**
 * @description Colaborador não encontrado
 */
export const findColaboradorById404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const findColaboradorById500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const findColaboradorByIdQueryResponseSchema = z.lazy(
  () => findColaboradorById200Schema,
);
