/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { colaboradoresKpisDTOSchema } from "../colaboradoresKpisDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description KPIs de colaboradores retornados com sucesso.
 */
export const getColaboradoresKpis200Schema = z
  .lazy(() => colaboradoresKpisDTOSchema)
  .describe("Formato de payload para obter opções de colaboradores");

/**
 * @description Parâmetros inválidos
 */
export const getColaboradoresKpis400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const getColaboradoresKpis500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const getColaboradoresKpisQueryResponseSchema = z.lazy(
  () => getColaboradoresKpis200Schema,
);
