/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { colaboradorRequestDTOSchema } from "../colaboradorRequestDTOSchema.ts";
import { colaboradorResponseDTOSchema } from "../colaboradorResponseDTOSchema.ts";
import { problemResponseDTOSchema } from "../problemResponseDTOSchema.ts";
import { z } from "zod/v4";

export const updateColaboradorPathParamsSchema = z.object({
  colaboradorId: z.uuid(),
});

/**
 * @description Colaborador atualizado com sucesso.
 */
export const updateColaborador200Schema = z
  .lazy(() => colaboradorResponseDTOSchema)
  .describe("Dados do colaborador retornados pela API");

/**
 * @description Falha de validação
 */
export const updateColaborador400Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Colaborador não encontrado
 */
export const updateColaborador404Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Conflito de regra de negócio
 */
export const updateColaborador409Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

/**
 * @description Erro interno do sistema
 */
export const updateColaborador500Schema = z
  .lazy(() => problemResponseDTOSchema)
  .describe("Um Problem são boas práticas de formato de exceptions em Java");

export const updateColaboradorMutationRequestSchema = z
  .lazy(() => colaboradorRequestDTOSchema)
  .describe("Formato de payload para criar um novo colaborador");

export const updateColaboradorMutationResponseSchema = z.lazy(
  () => updateColaborador200Schema,
);
