/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type {
  ArchiveUserMutationResponse,
  ArchiveUserPathParams,
} from "../../types/ArchiveUser.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const archiveUserMutationKey = () =>
  [{ url: "/v1/users/:id/archive" }] as const;

export type ArchiveUserMutationKey = ReturnType<typeof archiveUserMutationKey>;

/**
 * @summary Toggle active status of a user
 * {@link /v1/users/:id/archive}
 */
export async function archiveUser(
  id: ArchiveUserPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ArchiveUserMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "PATCH", url: `/v1/users/${id}/archive`, ...requestConfig });
  return res.data;
}

export function archiveUserMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = archiveUserMutationKey();
  return mutationOptions<
    ArchiveUserMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ArchiveUserPathParams["id"] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return archiveUser(id, config);
    },
  });
}

/**
 * @summary Toggle active status of a user
 * {@link /v1/users/:id/archive}
 */
export function useArchiveUser<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ArchiveUserMutationResponse,
      ResponseErrorConfig<Error>,
      { id: ArchiveUserPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? archiveUserMutationKey();

  const baseOptions = archiveUserMutationOptions(config) as UseMutationOptions<
    ArchiveUserMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ArchiveUserPathParams["id"] },
    TContext
  >;

  return useMutation<
    ArchiveUserMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ArchiveUserPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ArchiveUserMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ArchiveUserPathParams["id"] },
    TContext
  >;
}
