/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ListUsersQueryResponse,
  ListUsers500,
} from "../../types/user/ListUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listUsersQueryKey = () => [{ url: "/v1/users" }] as const;

export type ListUsersQueryKey = ReturnType<typeof listUsersQueryKey>;

/**
 * @summary List all users
 * {@link /v1/users}
 */
export async function listUsers(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListUsersQueryResponse,
    ResponseErrorConfig<ListUsers500>,
    unknown
  >({ method: "GET", url: `/v1/users`, ...requestConfig });
  return res.data;
}

export function listUsersQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listUsersQueryKey();
  return queryOptions<
    ListUsersQueryResponse,
    ResponseErrorConfig<ListUsers500>,
    ListUsersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listUsers({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary List all users
 * {@link /v1/users}
 */
export function useListUsers<
  TData = ListUsersQueryResponse,
  TQueryData = ListUsersQueryResponse,
  TQueryKey extends QueryKey = ListUsersQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListUsersQueryResponse,
        ResponseErrorConfig<ListUsers500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? listUsersQueryKey();

  const query = useQuery(
    {
      ...listUsersQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<ListUsers500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
