/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetStudentSummaryQueryResponse } from "../../types/student-controller/GetStudentSummary.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getStudentSummaryQueryKey = () =>
  [{ url: "/v1/students/options" }] as const;

export type GetStudentSummaryQueryKey = ReturnType<
  typeof getStudentSummaryQueryKey
>;

/**
 * @description Retorna uma lista de opções de alunos.
 * {@link /v1/students/options}
 */
export async function getStudentSummary(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetStudentSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/students/options`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function getStudentSummaryQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getStudentSummaryQueryKey();
  return queryOptions<
    GetStudentSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    GetStudentSummaryQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getStudentSummary({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Retorna uma lista de opções de alunos.
 * {@link /v1/students/options}
 */
export function useGetStudentSummary<
  TData = GetStudentSummaryQueryResponse,
  TQueryData = GetStudentSummaryQueryResponse,
  TQueryKey extends QueryKey = GetStudentSummaryQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetStudentSummaryQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getStudentSummaryQueryKey();

  const query = useQuery(
    {
      ...getStudentSummaryQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
