/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetStudentOptionsQueryResponse } from "../../types/student-controller/GetStudentOptions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getStudentOptionsQueryKey = () =>
  [{ url: "/v1/students/options" }] as const;

export type GetStudentOptionsQueryKey = ReturnType<
  typeof getStudentOptionsQueryKey
>;

/**
 * @description Retorna uma lista de opções de alunos.
 * {@link /v1/students/options}
 */
export async function getStudentOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetStudentOptionsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/students/options`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function getStudentOptionsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getStudentOptionsQueryKey();
  return queryOptions<
    GetStudentOptionsQueryResponse,
    ResponseErrorConfig<Error>,
    GetStudentOptionsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getStudentOptions({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Retorna uma lista de opções de alunos.
 * {@link /v1/students/options}
 */
export function useGetStudentOptions<
  TData = GetStudentOptionsQueryResponse,
  TQueryData = GetStudentOptionsQueryResponse,
  TQueryKey extends QueryKey = GetStudentOptionsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetStudentOptionsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getStudentOptionsQueryKey();

  const query = useQuery(
    {
      ...getStudentOptionsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
