/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ArchiveParentMutationResponse,
  ArchiveParentPathParams,
} from "../../types/parent/ArchiveParent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const archiveParentMutationKey = () =>
  [{ url: "/v1/parents/:parentId/archive" }] as const;

export type ArchiveParentMutationKey = ReturnType<
  typeof archiveParentMutationKey
>;

/**
 * @description Arquiva um responsável por ID
 * {@link /v1/parents/:parentId/archive}
 */
export async function archiveParent(
  parentId: ArchiveParentPathParams["parentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ArchiveParentMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/parents/${parentId}/archive`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function archiveParentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = archiveParentMutationKey();
  return mutationOptions<
    ArchiveParentMutationResponse,
    ResponseErrorConfig<Error>,
    { parentId: ArchiveParentPathParams["parentId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ parentId }) => {
      return archiveParent(parentId, config);
    },
  });
}

/**
 * @description Arquiva um responsável por ID
 * {@link /v1/parents/:parentId/archive}
 */
export function useArchiveParent<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ArchiveParentMutationResponse,
      ResponseErrorConfig<Error>,
      { parentId: ArchiveParentPathParams["parentId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? archiveParentMutationKey();

  const baseOptions = archiveParentMutationOptions(
    config,
  ) as UseMutationOptions<
    ArchiveParentMutationResponse,
    ResponseErrorConfig<Error>,
    { parentId: ArchiveParentPathParams["parentId"] },
    TContext
  >;

  return useMutation<
    ArchiveParentMutationResponse,
    ResponseErrorConfig<Error>,
    { parentId: ArchiveParentPathParams["parentId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ArchiveParentMutationResponse,
    ResponseErrorConfig<Error>,
    { parentId: ArchiveParentPathParams["parentId"] },
    TContext
  >;
}
