/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetParentsSummaryQueryResponse,
  GetParentsSummary400,
} from "../../types/parent/GetParentsSummary.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getParentsSummaryQueryKey = () =>
  [{ url: "/v1/parents/summary" }] as const;

export type GetParentsSummaryQueryKey = ReturnType<
  typeof getParentsSummaryQueryKey
>;

/**
 * @description Lista todos os responsáveis cadastrados para uso em listas e dropdowns.
 * @summary Listar responsáveis para listas e dropdowns
 * {@link /v1/parents/summary}
 */
export async function getParentsSummary(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetParentsSummaryQueryResponse,
    ResponseErrorConfig<GetParentsSummary400>,
    unknown
  >({
    method: "GET",
    url: `/v1/parents/summary`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return res.data;
}

export function getParentsSummaryQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getParentsSummaryQueryKey();
  return queryOptions<
    GetParentsSummaryQueryResponse,
    ResponseErrorConfig<GetParentsSummary400>,
    GetParentsSummaryQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getParentsSummary({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Lista todos os responsáveis cadastrados para uso em listas e dropdowns.
 * @summary Listar responsáveis para listas e dropdowns
 * {@link /v1/parents/summary}
 */
export function useGetParentsSummary<
  TData = GetParentsSummaryQueryResponse,
  TQueryData = GetParentsSummaryQueryResponse,
  TQueryKey extends QueryKey = GetParentsSummaryQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetParentsSummaryQueryResponse,
        ResponseErrorConfig<GetParentsSummary400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getParentsSummaryQueryKey();

  const query = useQuery(
    {
      ...getParentsSummaryQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetParentsSummary400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
