/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetParentsQueryResponse,
  GetParentsQueryParams,
} from "../../types/parent/GetParents.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getParentsQueryKey = (params?: GetParentsQueryParams) =>
  [{ url: "/v1/parents" }, ...(params ? [params] : [])] as const;

export type GetParentsQueryKey = ReturnType<typeof getParentsQueryKey>;

/**
 * @description Retorna uma lista de responsáveis paginada
 * {@link /v1/parents}
 */
export async function getParents(
  params?: GetParentsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetParentsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/parents`,
    baseURL: `http://localhost:8080`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getParentsQueryOptions(
  params?: GetParentsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getParentsQueryKey(params);
  return queryOptions<
    GetParentsQueryResponse,
    ResponseErrorConfig<Error>,
    GetParentsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getParents(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Retorna uma lista de responsáveis paginada
 * {@link /v1/parents}
 */
export function useGetParents<
  TData = GetParentsQueryResponse,
  TQueryData = GetParentsQueryResponse,
  TQueryKey extends QueryKey = GetParentsQueryKey,
>(
  params?: GetParentsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetParentsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getParentsQueryKey(params);

  const query = useQuery(
    {
      ...getParentsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
