/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UnarchiveParentMutationResponse,
  UnarchiveParentPathParams,
  UnarchiveParent404,
} from "../../types/parent/UnarchiveParent.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { unarchiveParentMutationResponseSchema } from "../../schemas/parent/unarchiveParentSchema.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const unarchiveParentMutationKey = () =>
  [{ url: "/v1/parents/:parentId/unarchive" }] as const;

export type UnarchiveParentMutationKey = ReturnType<
  typeof unarchiveParentMutationKey
>;

/**
 * @description Desarquiva um responsável específico.
 * @summary Desarquivar responsável
 * {@link /v1/parents/:parentId/unarchive}
 */
export async function unarchiveParent(
  parentId: UnarchiveParentPathParams["parentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    UnarchiveParentMutationResponse,
    ResponseErrorConfig<UnarchiveParent404>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/parents/${parentId}/unarchive`,
    baseURL: `http://localhost:8080`,
    ...requestConfig,
  });
  return unarchiveParentMutationResponseSchema.parse(res.data);
}

export function unarchiveParentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = unarchiveParentMutationKey();
  return mutationOptions<
    UnarchiveParentMutationResponse,
    ResponseErrorConfig<UnarchiveParent404>,
    { parentId: UnarchiveParentPathParams["parentId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ parentId }) => {
      return unarchiveParent(parentId, config);
    },
  });
}

/**
 * @description Desarquiva um responsável específico.
 * @summary Desarquivar responsável
 * {@link /v1/parents/:parentId/unarchive}
 */
export function useUnarchiveParent<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UnarchiveParentMutationResponse,
      ResponseErrorConfig<UnarchiveParent404>,
      { parentId: UnarchiveParentPathParams["parentId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? unarchiveParentMutationKey();

  const baseOptions = unarchiveParentMutationOptions(
    config,
  ) as UseMutationOptions<
    UnarchiveParentMutationResponse,
    ResponseErrorConfig<UnarchiveParent404>,
    { parentId: UnarchiveParentPathParams["parentId"] },
    TContext
  >;

  return useMutation<
    UnarchiveParentMutationResponse,
    ResponseErrorConfig<UnarchiveParent404>,
    { parentId: UnarchiveParentPathParams["parentId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UnarchiveParentMutationResponse,
    ResponseErrorConfig<UnarchiveParent404>,
    { parentId: UnarchiveParentPathParams["parentId"] },
    TContext
  >;
}
