/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const archiveEmployeePathParamsSchema = z.object({
  employeeId: z.uuid(),
});

/**
 * @description Colaborador arquivado com sucesso.
 */
export const archiveEmployee204Schema = z.any();

export const archiveEmployeeMutationResponseSchema = z.lazy(
  () => archiveEmployee204Schema,
);
