/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { employeeCreateDTOSchema } from "../employeeCreateDTOSchema.ts";
import { employeeResponseDTOSchema } from "../employeeResponseDTOSchema.ts";
import { z } from "zod/v4";

/**
 * @description Colaborador criado com sucesso.
 */
export const createEmployee201Schema = z.lazy(() => employeeResponseDTOSchema);

export const createEmployeeMutationRequestSchema = z
  .lazy(() => employeeCreateDTOSchema)
  .describe("Formato de payload para criar um novo colaborador");

export const createEmployeeMutationResponseSchema = z.lazy(
  () => createEmployee201Schema,
);
