/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const deleteEmployeePathParamsSchema = z.object({
  employeeId: z.uuid(),
});

/**
 * @description Colaborador deletado com sucesso.
 */
export const deleteEmployee204Schema = z.any();

export const deleteEmployeeMutationResponseSchema = z.lazy(
  () => deleteEmployee204Schema,
);
