/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const unarchiveEmployeePathParamsSchema = z.object({
  employeeId: z.uuid(),
});

/**
 * @description Colaborador desarquivado com sucesso.
 */
export const unarchiveEmployee204Schema = z.any();

export const unarchiveEmployeeMutationResponseSchema = z.lazy(
  () => unarchiveEmployee204Schema,
);
