/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { employeeResponseDTOSchema } from "../employeeResponseDTOSchema.ts";
import { employeeUpdateDTOSchema } from "../employeeUpdateDTOSchema.ts";
import { z } from "zod/v4";

export const updateEmployeePathParamsSchema = z.object({
  employeeId: z.uuid(),
});

/**
 * @description Colaborador atualizado com sucesso.
 */
export const updateEmployee200Schema = z.lazy(() => employeeResponseDTOSchema);

export const updateEmployeeMutationRequestSchema = z
  .lazy(() => employeeUpdateDTOSchema)
  .describe("Formato de payload para o update do colaborador");

export const updateEmployeeMutationResponseSchema = z.lazy(
  () => updateEmployee200Schema,
);
