export type { LoginMutationKey } from "./auth/useLogin.ts";
export type { LogoutMutationKey } from "./auth/useLogout.ts";
export type { MeQueryKey } from "./auth/useMe.ts";
export type { GetDashboardSummaryQueryKey } from "./dashboard-controller/useGetDashboardSummary.ts";
export type { ArchiveEmployeeMutationKey } from "./employee/useArchiveEmployee.ts";
export type { CreateEmployeeMutationKey } from "./employee/useCreateEmployee.ts";
export type { DeleteEmployeeMutationKey } from "./employee/useDeleteEmployee.ts";
export type { GetEmployeeByIdQueryKey } from "./employee/useGetEmployeeById.ts";
export type { GetEmployeeOptionsQueryKey } from "./employee/useGetEmployeeOptions.ts";
export type { GetEmployeesQueryKey } from "./employee/useGetEmployees.ts";
export type { UnarchiveEmployeeMutationKey } from "./employee/useUnarchiveEmployee.ts";
export type { UpdateEmployeeMutationKey } from "./employee/useUpdateEmployee.ts";
export type { CreateEventMutationKey } from "./events/useCreateEvent.ts";
export type { GetEventByIdQueryKey } from "./events/useGetEventById.ts";
export type { GetEventsQueryKey } from "./events/useGetEvents.ts";
export type { GetEventsByEmployeeQueryKey } from "./events/useGetEventsByEmployee.ts";
export type { GetEventsByStudentQueryKey } from "./events/useGetEventsByStudent.ts";
export type { UpdateEventMutationKey } from "./events/useUpdateEvent.ts";
export type { UpdateExpenseStatusMutationKey } from "./events/useUpdateExpenseStatus.ts";
export type { UpdateIncomeStatusMutationKey } from "./events/useUpdateIncomeStatus.ts";
export type { GetFinanceSummaryQueryKey } from "./finance/useGetFinanceSummary.ts";
export type { CreateMutationKey } from "./general expenses/useCreate.ts";
export type { DeleteMutationKey } from "./general expenses/useDelete.ts";
export type { FindAllQueryKey } from "./general expenses/useFindAll.ts";
export type { FindByIdQueryKey } from "./general expenses/useFindById.ts";
export type { UpdateMutationKey } from "./general expenses/useUpdate.ts";
export type { ArchiveParentMutationKey } from "./parent/useArchiveParent.ts";
export type { CreateParentMutationKey } from "./parent/useCreateParent.ts";
export type { DeleteParentMutationKey } from "./parent/useDeleteParent.ts";
export type { GetParentByIdQueryKey } from "./parent/useGetParentById.ts";
export type { GetParentsQueryKey } from "./parent/useGetParents.ts";
export type { GetParentsOptionsQueryKey } from "./parent/useGetParentsOptions.ts";
export type { UnarchiveParentMutationKey } from "./parent/useUnarchiveParent.ts";
export type { UpdateParentMutationKey } from "./parent/useUpdateParent.ts";
export type { ArchiveStudentMutationKey } from "./student/useArchiveStudent.ts";
export type { CreateStudentMutationKey } from "./student/useCreateStudent.ts";
export type { DeleteStudentMutationKey } from "./student/useDeleteStudent.ts";
export type { GetStudentByIdQueryKey } from "./student/useGetStudentById.ts";
export type { GetStudentsQueryKey } from "./student/useGetStudents.ts";
export type { GetStudentsByParentQueryKey } from "./student/useGetStudentsByParent.ts";
export type { GetStudentsOptionsQueryKey } from "./student/useGetStudentsOptions.ts";
export type { UnarchiveStudentMutationKey } from "./student/useUnarchiveStudent.ts";
export type { UpdateStudentMutationKey } from "./student/useUpdateStudent.ts";
export { login } from "./auth/useLogin.ts";
export { loginMutationKey } from "./auth/useLogin.ts";
export { loginMutationOptions } from "./auth/useLogin.ts";
export { useLogin } from "./auth/useLogin.ts";
export { logout } from "./auth/useLogout.ts";
export { logoutMutationKey } from "./auth/useLogout.ts";
export { logoutMutationOptions } from "./auth/useLogout.ts";
export { useLogout } from "./auth/useLogout.ts";
export { me } from "./auth/useMe.ts";
export { meQueryKey } from "./auth/useMe.ts";
export { meQueryOptions } from "./auth/useMe.ts";
export { useMe } from "./auth/useMe.ts";
export { getDashboardSummary } from "./dashboard-controller/useGetDashboardSummary.ts";
export { getDashboardSummaryQueryKey } from "./dashboard-controller/useGetDashboardSummary.ts";
export { getDashboardSummaryQueryOptions } from "./dashboard-controller/useGetDashboardSummary.ts";
export { useGetDashboardSummary } from "./dashboard-controller/useGetDashboardSummary.ts";
export { archiveEmployee } from "./employee/useArchiveEmployee.ts";
export { archiveEmployeeMutationKey } from "./employee/useArchiveEmployee.ts";
export { archiveEmployeeMutationOptions } from "./employee/useArchiveEmployee.ts";
export { useArchiveEmployee } from "./employee/useArchiveEmployee.ts";
export { createEmployee } from "./employee/useCreateEmployee.ts";
export { createEmployeeMutationKey } from "./employee/useCreateEmployee.ts";
export { createEmployeeMutationOptions } from "./employee/useCreateEmployee.ts";
export { useCreateEmployee } from "./employee/useCreateEmployee.ts";
export { deleteEmployee } from "./employee/useDeleteEmployee.ts";
export { deleteEmployeeMutationKey } from "./employee/useDeleteEmployee.ts";
export { deleteEmployeeMutationOptions } from "./employee/useDeleteEmployee.ts";
export { useDeleteEmployee } from "./employee/useDeleteEmployee.ts";
export { getEmployeeById } from "./employee/useGetEmployeeById.ts";
export { getEmployeeByIdQueryKey } from "./employee/useGetEmployeeById.ts";
export { getEmployeeByIdQueryOptions } from "./employee/useGetEmployeeById.ts";
export { useGetEmployeeById } from "./employee/useGetEmployeeById.ts";
export { getEmployeeOptions } from "./employee/useGetEmployeeOptions.ts";
export { getEmployeeOptionsQueryKey } from "./employee/useGetEmployeeOptions.ts";
export { getEmployeeOptionsQueryOptions } from "./employee/useGetEmployeeOptions.ts";
export { useGetEmployeeOptions } from "./employee/useGetEmployeeOptions.ts";
export { getEmployees } from "./employee/useGetEmployees.ts";
export { getEmployeesQueryKey } from "./employee/useGetEmployees.ts";
export { getEmployeesQueryOptions } from "./employee/useGetEmployees.ts";
export { useGetEmployees } from "./employee/useGetEmployees.ts";
export { unarchiveEmployee } from "./employee/useUnarchiveEmployee.ts";
export { unarchiveEmployeeMutationKey } from "./employee/useUnarchiveEmployee.ts";
export { unarchiveEmployeeMutationOptions } from "./employee/useUnarchiveEmployee.ts";
export { useUnarchiveEmployee } from "./employee/useUnarchiveEmployee.ts";
export { updateEmployee } from "./employee/useUpdateEmployee.ts";
export { updateEmployeeMutationKey } from "./employee/useUpdateEmployee.ts";
export { updateEmployeeMutationOptions } from "./employee/useUpdateEmployee.ts";
export { useUpdateEmployee } from "./employee/useUpdateEmployee.ts";
export { createEvent } from "./events/useCreateEvent.ts";
export { createEventMutationKey } from "./events/useCreateEvent.ts";
export { createEventMutationOptions } from "./events/useCreateEvent.ts";
export { useCreateEvent } from "./events/useCreateEvent.ts";
export { getEventById } from "./events/useGetEventById.ts";
export { getEventByIdQueryKey } from "./events/useGetEventById.ts";
export { getEventByIdQueryOptions } from "./events/useGetEventById.ts";
export { useGetEventById } from "./events/useGetEventById.ts";
export { getEvents } from "./events/useGetEvents.ts";
export { getEventsQueryKey } from "./events/useGetEvents.ts";
export { getEventsQueryOptions } from "./events/useGetEvents.ts";
export { useGetEvents } from "./events/useGetEvents.ts";
export { getEventsByEmployee } from "./events/useGetEventsByEmployee.ts";
export { getEventsByEmployeeQueryKey } from "./events/useGetEventsByEmployee.ts";
export { getEventsByEmployeeQueryOptions } from "./events/useGetEventsByEmployee.ts";
export { useGetEventsByEmployee } from "./events/useGetEventsByEmployee.ts";
export { getEventsByStudent } from "./events/useGetEventsByStudent.ts";
export { getEventsByStudentQueryKey } from "./events/useGetEventsByStudent.ts";
export { getEventsByStudentQueryOptions } from "./events/useGetEventsByStudent.ts";
export { useGetEventsByStudent } from "./events/useGetEventsByStudent.ts";
export { updateEvent } from "./events/useUpdateEvent.ts";
export { updateEventMutationKey } from "./events/useUpdateEvent.ts";
export { updateEventMutationOptions } from "./events/useUpdateEvent.ts";
export { useUpdateEvent } from "./events/useUpdateEvent.ts";
export { updateExpenseStatus } from "./events/useUpdateExpenseStatus.ts";
export { updateExpenseStatusMutationKey } from "./events/useUpdateExpenseStatus.ts";
export { updateExpenseStatusMutationOptions } from "./events/useUpdateExpenseStatus.ts";
export { useUpdateExpenseStatus } from "./events/useUpdateExpenseStatus.ts";
export { updateIncomeStatus } from "./events/useUpdateIncomeStatus.ts";
export { updateIncomeStatusMutationKey } from "./events/useUpdateIncomeStatus.ts";
export { updateIncomeStatusMutationOptions } from "./events/useUpdateIncomeStatus.ts";
export { useUpdateIncomeStatus } from "./events/useUpdateIncomeStatus.ts";
export { getFinanceSummary } from "./finance/useGetFinanceSummary.ts";
export { getFinanceSummaryQueryKey } from "./finance/useGetFinanceSummary.ts";
export { getFinanceSummaryQueryOptions } from "./finance/useGetFinanceSummary.ts";
export { useGetFinanceSummary } from "./finance/useGetFinanceSummary.ts";
export { create } from "./general expenses/useCreate.ts";
export { createMutationKey } from "./general expenses/useCreate.ts";
export { createMutationOptions } from "./general expenses/useCreate.ts";
export { useCreate } from "./general expenses/useCreate.ts";
export { _delete } from "./general expenses/useDelete.ts";
export { deleteMutationKey } from "./general expenses/useDelete.ts";
export { deleteMutationOptions } from "./general expenses/useDelete.ts";
export { useDelete } from "./general expenses/useDelete.ts";
export { findAll } from "./general expenses/useFindAll.ts";
export { findAllQueryKey } from "./general expenses/useFindAll.ts";
export { findAllQueryOptions } from "./general expenses/useFindAll.ts";
export { useFindAll } from "./general expenses/useFindAll.ts";
export { findById } from "./general expenses/useFindById.ts";
export { findByIdQueryKey } from "./general expenses/useFindById.ts";
export { findByIdQueryOptions } from "./general expenses/useFindById.ts";
export { useFindById } from "./general expenses/useFindById.ts";
export { update } from "./general expenses/useUpdate.ts";
export { updateMutationKey } from "./general expenses/useUpdate.ts";
export { updateMutationOptions } from "./general expenses/useUpdate.ts";
export { useUpdate } from "./general expenses/useUpdate.ts";
export { archiveParent } from "./parent/useArchiveParent.ts";
export { archiveParentMutationKey } from "./parent/useArchiveParent.ts";
export { archiveParentMutationOptions } from "./parent/useArchiveParent.ts";
export { useArchiveParent } from "./parent/useArchiveParent.ts";
export { createParent } from "./parent/useCreateParent.ts";
export { createParentMutationKey } from "./parent/useCreateParent.ts";
export { createParentMutationOptions } from "./parent/useCreateParent.ts";
export { useCreateParent } from "./parent/useCreateParent.ts";
export { deleteParent } from "./parent/useDeleteParent.ts";
export { deleteParentMutationKey } from "./parent/useDeleteParent.ts";
export { deleteParentMutationOptions } from "./parent/useDeleteParent.ts";
export { useDeleteParent } from "./parent/useDeleteParent.ts";
export { getParentById } from "./parent/useGetParentById.ts";
export { getParentByIdQueryKey } from "./parent/useGetParentById.ts";
export { getParentByIdQueryOptions } from "./parent/useGetParentById.ts";
export { useGetParentById } from "./parent/useGetParentById.ts";
export { getParents } from "./parent/useGetParents.ts";
export { getParentsQueryKey } from "./parent/useGetParents.ts";
export { getParentsQueryOptions } from "./parent/useGetParents.ts";
export { useGetParents } from "./parent/useGetParents.ts";
export { getParentsOptions } from "./parent/useGetParentsOptions.ts";
export { getParentsOptionsQueryKey } from "./parent/useGetParentsOptions.ts";
export { getParentsOptionsQueryOptions } from "./parent/useGetParentsOptions.ts";
export { useGetParentsOptions } from "./parent/useGetParentsOptions.ts";
export { unarchiveParent } from "./parent/useUnarchiveParent.ts";
export { unarchiveParentMutationKey } from "./parent/useUnarchiveParent.ts";
export { unarchiveParentMutationOptions } from "./parent/useUnarchiveParent.ts";
export { useUnarchiveParent } from "./parent/useUnarchiveParent.ts";
export { updateParent } from "./parent/useUpdateParent.ts";
export { updateParentMutationKey } from "./parent/useUpdateParent.ts";
export { updateParentMutationOptions } from "./parent/useUpdateParent.ts";
export { useUpdateParent } from "./parent/useUpdateParent.ts";
export { archiveStudent } from "./student/useArchiveStudent.ts";
export { archiveStudentMutationKey } from "./student/useArchiveStudent.ts";
export { archiveStudentMutationOptions } from "./student/useArchiveStudent.ts";
export { useArchiveStudent } from "./student/useArchiveStudent.ts";
export { createStudent } from "./student/useCreateStudent.ts";
export { createStudentMutationKey } from "./student/useCreateStudent.ts";
export { createStudentMutationOptions } from "./student/useCreateStudent.ts";
export { useCreateStudent } from "./student/useCreateStudent.ts";
export { deleteStudent } from "./student/useDeleteStudent.ts";
export { deleteStudentMutationKey } from "./student/useDeleteStudent.ts";
export { deleteStudentMutationOptions } from "./student/useDeleteStudent.ts";
export { useDeleteStudent } from "./student/useDeleteStudent.ts";
export { getStudentById } from "./student/useGetStudentById.ts";
export { getStudentByIdQueryKey } from "./student/useGetStudentById.ts";
export { getStudentByIdQueryOptions } from "./student/useGetStudentById.ts";
export { useGetStudentById } from "./student/useGetStudentById.ts";
export { getStudents } from "./student/useGetStudents.ts";
export { getStudentsQueryKey } from "./student/useGetStudents.ts";
export { getStudentsQueryOptions } from "./student/useGetStudents.ts";
export { useGetStudents } from "./student/useGetStudents.ts";
export { getStudentsByParent } from "./student/useGetStudentsByParent.ts";
export { getStudentsByParentQueryKey } from "./student/useGetStudentsByParent.ts";
export { getStudentsByParentQueryOptions } from "./student/useGetStudentsByParent.ts";
export { useGetStudentsByParent } from "./student/useGetStudentsByParent.ts";
export { getStudentsOptions } from "./student/useGetStudentsOptions.ts";
export { getStudentsOptionsQueryKey } from "./student/useGetStudentsOptions.ts";
export { getStudentsOptionsQueryOptions } from "./student/useGetStudentsOptions.ts";
export { useGetStudentsOptions } from "./student/useGetStudentsOptions.ts";
export { unarchiveStudent } from "./student/useUnarchiveStudent.ts";
export { unarchiveStudentMutationKey } from "./student/useUnarchiveStudent.ts";
export { unarchiveStudentMutationOptions } from "./student/useUnarchiveStudent.ts";
export { useUnarchiveStudent } from "./student/useUnarchiveStudent.ts";
export { updateStudent } from "./student/useUpdateStudent.ts";
export { updateStudentMutationKey } from "./student/useUpdateStudent.ts";
export { updateStudentMutationOptions } from "./student/useUpdateStudent.ts";
export { useUpdateStudent } from "./student/useUpdateStudent.ts";
