export type { AgendarAtendimentoMutationKey } from "./useAgendarAtendimento.ts";
export type { CancelarAtendimentoMutationKey } from "./useCancelarAtendimento.ts";
export type { ConcluirAtendimentoMutationKey } from "./useConcluirAtendimento.ts";
export type { ExcluirAtendimentoMutationKey } from "./useExcluirAtendimento.ts";
export type { GetAtendimentoByIdQueryKey } from "./useGetAtendimentoById.ts";
export type { GetAtendimentosQueryKey } from "./useGetAtendimentos.ts";
export type { GetDashboardQueryKey } from "./useGetDashboard.ts";
export type { ReagendarAtendimentoMutationKey } from "./useReagendarAtendimento.ts";
export { agendarAtendimento } from "./useAgendarAtendimento.ts";
export { agendarAtendimentoMutationKey } from "./useAgendarAtendimento.ts";
export { agendarAtendimentoMutationOptions } from "./useAgendarAtendimento.ts";
export { useAgendarAtendimento } from "./useAgendarAtendimento.ts";
export { cancelarAtendimento } from "./useCancelarAtendimento.ts";
export { cancelarAtendimentoMutationKey } from "./useCancelarAtendimento.ts";
export { cancelarAtendimentoMutationOptions } from "./useCancelarAtendimento.ts";
export { useCancelarAtendimento } from "./useCancelarAtendimento.ts";
export { concluirAtendimento } from "./useConcluirAtendimento.ts";
export { concluirAtendimentoMutationKey } from "./useConcluirAtendimento.ts";
export { concluirAtendimentoMutationOptions } from "./useConcluirAtendimento.ts";
export { useConcluirAtendimento } from "./useConcluirAtendimento.ts";
export { excluirAtendimento } from "./useExcluirAtendimento.ts";
export { excluirAtendimentoMutationKey } from "./useExcluirAtendimento.ts";
export { excluirAtendimentoMutationOptions } from "./useExcluirAtendimento.ts";
export { useExcluirAtendimento } from "./useExcluirAtendimento.ts";
export { getAtendimentoById } from "./useGetAtendimentoById.ts";
export { getAtendimentoByIdQueryKey } from "./useGetAtendimentoById.ts";
export { getAtendimentoByIdQueryOptions } from "./useGetAtendimentoById.ts";
export { useGetAtendimentoById } from "./useGetAtendimentoById.ts";
export { getAtendimentos } from "./useGetAtendimentos.ts";
export { getAtendimentosQueryKey } from "./useGetAtendimentos.ts";
export { getAtendimentosQueryOptions } from "./useGetAtendimentos.ts";
export { useGetAtendimentos } from "./useGetAtendimentos.ts";
export { getDashboard } from "./useGetDashboard.ts";
export { getDashboardQueryKey } from "./useGetDashboard.ts";
export { getDashboardQueryOptions } from "./useGetDashboard.ts";
export { useGetDashboard } from "./useGetDashboard.ts";
export { reagendarAtendimento } from "./useReagendarAtendimento.ts";
export { reagendarAtendimentoMutationKey } from "./useReagendarAtendimento.ts";
export { reagendarAtendimentoMutationOptions } from "./useReagendarAtendimento.ts";
export { useReagendarAtendimento } from "./useReagendarAtendimento.ts";
