/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  AlternarPagamentoColaboradorAtendimentoMutationResponse,
  AlternarPagamentoColaboradorAtendimentoPathParams,
  AlternarPagamentoColaboradorAtendimento404,
  AlternarPagamentoColaboradorAtendimento500,
} from "../../types/atendimento/AlternarPagamentoColaboradorAtendimento.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const alternarPagamentoColaboradorAtendimentoMutationKey = () =>
  [{ url: "/v1/atendimentos/:id/alternar-pagamento-colaborador" }] as const;

export type AlternarPagamentoColaboradorAtendimentoMutationKey = ReturnType<
  typeof alternarPagamentoColaboradorAtendimentoMutationKey
>;

/**
 * @description Alterna a baixa financeira do colaborador para o atendimento.
 * {@link /v1/atendimentos/:id/alternar-pagamento-colaborador}
 */
export async function alternarPagamentoColaboradorAtendimento(
  id: AlternarPagamentoColaboradorAtendimentoPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AlternarPagamentoColaboradorAtendimentoMutationResponse,
    ResponseErrorConfig<
      | AlternarPagamentoColaboradorAtendimento404
      | AlternarPagamentoColaboradorAtendimento500
    >,
    unknown
  >({
    method: "PATCH",
    url: `/v1/atendimentos/${id}/alternar-pagamento-colaborador`,
    ...requestConfig,
  });
  return res.data;
}

export function alternarPagamentoColaboradorAtendimentoMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = alternarPagamentoColaboradorAtendimentoMutationKey();
  return mutationOptions<
    AlternarPagamentoColaboradorAtendimentoMutationResponse,
    ResponseErrorConfig<
      | AlternarPagamentoColaboradorAtendimento404
      | AlternarPagamentoColaboradorAtendimento500
    >,
    { id: AlternarPagamentoColaboradorAtendimentoPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return alternarPagamentoColaboradorAtendimento(id, config);
    },
  });
}

/**
 * @description Alterna a baixa financeira do colaborador para o atendimento.
 * {@link /v1/atendimentos/:id/alternar-pagamento-colaborador}
 */
export function useAlternarPagamentoColaboradorAtendimento<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AlternarPagamentoColaboradorAtendimentoMutationResponse,
      ResponseErrorConfig<
        | AlternarPagamentoColaboradorAtendimento404
        | AlternarPagamentoColaboradorAtendimento500
      >,
      { id: AlternarPagamentoColaboradorAtendimentoPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    alternarPagamentoColaboradorAtendimentoMutationKey();

  const baseOptions = alternarPagamentoColaboradorAtendimentoMutationOptions(
    config,
  ) as UseMutationOptions<
    AlternarPagamentoColaboradorAtendimentoMutationResponse,
    ResponseErrorConfig<
      | AlternarPagamentoColaboradorAtendimento404
      | AlternarPagamentoColaboradorAtendimento500
    >,
    { id: AlternarPagamentoColaboradorAtendimentoPathParams["id"] },
    TContext
  >;

  return useMutation<
    AlternarPagamentoColaboradorAtendimentoMutationResponse,
    ResponseErrorConfig<
      | AlternarPagamentoColaboradorAtendimento404
      | AlternarPagamentoColaboradorAtendimento500
    >,
    { id: AlternarPagamentoColaboradorAtendimentoPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AlternarPagamentoColaboradorAtendimentoMutationResponse,
    ResponseErrorConfig<
      | AlternarPagamentoColaboradorAtendimento404
      | AlternarPagamentoColaboradorAtendimento500
    >,
    { id: AlternarPagamentoColaboradorAtendimentoPathParams["id"] },
    TContext
  >;
}
