/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/services/api";
import type {
  CancelarAtendimentoMutationResponse,
  CancelarAtendimentoPathParams,
} from "../../types/CancelarAtendimento.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/services/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const cancelarAtendimentoMutationKey = () =>
  [{ url: "/v1/atendimentos/:id/cancelar" }] as const;

export type CancelarAtendimentoMutationKey = ReturnType<
  typeof cancelarAtendimentoMutationKey
>;

/**
 * @description Muda o status de um atendimento para CANCELADO.
 * {@link /v1/atendimentos/:id/cancelar}
 */
export async function cancelarAtendimento(
  id: CancelarAtendimentoPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CancelarAtendimentoMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "PATCH",
    url: `/v1/atendimentos/${id}/cancelar`,
    ...requestConfig,
  });
  return res.data;
}

export function cancelarAtendimentoMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = cancelarAtendimentoMutationKey();
  return mutationOptions<
    CancelarAtendimentoMutationResponse,
    ResponseErrorConfig<Error>,
    { id: CancelarAtendimentoPathParams["id"] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return cancelarAtendimento(id, config);
    },
  });
}

/**
 * @description Muda o status de um atendimento para CANCELADO.
 * {@link /v1/atendimentos/:id/cancelar}
 */
export function useCancelarAtendimento<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CancelarAtendimentoMutationResponse,
      ResponseErrorConfig<Error>,
      { id: CancelarAtendimentoPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? cancelarAtendimentoMutationKey();

  const baseOptions = cancelarAtendimentoMutationOptions(
    config,
  ) as UseMutationOptions<
    CancelarAtendimentoMutationResponse,
    ResponseErrorConfig<Error>,
    { id: CancelarAtendimentoPathParams["id"] },
    TContext
  >;

  return useMutation<
    CancelarAtendimentoMutationResponse,
    ResponseErrorConfig<Error>,
    { id: CancelarAtendimentoPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CancelarAtendimentoMutationResponse,
    ResponseErrorConfig<Error>,
    { id: CancelarAtendimentoPathParams["id"] },
    TContext
  >;
}
