/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CreateAtendimentoMutationRequest,
  CreateAtendimentoMutationResponse,
  CreateAtendimento400,
  CreateAtendimento409,
  CreateAtendimento500,
} from "../../types/atendimento/CreateAtendimento.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createAtendimentoMutationKey = () =>
  [{ url: "/v1/atendimentos" }] as const;

export type CreateAtendimentoMutationKey = ReturnType<
  typeof createAtendimentoMutationKey
>;

/**
 * @description Cria um atendimento vinculando aluno e colaborador.
 * {@link /v1/atendimentos}
 */
export async function createAtendimento(
  data: CreateAtendimentoMutationRequest,
  config: Partial<RequestConfig<CreateAtendimentoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateAtendimentoMutationResponse,
    ResponseErrorConfig<
      CreateAtendimento400 | CreateAtendimento409 | CreateAtendimento500
    >,
    CreateAtendimentoMutationRequest
  >({
    method: "POST",
    url: `/v1/atendimentos`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createAtendimentoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateAtendimentoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createAtendimentoMutationKey();
  return mutationOptions<
    CreateAtendimentoMutationResponse,
    ResponseErrorConfig<
      CreateAtendimento400 | CreateAtendimento409 | CreateAtendimento500
    >,
    { data: CreateAtendimentoMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createAtendimento(data, config);
    },
  });
}

/**
 * @description Cria um atendimento vinculando aluno e colaborador.
 * {@link /v1/atendimentos}
 */
export function useCreateAtendimento<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateAtendimentoMutationResponse,
      ResponseErrorConfig<
        CreateAtendimento400 | CreateAtendimento409 | CreateAtendimento500
      >,
      { data: CreateAtendimentoMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateAtendimentoMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createAtendimentoMutationKey();

  const baseOptions = createAtendimentoMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateAtendimentoMutationResponse,
    ResponseErrorConfig<
      CreateAtendimento400 | CreateAtendimento409 | CreateAtendimento500
    >,
    { data: CreateAtendimentoMutationRequest },
    TContext
  >;

  return useMutation<
    CreateAtendimentoMutationResponse,
    ResponseErrorConfig<
      CreateAtendimento400 | CreateAtendimento409 | CreateAtendimento500
    >,
    { data: CreateAtendimentoMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateAtendimentoMutationResponse,
    ResponseErrorConfig<
      CreateAtendimento400 | CreateAtendimento409 | CreateAtendimento500
    >,
    { data: CreateAtendimentoMutationRequest },
    TContext
  >;
}
