/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetOverviewFinanceiroAlunosQueryResponse,
  GetOverviewFinanceiroAlunosQueryParams,
  GetOverviewFinanceiroAlunos400,
  GetOverviewFinanceiroAlunos500,
} from "../../types/atendimento/GetOverviewFinanceiroAlunos.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getOverviewFinanceiroAlunosQueryKey = (
  params?: GetOverviewFinanceiroAlunosQueryParams,
) =>
  [
    { url: "/v1/atendimentos/relatorio/alunos" },
    ...(params ? [params] : []),
  ] as const;

export type GetOverviewFinanceiroAlunosQueryKey = ReturnType<
  typeof getOverviewFinanceiroAlunosQueryKey
>;

/**
 * @description Lista alunos paginados com indicadores de cobrado e pendente por aluno.
 * {@link /v1/atendimentos/relatorio/alunos}
 */
export async function getOverviewFinanceiroAlunos(
  params?: GetOverviewFinanceiroAlunosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetOverviewFinanceiroAlunosQueryResponse,
    ResponseErrorConfig<
      GetOverviewFinanceiroAlunos400 | GetOverviewFinanceiroAlunos500
    >,
    unknown
  >({
    method: "GET",
    url: `/v1/atendimentos/relatorio/alunos`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getOverviewFinanceiroAlunosQueryOptions(
  params?: GetOverviewFinanceiroAlunosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getOverviewFinanceiroAlunosQueryKey(params);
  return queryOptions<
    GetOverviewFinanceiroAlunosQueryResponse,
    ResponseErrorConfig<
      GetOverviewFinanceiroAlunos400 | GetOverviewFinanceiroAlunos500
    >,
    GetOverviewFinanceiroAlunosQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getOverviewFinanceiroAlunos(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista alunos paginados com indicadores de cobrado e pendente por aluno.
 * {@link /v1/atendimentos/relatorio/alunos}
 */
export function useGetOverviewFinanceiroAlunos<
  TData = GetOverviewFinanceiroAlunosQueryResponse,
  TQueryData = GetOverviewFinanceiroAlunosQueryResponse,
  TQueryKey extends QueryKey = GetOverviewFinanceiroAlunosQueryKey,
>(
  params?: GetOverviewFinanceiroAlunosQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetOverviewFinanceiroAlunosQueryResponse,
        ResponseErrorConfig<
          GetOverviewFinanceiroAlunos400 | GetOverviewFinanceiroAlunos500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getOverviewFinanceiroAlunosQueryKey(params);

  const query = useQuery(
    {
      ...getOverviewFinanceiroAlunosQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetOverviewFinanceiroAlunos400 | GetOverviewFinanceiroAlunos500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
