/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetOverviewFinanceiroColaboradoresQueryResponse,
  GetOverviewFinanceiroColaboradoresQueryParams,
  GetOverviewFinanceiroColaboradores400,
  GetOverviewFinanceiroColaboradores500,
} from "../../types/atendimento/GetOverviewFinanceiroColaboradores.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getOverviewFinanceiroColaboradoresQueryKey = (
  params?: GetOverviewFinanceiroColaboradoresQueryParams,
) =>
  [
    { url: "/v1/atendimentos/relatorio/colaboradores" },
    ...(params ? [params] : []),
  ] as const;

export type GetOverviewFinanceiroColaboradoresQueryKey = ReturnType<
  typeof getOverviewFinanceiroColaboradoresQueryKey
>;

/**
 * @description Lista colaboradores paginados com indicadores de pago e pendente por colaborador.
 * {@link /v1/atendimentos/relatorio/colaboradores}
 */
export async function getOverviewFinanceiroColaboradores(
  params?: GetOverviewFinanceiroColaboradoresQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetOverviewFinanceiroColaboradoresQueryResponse,
    ResponseErrorConfig<
      | GetOverviewFinanceiroColaboradores400
      | GetOverviewFinanceiroColaboradores500
    >,
    unknown
  >({
    method: "GET",
    url: `/v1/atendimentos/relatorio/colaboradores`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getOverviewFinanceiroColaboradoresQueryOptions(
  params?: GetOverviewFinanceiroColaboradoresQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getOverviewFinanceiroColaboradoresQueryKey(params);
  return queryOptions<
    GetOverviewFinanceiroColaboradoresQueryResponse,
    ResponseErrorConfig<
      | GetOverviewFinanceiroColaboradores400
      | GetOverviewFinanceiroColaboradores500
    >,
    GetOverviewFinanceiroColaboradoresQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getOverviewFinanceiroColaboradores(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista colaboradores paginados com indicadores de pago e pendente por colaborador.
 * {@link /v1/atendimentos/relatorio/colaboradores}
 */
export function useGetOverviewFinanceiroColaboradores<
  TData = GetOverviewFinanceiroColaboradoresQueryResponse,
  TQueryData = GetOverviewFinanceiroColaboradoresQueryResponse,
  TQueryKey extends QueryKey = GetOverviewFinanceiroColaboradoresQueryKey,
>(
  params?: GetOverviewFinanceiroColaboradoresQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetOverviewFinanceiroColaboradoresQueryResponse,
        ResponseErrorConfig<
          | GetOverviewFinanceiroColaboradores400
          | GetOverviewFinanceiroColaboradores500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getOverviewFinanceiroColaboradoresQueryKey(params);

  const query = useQuery(
    {
      ...getOverviewFinanceiroColaboradoresQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetOverviewFinanceiroColaboradores400
      | GetOverviewFinanceiroColaboradores500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
