/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetCalendarioAtendimentosQueryResponse,
  GetCalendarioAtendimentosQueryParams,
} from "../../types/atendimento/GetCalendarioAtendimentos.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCalendarioAtendimentosQueryKey = (
  params: GetCalendarioAtendimentosQueryParams,
) =>
  [
    { url: "/v1/atendimentos/calendario" },
    ...(params ? [params] : []),
  ] as const;

export type GetCalendarioAtendimentosQueryKey = ReturnType<
  typeof getCalendarioAtendimentosQueryKey
>;

/**
 * @description Retorna o conteúdo para montar o calendário de atendimentos.
 * {@link /v1/atendimentos/calendario}
 */
export async function getCalendarioAtendimentos(
  params: GetCalendarioAtendimentosQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCalendarioAtendimentosQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/atendimentos/calendario`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getCalendarioAtendimentosQueryOptions(
  params: GetCalendarioAtendimentosQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getCalendarioAtendimentosQueryKey(params);
  return queryOptions<
    GetCalendarioAtendimentosQueryResponse,
    ResponseErrorConfig<Error>,
    GetCalendarioAtendimentosQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getCalendarioAtendimentos(params, config);
    },
  });
}

/**
 * @description Retorna o conteúdo para montar o calendário de atendimentos.
 * {@link /v1/atendimentos/calendario}
 */
export function useGetCalendarioAtendimentos<
  TData = GetCalendarioAtendimentosQueryResponse,
  TQueryData = GetCalendarioAtendimentosQueryResponse,
  TQueryKey extends QueryKey = GetCalendarioAtendimentosQueryKey,
>(
  params: GetCalendarioAtendimentosQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetCalendarioAtendimentosQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getCalendarioAtendimentosQueryKey(params);

  const query = useQuery(
    {
      ...getCalendarioAtendimentosQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
