/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetRelatorioAtendimentosQueryResponse, GetRelatorioAtendimentosQueryParams } from "../../types/atendimento/GetRelatorioAtendimentos.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getRelatorioAtendimentosQueryKey = (params: GetRelatorioAtendimentosQueryParams) => [{ url: '/v1/atendimentos/relatorio' }, ...(params ? [params] : [])] as const

export type GetRelatorioAtendimentosQueryKey = ReturnType<typeof getRelatorioAtendimentosQueryKey>

/**
 * @description Retorna o conteúdo para montar o relatório.
 * {@link /v1/atendimentos/relatorio}
 */
export async function getRelatorioAtendimentos(params: GetRelatorioAtendimentosQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetRelatorioAtendimentosQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/atendimentos/relatorio`, params, ... requestConfig })  
  return res.data
}

export function getRelatorioAtendimentosQueryOptions(params: GetRelatorioAtendimentosQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRelatorioAtendimentosQueryKey(params)
  return queryOptions<GetRelatorioAtendimentosQueryResponse, ResponseErrorConfig<Error>, GetRelatorioAtendimentosQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getRelatorioAtendimentos(params, config)
   },
  })
}

/**
 * @description Retorna o conteúdo para montar o relatório.
 * {@link /v1/atendimentos/relatorio}
 */
export function useGetRelatorioAtendimentos<TData = GetRelatorioAtendimentosQueryResponse, TQueryData = GetRelatorioAtendimentosQueryResponse, TQueryKey extends QueryKey = GetRelatorioAtendimentosQueryKey>(params: GetRelatorioAtendimentosQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetRelatorioAtendimentosQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getRelatorioAtendimentosQueryKey(params)

  const query = useQuery({
   ...getRelatorioAtendimentosQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}