/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetAtendimentosQueryResponse,
  GetAtendimentosQueryParams,
  GetAtendimentos400,
  GetAtendimentos500,
} from "../../types/atendimento/GetAtendimentos.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAtendimentosQueryKey = (params?: GetAtendimentosQueryParams) =>
  [{ url: "/v1/atendimentos" }, ...(params ? [params] : [])] as const;

export type GetAtendimentosQueryKey = ReturnType<
  typeof getAtendimentosQueryKey
>;

/**
 * @description Lista atendimentos com paginacao, ordenacao e filtros opcionais por texto, periodo, cobranca do aluno e pagamento do colaborador.
 * {@link /v1/atendimentos}
 */
export async function getAtendimentos(
  params?: GetAtendimentosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAtendimentosQueryResponse,
    ResponseErrorConfig<GetAtendimentos400 | GetAtendimentos500>,
    unknown
  >({ method: "GET", url: `/v1/atendimentos`, params, ...requestConfig });
  return res.data;
}

export function getAtendimentosQueryOptions(
  params?: GetAtendimentosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAtendimentosQueryKey(params);
  return queryOptions<
    GetAtendimentosQueryResponse,
    ResponseErrorConfig<GetAtendimentos400 | GetAtendimentos500>,
    GetAtendimentosQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getAtendimentos(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista atendimentos com paginacao, ordenacao e filtros opcionais por texto, periodo, cobranca do aluno e pagamento do colaborador.
 * {@link /v1/atendimentos}
 */
export function useGetAtendimentos<
  TData = GetAtendimentosQueryResponse,
  TQueryData = GetAtendimentosQueryResponse,
  TQueryKey extends QueryKey = GetAtendimentosQueryKey,
>(
  params?: GetAtendimentosQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAtendimentosQueryResponse,
        ResponseErrorConfig<GetAtendimentos400 | GetAtendimentos500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getAtendimentosQueryKey(params);

  const query = useQuery(
    {
      ...getAtendimentosQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetAtendimentos400 | GetAtendimentos500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
