/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetDashboardQueryResponse,
  GetDashboardQueryParams,
} from "../../types/atendimento/GetDashboard.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDashboardQueryKey = (params: GetDashboardQueryParams) =>
  [{ url: "/v1/atendimentos/dashboard" }, ...(params ? [params] : [])] as const;

export type GetDashboardQueryKey = ReturnType<typeof getDashboardQueryKey>;

/**
 * @description Retorna o conteúdo para montar o dashboard.
 * {@link /v1/atendimentos/dashboard}
 */
export async function getDashboard(
  params: GetDashboardQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDashboardQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/v1/atendimentos/dashboard`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getDashboardQueryOptions(
  params: GetDashboardQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDashboardQueryKey(params);
  return queryOptions<
    GetDashboardQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboard(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna o conteúdo para montar o dashboard.
 * {@link /v1/atendimentos/dashboard}
 */
export function useGetDashboard<
  TData = GetDashboardQueryResponse,
  TQueryData = GetDashboardQueryResponse,
  TQueryKey extends QueryKey = GetDashboardQueryKey,
>(
  params: GetDashboardQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDashboardQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getDashboardQueryKey(params);

  const query = useQuery(
    {
      ...getDashboardQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
