/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ToggleStudentAtendimentoChargeMutationResponse,
  ToggleStudentAtendimentoChargePathParams,
  ToggleStudentAtendimentoCharge404,
  ToggleStudentAtendimentoCharge500,
} from "../../types/atendimento/ToggleStudentAtendimentoCharge.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const toggleStudentAtendimentoChargeMutationKey = () =>
  [{ url: "/v1/atendimentos/:id/toggle-student-charge" }] as const;

export type ToggleStudentAtendimentoChargeMutationKey = ReturnType<
  typeof toggleStudentAtendimentoChargeMutationKey
>;

/**
 * @description Alterna a baixa financeira do aluno para o atendimento.
 * {@link /v1/atendimentos/:id/toggle-student-charge}
 */
export async function toggleStudentAtendimentoCharge(
  id: ToggleStudentAtendimentoChargePathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ToggleStudentAtendimentoChargeMutationResponse,
    ResponseErrorConfig<
      ToggleStudentAtendimentoCharge404 | ToggleStudentAtendimentoCharge500
    >,
    unknown
  >({
    method: "PATCH",
    url: `/v1/atendimentos/${id}/toggle-student-charge`,
    ...requestConfig,
  });
  return res.data;
}

export function toggleStudentAtendimentoChargeMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = toggleStudentAtendimentoChargeMutationKey();
  return mutationOptions<
    ToggleStudentAtendimentoChargeMutationResponse,
    ResponseErrorConfig<
      ToggleStudentAtendimentoCharge404 | ToggleStudentAtendimentoCharge500
    >,
    { id: ToggleStudentAtendimentoChargePathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return toggleStudentAtendimentoCharge(id, config);
    },
  });
}

/**
 * @description Alterna a baixa financeira do aluno para o atendimento.
 * {@link /v1/atendimentos/:id/toggle-student-charge}
 */
export function useToggleStudentAtendimentoCharge<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ToggleStudentAtendimentoChargeMutationResponse,
      ResponseErrorConfig<
        ToggleStudentAtendimentoCharge404 | ToggleStudentAtendimentoCharge500
      >,
      { id: ToggleStudentAtendimentoChargePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? toggleStudentAtendimentoChargeMutationKey();

  const baseOptions = toggleStudentAtendimentoChargeMutationOptions(
    config,
  ) as UseMutationOptions<
    ToggleStudentAtendimentoChargeMutationResponse,
    ResponseErrorConfig<
      ToggleStudentAtendimentoCharge404 | ToggleStudentAtendimentoCharge500
    >,
    { id: ToggleStudentAtendimentoChargePathParams["id"] },
    TContext
  >;

  return useMutation<
    ToggleStudentAtendimentoChargeMutationResponse,
    ResponseErrorConfig<
      ToggleStudentAtendimentoCharge404 | ToggleStudentAtendimentoCharge500
    >,
    { id: ToggleStudentAtendimentoChargePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ToggleStudentAtendimentoChargeMutationResponse,
    ResponseErrorConfig<
      ToggleStudentAtendimentoCharge404 | ToggleStudentAtendimentoCharge500
    >,
    { id: ToggleStudentAtendimentoChargePathParams["id"] },
    TContext
  >;
}
