/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UpdateAtendimentoMutationRequest,
  UpdateAtendimentoMutationResponse,
  UpdateAtendimentoPathParams,
  UpdateAtendimento400,
  UpdateAtendimento404,
  UpdateAtendimento409,
  UpdateAtendimento500,
} from "../../types/atendimento/UpdateAtendimento.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateAtendimentoMutationKey = () =>
  [{ url: "/v1/atendimentos/:id" }] as const;

export type UpdateAtendimentoMutationKey = ReturnType<
  typeof updateAtendimentoMutationKey
>;

/**
 * @description Atualiza dados cadastrais do atendimento.
 * {@link /v1/atendimentos/:id}
 */
export async function updateAtendimento(
  id: UpdateAtendimentoPathParams["id"],
  data: UpdateAtendimentoMutationRequest,
  config: Partial<RequestConfig<UpdateAtendimentoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateAtendimentoMutationResponse,
    ResponseErrorConfig<
      | UpdateAtendimento400
      | UpdateAtendimento404
      | UpdateAtendimento409
      | UpdateAtendimento500
    >,
    UpdateAtendimentoMutationRequest
  >({
    method: "PUT",
    url: `/v1/atendimentos/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateAtendimentoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateAtendimentoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updateAtendimentoMutationKey();
  return mutationOptions<
    UpdateAtendimentoMutationResponse,
    ResponseErrorConfig<
      | UpdateAtendimento400
      | UpdateAtendimento404
      | UpdateAtendimento409
      | UpdateAtendimento500
    >,
    {
      id: UpdateAtendimentoPathParams["id"];
      data: UpdateAtendimentoMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return updateAtendimento(id, data, config);
    },
  });
}

/**
 * @description Atualiza dados cadastrais do atendimento.
 * {@link /v1/atendimentos/:id}
 */
export function useUpdateAtendimento<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateAtendimentoMutationResponse,
      ResponseErrorConfig<
        | UpdateAtendimento400
        | UpdateAtendimento404
        | UpdateAtendimento409
        | UpdateAtendimento500
      >,
      {
        id: UpdateAtendimentoPathParams["id"];
        data: UpdateAtendimentoMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateAtendimentoMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateAtendimentoMutationKey();

  const baseOptions = updateAtendimentoMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateAtendimentoMutationResponse,
    ResponseErrorConfig<
      | UpdateAtendimento400
      | UpdateAtendimento404
      | UpdateAtendimento409
      | UpdateAtendimento500
    >,
    {
      id: UpdateAtendimentoPathParams["id"];
      data: UpdateAtendimentoMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdateAtendimentoMutationResponse,
    ResponseErrorConfig<
      | UpdateAtendimento400
      | UpdateAtendimento404
      | UpdateAtendimento409
      | UpdateAtendimento500
    >,
    {
      id: UpdateAtendimentoPathParams["id"];
      data: UpdateAtendimentoMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateAtendimentoMutationResponse,
    ResponseErrorConfig<
      | UpdateAtendimento400
      | UpdateAtendimento404
      | UpdateAtendimento409
      | UpdateAtendimento500
    >,
    {
      id: UpdateAtendimentoPathParams["id"];
      data: UpdateAtendimentoMutationRequest;
    },
    TContext
  >;
}
