@startuml
set separator none
title AprimorarAplication

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("AprimorarAplication.AprimorarAplication_boundary", "AprimorarAplication", $tags="") {
  Component(AprimorarAplication.AprimorarAplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
  Component(AprimorarAplication.AprimorarAplication.Autenticação, "Autenticação", $techn="Module", $descr="", $tags="", $link="")
  Component(AprimorarAplication.AprimorarAplication.Financeiro, "Financeiro", $techn="Module", $descr="", $tags="", $link="")
  Component(AprimorarAplication.AprimorarAplication.Instituição, "Instituição", $techn="Module", $descr="", $tags="", $link="")
}

Rel(AprimorarAplication.AprimorarAplication.Instituição, AprimorarAplication.AprimorarAplication.Common, "depends on", $techn="", $tags="", $link="")
Rel(AprimorarAplication.AprimorarAplication.Instituição, AprimorarAplication.AprimorarAplication.Financeiro, "uses", $techn="", $tags="", $link="")
Rel(AprimorarAplication.AprimorarAplication.Financeiro, AprimorarAplication.AprimorarAplication.Common, "depends on", $techn="", $tags="", $link="")
Rel(AprimorarAplication.AprimorarAplication.Autenticação, AprimorarAplication.AprimorarAplication.Common, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml