@startuml
set separator none
title Common

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("AprimorarAplication.AprimorarAplication_boundary", "AprimorarAplication", $tags="") {
  Component(AprimorarAplication.AprimorarAplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml